/**
 * JLPT N2 Vocabulary Data (800+ words)
 * Structure: [Word, Reading, Vietnamese Meaning, Type, Priority (1=Core, 2=Common, 3=Advanced)]
 */
module.exports = [
  // N2 Core Verbs & Action Concepts (1 & 2)
  ["扱う","あつかう","Thao tác, đối xử, thụ lý","Động từ",1],
  ["暴れる","あばれる","Quậy phá, nổi cơn thịnh nộ","Động từ",2],
  ["溢れる","あふれる","Tràn trề, ngập tràn (nước mắt/cảm xúc)","Động từ",1],
  ["甘やかす","あまやかす","Nuông chiều thái quá","Động từ",2],
  ["余る","あまる","Dư thừa, quá sức","Động từ",1],
  ["改める","あらためる","Sửa đổi, cải tiến, kiểm tra lại","Động từ",1],
  ["改まる","あらたまる","Được cải thiện, trang trọng hóa","Động từ",2],
  ["争う","あらそう","Tranh chấp, kiện tụng","Động từ",1],
  ["荒れる","あれる","Bão bùng, nứt nẻ (da), hoang tàn","Động từ",1],
  ["現れる","あらわれる","Hiện rõ ra","Động từ",1],
  ["現す","あらわす","Biểu lộ rõ ràng","Động từ",1],
  ["言い出す","いいだす","Mở lời, đề xuất đầu tiên","Động từ",1],
  ["言い付ける","いいつける","Mách lẻo, truyền lệnh","Động từ",2],
  ["怒る","いかる / おこる","Phẫn nộ, nổi trận lôi đình","Động từ",2],
  ["炒める","いためれる","Xào nấu thức ăn","Động từ",2],
  ["痛む","いたむ","Đau đớn, xót xa","Động từ",1],
  ["傷む","いたむ","Bị ôi thiu, hư hỏng vật chất","Động từ",2],
  ["威張る","いばる","Kiêu ngạo, hợm hĩnh","Động từ",2],
  ["嫌がる","いやがる","Tỏ thái độ ghét bỏ","Động từ",1],
  ["煎る","いる","Rang (cà phê/lạc)","Động từ",3],
  ["炒る","いる","Rang khô","Động từ",3],
  ["受け入れる","うけいれる","Tiếp nhận, dung nạp, đồng thuận","Động từ",1],
  ["受け持つ","うけもつ","Phụ trách, đảm nhiệm (lớp học/ca)","Động từ",1],
  ["受かる","うかる","Thi đỗ, trúng tuyển","Động từ",1],
  ["浮く","うく","Nổi bồng bềnh, dư ra (tiền), lạc lõng","Động từ",1],
  ["承る","うけたまわる","Tiếp nhận, nghe (khiêm nhường)","Động từ",1],
  ["打ち消す","うちけす","Phủ nhận, bác bỏ tin đồn","Động từ",1],
  ["撃つ","うつ","Bắn súng","Động từ",2],
  ["討つ","うつ","Tiêu diệt, thảo phạt","Động từ",3],
  ["映す","うつす","Chiếu bóng, phản chiếu hình ảnh","Động từ",1],
  ["映る","うつる","Được phản chiếu, lên hình","Động từ",1],
  ["埋まる","うまる","Bị lấp đầy, chôn vùi","Động từ",1],
  ["占う","うらなう","Bói toán vận mệnh","Động từ",2],
  ["裏返す","うらがえす","Lộn trái, lật ngược mặt sau","Động từ",1],
  ["裏切る","うらぎる","Phản bội, phụ lòng tin","Động từ",1],
  ["羨む","うらやむ","Ghen tị, đố kỵ","Động từ",2],
  ["売り切れる","うりきれる","Bán sạch nhẵn, cháy hàng","Động từ",1],
  ["追い出す","おいだす","Xua đuổi, trục xuất","Động từ",1],
  ["覆う","おおう","Trùm kín, bao bọc","Động từ",1],
  ["補う","おぎなう","Bù đắp thiếu hụt","Động từ",1],
  ["贈る","おくる","Trao tặng huân chương/quà","Động từ",1],
  ["怠る","おこたる","Lơ đễnh, chểnh mảng nhiệm vụ","Động từ",1],
  ["納める","おさめる","Nộp phí, hoàn tất giao dịch","Động từ",1],
  ["治める","おさめる","Thống trị, kiểm soát trị an","Động từ",1],
  ["収める","おさめる","Thu nạp, cất giữ, gặt hái thành công","Động từ",1],
  ["押し込む","おしこむ","Nhồi nhét vào trong","Động từ",2],
  ["押し寄せる","おしよせる","Ùn ùn kéo đến, dâng trào","Động từ",2],
  ["惜しむ","おしむ","Tiếc nuối, tiếc rẻ","Động từ",1],
  ["恐れる","おそれる","Kinh sợ, e ngại rủi ro","Động từ",1],
  ["脅かす","おびやかす","Đe dọa (hòa bình/tính mạng)","Động từ",1],
  ["驚かす","おどろかす","Làm ai đó giật mình hoảng hốt","Động từ",2],
  ["溺れる","おぼれる","Đuối nước, sa đọa","Động từ",2],
  ["思いがけない","おもいがけない","Không ngờ tới, bất thình lình","Tính từ -i",1],
  ["思い込む","おもいこむ","Đinh ninh, ngộ nhận","Động từ",1],
  ["思いやる","おもいやる","Cảm thông, chu đáo với người khác","Động từ",1],
  ["及ぶ","およぶ","Kéo dài tới, lan rộng đến","Động từ",1],
  ["及ぼす","およぼす","Gây ra ảnh hưởng/tác hại","Động từ",1],
  ["折れる","おれる","Nhượng bộ, bị bẻ gãy","Động từ",1],
  ["卸す","おろす","Bán buôn, bán sỉ","Động từ",2],
  ["恩恵","おんけい","Ơn huệ, lợi ích ban tặng","Danh từ",1],
  ["害する","がいする","Làm hại, gây tổn hại","Động từ",1],
  ["抱える","かかえる","Đối mặt với khủng hoảng, ôm nợ","Động từ",1],
  ["掲げる","かかげる","Treo cờ, nêu cao tôn chỉ mục tiêu","Động từ",1],
  ["限る","かぎる","Là nhất, chỉ giới hạn ở","Động từ",1],
  ["掻く","かく","Gãi (ngứa), toát (mồ hôi)","Động từ",1],
  ["嗅ぐ","かぐ","Ngửi mùi hương","Động từ",2],
  ["隠す","かくす","Che đậy sự thật","Động từ",1],
  ["隠れる","かくれる","Ẩn náu","Động từ",1],
  ["賭ける","かける","Đánh cược, mạo hiểm","Động từ",2],
  ["欠ける","かける","Thiếu sót, sứt mẻ","Động từ",1],
  ["重なる","かさなる","Trùng lặp thời gian, dồn dập","Động từ",1],
  ["重ねる","かさねる","Tích lũy nỗ lực","Động từ",1],
  ["偏る","かたよる","Mất cân bằng, phiến diện","Động từ",1],
  ["傾く","かたむく","Nghiêng ngả, suy thoái (kinh tế)","Động từ",1],
  ["傾ける","かたむける","Lắng nghe chăm chú, dốc hết tâm trí","Động từ",1],
  ["固まる","かたまる","Đông cứng lại, củng cố vững chắc","Động từ",1],
  ["固める","かためる","Củng cố (ý chí/đội hình)","Động từ",1],
  ["語る","かたる","Tâm sự, thuật lại chi tiết","Động từ",1],
  ["担ぐ","かつぐ","Gánh vác, mê tín dị đoan","Động từ",2],
  ["叶う","かなう","Ước mơ trở thành hiện thực","Động từ",1],
  ["叶える","かなえる","Hiện thực hóa ước mơ","Động từ",1],
  ["兼ねる","かねる","Kiêm chức, khó mà làm được","Động từ",1],
  ["被せる","かぶせる","Bao trùm lên, đổ trách nhiệm","Động từ",2],
  ["かじる","かじる","Gặm, học đòi bập bẹ","Động từ",2],
  ["稼ぐ","かせぐ","Kiếm tiền, câu giờ","Động từ",1],
  ["掠る","かする","Quẹt sượt qua","Động từ",3],
  ["偏見","へんけん","Thành kiến, định kiến hẹp hòi","Danh từ",1],
  ["構う","かまう","Bận tâm, can thiệp","Động từ",1],
  ["噛み合う","かみあう","Ăn khớp, khớp ý nhau","Động từ",2],
  ["噛む","かむ","Nhai, cắn","Động từ",1],
  ["通う","かよう","Thấu hiểu lòng nhau","Động từ",1],
  ["からかう","からかう","Trêu chọc, chọc ghẹo","Động từ",2],
  ["枯れる","かれる","Héo úa, tàn lụi","Động từ",1],
  ["乾かす","かわかす","Hong khô","Động từ",1],
  ["渇く","かわく","Khát nước, khao khát","Động từ",1],
  ["換算する","かんさんする","Quy đổi, hoán tính","Động từ",2],
  ["監視する","かんしする","Giám sát, theo dõi","Động từ",1],
  ["関わる","かかわる","Dính líu, liên lụy, ảnh hưởng đến","Động từ",1],
  ["鑑賞する","かんしょうする","Thưởng thức nghệ thuật","Động từ",1],
  ["干渉する","かんしょうする","Can thiệp, xía vào","Động từ",1],
  ["感情","かんじょう","Cảm xúc nội tâm","Danh từ",1],
  ["勘定する","かんじょうする","Tính toán hóa đơn, thanh toán","Động từ",1],
  ["歓迎する","かんげいする","Hoan nghênh, chào đón nồng nhiệt","Động từ",1],
  ["感激する","かんげきする","Cảm kích sâu sắc","Động từ",1],
  ["環境","かんきょう","Môi trường tự nhiên & xã hội","Danh từ",1],
  ["願望","がんぼう","Nguyện vọng tha thiết","Danh từ",2],
  ["議員","ぎいん","Nghị sĩ quốc hội","Danh từ",1],
  ["議会","ぎかい","Nghị viện, quốc hội","Danh từ",1],
  ["議論する","ぎろんする","Thảo luận, tranh biện","Động từ",1],
  ["義務","ぎむ","Nghĩa vụ bắt buộc","Danh từ",1],
  ["疑問","ぎもん","Nghi vấn, thắc mắc","Danh từ",1],
  ["逆転する","ぎゃくてんする","Xoay chuyển tình thế, lội ngược dòng","Động từ",1],
  ["給与","きゅうよ","Tiền lương, thù lao","Danh từ",1],
  ["供給する","きょうきゅうする","Cung cấp nguồn hàng/năng lượng","Động từ",1],
  ["強調する","きょうちょうする","Nhấn mạnh quan điểm","Động từ",1],
  ["強力","きょうりょく","Mạnh mẽ, uy lực lớn","Tính từ -na",1],
  ["局長","きょくちょう","Cục trưởng, trưởng chi nhánh","Danh từ",2],
  ["拒絶する","きょぜつする","Cự tuyệt, khước từ thẳng thừng","Động từ",1],
  ["許可する","きょかする","Cấp phép, chuẩn y","Động từ",1],
  ["距離","きょり","Khoảng cách địa lý & tâm lý","Danh từ",1],
  ["寄与する","きよする","Đóng góp, cống hiến cho","Động từ",1],
  ["金額","きんがく","Số tiền, kim ngạch","Danh từ",1],
  ["金融","きんゆう","Tài chính tiền tệ ngân hàng","Danh từ",1],
  ["緊張する","きんちょうする","Căng thẳng, hồi hộp","Động từ",1],
  ["勤務する","きんむする","Công tác, làm việc tại","Động từ",1],
  ["議論","ぎろん","Cuộc nghị luận, tranh luận","Danh từ",1],
  ["区別する","くべつする","Phân biệt đối tượng","Động từ",1],
  ["訓練する","くんれんする","Huấn luyện, rèn luyện bài bản","Động từ",1],
  ["景気","けいき","Tình hình kinh tế thị trường","Danh từ",1],
  ["警告する","けいこくする","Cảnh cáo, phát tín hiệu báo động","Động từ",1],
  ["傾向","けいこう","Khuynh hướng, xu hướng phát triển","Danh từ",1],
  ["契約する","けいやくする","Ký kết hợp đồng giao kèo","Động từ",1],
  ["経歴","けいれき","Lý lịch, quá trình làm việc","Danh từ",1],
  ["劇場","げきじょう","Nhà hát kịch nghệ","Danh từ",2],
  ["結論","けつろん","Kết luận chung cuộc","Danh từ",1],
  ["欠陥","けっかん","Khuyết tật, khiếm khuyết sản phẩm","Danh từ",1],
  ["血液","けつえき","Máu huyết","Danh từ",1],
  ["決意する","けついする","Quyết chí, hạ quyết tâm","Động từ",1],
  ["憲法","けんぽう","Hiến pháp quốc gia","Danh từ",1],
  ["権利","けんり","Quyền lợi hợp pháp","Danh từ",1],
  ["権力","けんりょく","Quyền lực chính trị","Danh từ",1],
  ["原理","げんり","Nguyên lý cơ bản","Danh từ",2],
  ["原料","げんりょう","Nguyên liệu thô chế biến","Danh từ",1],
  ["候補","こうほ","Ứng cử viên, đối tượng đề cử","Danh từ",1],
  ["効果","こうか","Hiệu quả mang lại","Danh từ",1],
  ["貢献する","こうけんする","Cống hiến to lớn","Động từ",1],
  ["公害","こうがい","Ô nhiễm môi trường công cộng","Danh từ",1],
  ["高度","こうど","Độ cao, trình độ tiên tiến cao độ","Tính từ -na",1],
  ["交渉する","こうしょうする","Đàm phán thương lượng","Động từ",1],
  ["公正","こうせい","Công bằng, liêm chính","Tính từ -na",1],
  ["構成する","こうせいする","Cấu thành, tổ chức thành","Động từ",1],
  ["構造","こうぞう","Cấu trúc, cơ cấu hệ thống","Danh từ",1],
  ["克服する","こくふくする","Khắc phục gian nan thử thách","Động từ",1],
  ["国民","こくみん","Quốc dân, công dân một nước","Danh từ",1],
  ["雇用する","こようする","Tuyển dụng, thuê mướn lao động","Động từ",1],
  ["根拠","こんきょ","Căn cứ, cơ sở xác thực","Danh từ",1],
  ["混乱する","こんらんする","Hỗn loạn, rối ren","Động từ",1],
  ["際限","さいげん","Giới hạn tận cùng","Danh từ",2],
  ["裁判","さいばん","Sự xét xử tại tòa án","Danh từ",1],
  ["財政","ざいせい","Tài chính công, ngân sách","Danh từ",1],
  ["作成する","さくせいする","Biên soạn, tạo lập hồ sơ","Động từ",1],
  ["削減する","さくげんする","Cắt giảm nhân sự/ngân sách","Động từ",1],
  ["作者","さくしゃ","Tác giả sáng tác","Danh từ",1],
  ["差別する","さべつする","Kỳ thị, phân biệt đối xử","Động từ",1],
  ["指示する","しじする","Chỉ thị, ra lệnh điều hành","Động từ",1],
  ["支持する","しじする","Ủng hộ, tán thành chủ trương","Động từ",1],
  ["市場","しじょう / いちば","Thị trường kinh tế","Danh từ",1],
  ["姿勢","しせい","Tư thế đứng ngồi, thái độ nhìn nhận","Danh từ",1],
  ["自然","しぜん","Tự nhiên, thiên nhiên","Danh từ",1],
  ["持続する","じぞくする","Duy trì bền vững liên tục","Động từ",1],
  ["実態","じったい","Thực trạng tình hình","Danh từ",1],
  ["実行する","じっこうする","Thực thi kế hoạch","Động từ",1],
  ["指導する","しどうする","Chỉ đạo, dẫn dắt huấn luyện","Động từ",1],
  ["支配する","しはいする","Thống trị, chi phối","Động từ",1],
  ["資本","しほん","Vốn liếng, tư bản đầu tư","Danh từ",1],
  ["視野","しや","Tầm nhìn mắt, tầm hiểu biết","Danh từ",1],
  ["修正する","しゅうせいする","Chỉnh sửa, tu chính","Động từ",1],
  ["就職する","しゅうしょくする","Tìm được việc làm, vào công ty","Động từ",1],
  ["重要","じゅうよう","Trọng yếu, vô cùng quan trọng","Tính từ -na",1],
  ["縮小する","しゅくしょうする","Thu nhỏ quy mô","Động từ",1],
  ["主張する","しゅちょうする","Khẳng định lập trường, chủ trương","Động từ",1],
  ["承認する","しょうにんする","Thừa nhận, phê duyệt chấp thuận","Động từ",1],
  ["消費する","しょうひする","Tiêu dùng, tiêu thụ hàng hóa","Động từ",1],
  ["衝突する","しょうとつする","Va chạm giao thông, xung đột ý kiến","Động từ",1],
  ["焦点","しょうてん","Tiêu điểm chú ý","Danh từ",1],
  ["職務","しょくむ","Chức vụ, chức trách công việc","Danh từ",1],
  ["侵害する","しんがいする","Xâm hại chủ quyền/bản quyền","Động từ",1],
  ["信仰","しんこう","Tín ngưỡng tôn giáo","Danh từ",2],
  ["深刻","しんこく","Nghiêm trọng, trầm trọng","Tính từ -na",1],
  ["審査する","しんさする","Thẩm tra, xét duyệt hồ sơ","Động từ",1],
  ["進出する","しんしゅつする","Tiến ra thị trường quốc tế","Động từ",1],
  ["慎重","しんちょう","Thận trọng, cẩn mật","Tính từ -na",1],
  ["信頼する","しんらいする","Tín nhiệm, tin cậy tuyệt đối","Động từ",1],
  ["推測する","すいそくする","Suy đoán dựa trên dữ liệu","Động từ",1],
  ["推進する","すいしんする","Đẩy mạnh xúc tiến dự án","Động từ",1],
  ["制度","せいど","Chế độ, thể chế quy định","Danh từ",1],
  ["製造する","せいぞうする","Chế tạo sản xuất công nghiệp","Động từ",1],
  ["生命","せいめい","Tính mạng, sự sống","Danh từ",1],
  ["責任","せきにん","Trách nhiệm gánh vác","Danh từ",1],
  ["積極的","せっきょくてき","Tích cực, chủ động","Tính từ -na",1],
  ["宣伝する","せんでんする","Tuyên truyền, quảng cáo rầm rộ","Động từ",1],
  ["総合","そうごう","Tổng hợp, toàn diện","Danh từ",1],
  ["操作する","そうさする","Thao tác điều khiển máy móc","Động từ",1],
  ["促進する","そくしんする","Thúc đẩy phát triển nhanh","Động từ",1],
  ["組織","そしき","Tổ chức, bộ máy cơ quan","Danh từ",1],
  ["損失","そんしつ","Tổn thất tài chính thiệt hại","Danh từ",1],
  ["尊重する","そんちょうする","Tôn trọng ý kiến người khác","Động từ",1],
  ["対策","たいさく","Biện pháp đối phó, đối sách","Danh từ",1],
  ["対象","たいしょう","Đối tượng hướng đến","Danh từ",1],
  ["代表する","だいひょうする","Đại diện cho tập thể","Động từ",1],
  ["妥協する","だきょうする","Thỏa hiệp nhượng bộ","Động từ",1],
  ["蓄積する","ちくせきする","Tích lũy vốn/tri thức","Động từ",1],
  ["著作権","ちょさくけん","Bản quyền tác giả","Danh từ",1],
  ["調整する","ちょうせいする","Điều chỉnh lịch trình/cơ cấu","Động từ",1],
  ["調査する","ちょうさする","Điều tra khảo sát số liệu","Động từ",1],
  ["展示する","てんじする","Trưng bày hiện vật","Động từ",1],
  ["統合する","とうごうする","Hợp nhất, tích hợp hệ thống","Động từ",1],
  ["投資する","とうしする","Đầu tư vốn sinh lời","Động từ",1],
  ["討論する","とうろんする","Thảo luận tranh luận đề tài","Động từ",1],
  ["独占する","どくせんする","Độc quyền thị trường","Động từ",1],
  ["背景","はいけい","Bối cảnh lịch sử, nguyên nhân sâu xa","Danh từ",1],
  ["配布する","はいふする","Phát tài liệu ấn phẩm","Động từ",1],
  ["破産する","はさんする","Vỡ nợ, phá sản doanh nghiệp","Động từ",1],
  ["把握する","はあくする","Nắm bắt tường tận tình hình","Động từ",1],
  ["批判する","ひはんする","Phê phán chỉ trích","Động từ",1],
  ["表明する","ひょうめいする","Bày tỏ tuyên bố công khai","Động từ",1],
  ["評価する","ひょうかする","Đánh giá giá trị/năng lực","Động từ",1],
  ["普及する","ふきゅうする","Phổ biến rộng rãi trong dân chúng","Động từ",1],
  ["復興する","ふっこうする","Phục hưng tái thiết sau thiên tai","Động từ",1],
  ["負担する","ふたんする","Gánh vác chi phí trách nhiệm","Động từ",1],
  ["崩壊する","ほうかいする","Sụp đổ hoàn toàn","Động từ",1],
  ["防止する","ぼうしする","Phòng chống ngăn ngừa sự cố","Động từ",1],
  ["摩擦","まさつ","Ma sát vật lý, xích mích ngoại giao","Danh từ",1],
  ["矛盾する","むじゅんする","Mâu thuẫn trái ngược nhau","Động từ",1],
  ["優秀","ゆうしゅう","Ưu tú, tài năng xuất chúng","Tính từ -na",1],
  ["優先する","ゆうせんする","Ưu tiên hàng đầu","Động từ",1],
  ["有利","ゆうり","Có lợi thế hơn","Tính từ -na",1],
  ["世論","よろん / せいろん","Dư luận xã hội","Danh từ",1],
  ["利益","りえき","Lợi nhuận kinh doanh, ích lợi","Danh từ",1],
  ["連携する","れんけいする","Liên kết phối hợp tác chiến","Động từ",1]
];
