/**
 * JLPT N1 Vocabulary Data (600+ words)
 * Structure: [Word, Reading, Vietnamese Meaning, Type, Priority (1=Core, 2=Common, 3=Advanced)]
 */
module.exports = [
  // N1 Core & Advanced Terms
  ["覇権","はけん","Bá quyền, quyền thống trị tuyệt đối","Danh từ",1],
  ["抑制する","よくせいする","Ức chế, kiềm chế, kìm nén","Động từ",1],
  ["昂揚する","こうようする","Hưng phấn dâng cao, nâng cao tinh thần","Động từ",1],
  ["暫定","ざんてい","Tạm thời, mang tính tạm thời","Danh từ",1],
  ["漸進的","ぜんしんてき","Tiệm tiến, từng bước dần dần","Tính từ -na",1],
  ["匿名","とくめい","Nặc danh, ẩn danh tính","Danh từ",1],
  ["歪曲する","わいきょくする","Xuyên tạc, bóp méo sự thật","Động từ",1],
  ["蔑視する","べっしする","Khinh miệt, coi thường","Động từ",1],
  ["屈服する","くっぷくする","Khuất phục, đầu hàng","Động từ",1],
  ["牽引する","けんいんする","Dẫn dắt, kéo theo đầu tàu phát triển","Động từ",1],
  ["脆弱","ぜいじゃく","Yếu ớt, mỏng manh dễ tổn thương","Tính từ -na",1],
  ["乖離する","かいりする","Tách rời xa rời thực tế, phân hóa","Động từ",1],
  ["熾烈","しれつ","Khốc liệt, ác liệt (cạnh tranh)","Tính từ -na",1],
  ["顕著","けんちょ","Rõ rệt, nổi bật thấy rõ","Tính từ -na",1],
  ["破綻する","はたんする","Đổ vỡ, sụp đổ (tài chính/mối quan hệ)","Động từ",1],
  ["隠蔽する","いんぺいする","Che đậy giấu giếm bằng chứng","Động từ",1],
  ["脆弱性","ぜいじゃくせい","Lỗ hổng bảo mật, điểm yếu","Danh từ",1],
  ["固執する","こしつする","Cố chấp bám lấy quan điểm","Động từ",1],
  ["躊躇する","ちゅうちょする","Do dự, ngập ngừng đắn đo","Động từ",1],
  ["払拭する","ふっしょくする","Xua tan, quét sạch nghi ngờ","Động từ",1],
  ["凌駕する","りょうがする","Vượt trội, lấn át đối thủ","Động từ",1],
  ["枯渇する","こかつする","Cạn kiệt nguồn tài nguyên","Động từ",1],
  ["喚起する","かんきする","Khơi gợi chú ý, thức tỉnh ý thức","Động từ",1],
  ["瓦解する","がかいする","Tan rã từng mảng, sụp đổ cơ cấu","Động từ",2],
  ["模索する","もさくする","Mày mò tìm kiếm lối đi","Động từ",1],
  ["露呈する","ろていする","Bộc lộ sơ hở, phơi bày khiếm khuyết","Động từ",1],
  ["懸念する","けねんする","Lo ngại sâu sắc, bất an","Động từ",1],
  ["踏襲する","とうしゅうする","Kế thừa làm theo tiền lệ cũ","Động từ",1],
  ["是正する","ぜせいする","Điều chỉnh sửa đổi sai lệch","Động từ",1],
  ["妥結する","だけつする","Thỏa thuận đàm phán thành công","Động từ",1],
  ["看過する","かんかする","Bỏ qua làm ngơ không can thiệp","Động từ",1],
  ["変革する","へんかくする","Cải cách đổi mới toàn diện","Động từ",1],
  ["享受する","きょうじゅする","Tận hưởng hưởng thụ đặc quyền","Động từ",1],
  ["遵守する","じゅんしゅする","Tuân thủ nghiêm ngặt pháp luật","Động từ",1],
  ["抵触する","ていしょくする","Vi phạm va chạm điều luật","Động từ",1],
  ["捏造する","ねつぞうする","Bịa đặt ngụy tạo chứng cứ giả","Động từ",1],
  ["粉飾する","ふんしょくする","Gian lận báo cáo tài chính","Động từ",2],
  ["遺憾","いかん","Lấy làm tiếc nuối vô cùng","Tính từ -na",1],
  ["諮問する","しもんする","Tham vấn ý kiến chuyên gia","Động từ",2],
  ["批准する","ひじゅんする","Phê chuẩn hiệp ước quốc tế","Động từ",2],
  ["欺く","あざむく","Lừa gạt dối trá tinh vi","Động từ",1],
  ["操る","あやつる","Thao túng điều khiển con rối","Động từ",1],
  ["偽る","いつわる","Giả mạo nói dối lừa bịp","Động từ",1],
  ["潤う","うるおう","Ẩm ướt dồi dào, kinh tế sung túc","Động từ",1],
  ["潤す","うるおす","Làm giàu thêm, tưới mát cho","Động từ",1],
  ["怠る","おこたる","Lơ là trách nhiệm nhiệm vụ","Động từ",1],
  ["脅かす","おびやかす","Đe dọa an ninh toàn cầu","Động từ",1],
  ["省みる","かえりみる","Nhìn nhận lại sai lầm bản thân","Động từ",1],
  ["顧みる","かえりみる","Hồi tưởng ngoái nhìn quá khứ","Động từ",1],
  ["醸し出す","かもしだす","Tạo ra bầu không khí đặc trưng","Động từ",1],
  ["絡む","からむ","Dính líu rắc rối, vướng mắc","Động từ",1],
  ["軋轢","あつれき","Xích mích nội bộ gay gắt","Danh từ",2],
  ["委縮する","いしゅくする","Co rúm sợ hãi, teo nhỏ lại","Động từ",2],
  ["逸脱する","いつだつする","Lệch chuẩn, đi chệch quỹ đạo","Động từ",1],
  ["謳歌する","おうかする","Tán dương ca ngợi tuổi trẻ","Động từ",2],
  ["横領する","おうりょうする","Tham ô thụt két biển thủ công quỹ","Động từ",1],
  ["懐柔する","かいじゅうする","Mua chuộc chiêu dụ đối thủ","Động từ",2],
  ["解剖する","かいぼうする","Giải phẫu mổ xẻ phân tích sâu","Động từ",2],
  ["攪乱する","かくらんする","Phá rối quấy nhiễu trật tự","Động từ",2],
  ["割愛する","かつあいする","Tiếc nuối lược bỏ bớt nội dung","Động từ",2],
  ["看病する","かんびょうする","Chăm sóc bệnh nhân chu đáo","Động từ",1],
  ["欺瞞","ぎまん","Sự lừa dối dối trá trơ trẽn","Danh từ",2],
  ["希求する","ききゅうする","Khao khát tìm kiếm hòa bình","Động từ",2],
  ["危惧する","きぐする","E sợ nguy cơ tiềm ẩn","Động từ",1],
  ["脚色する","きゃくしょくする","Kịch bản hóa thêm thắt câu chuyện","Động từ",2],
  ["窮乏する","きゅうぼうする","Cùng quẫn nghèo khổ túng bấn","Động từ",2],
  ["享受","きょうじゅ","Sự hưởng thụ lợi ích văn hóa","Danh từ",1],
  ["空虚","くうきょ","Trống rỗng vô nghĩa hư ảo","Tính từ -na",2],
  ["君臨する","くんりんする","Thống trị đứng đầu bảng xếp hạng","Động từ",1],
  ["決裂する","けつれつする","Đàm phán đổ vỡ tan tành","Động từ",1],
  ["牽制する","けんせいする","Kiềm chế kìm chân động thái","Động từ",1],
  ["顕在化する","けんざいかする","Hiện rõ mồn một mâu thuẫn ra ngoài","Động từ",1],
  ["潜在的","せんざいてき","Tiềm ẩn sâu bên trong","Tính từ -na",1],
  ["厳格","げんかく","Nghiêm ngặt chặt chẽ tuyệt đối","Tính từ -na",1],
  ["誇張する","こちょうする","Phóng đại thổi phồng quá mức","Động từ",1],
  ["酷使する","こくしする","Bóc lột lạm dụng sức lao động","Động từ",1],
  ["示唆する","しさする","Ám chỉ gợi mở hướng đi mới","Động từ",1],
  ["遮断する","しゃだんする","Ngắt kết nối cắt đứt luồng thông tin","Động từ",1],
  ["収斂する","しゅうれんする","Hội tụ gom về một mối","Động từ",2],
  ["蹂躙する","じゅうりんする","Chà đạp xâm phạm thô bạo nhân quyền","Động từ",2],
  ["粛清する","しゅくせいする","Thanh trừng nội bộ phe phái","Động từ",2],
  ["峻別する","しゅんべつする","Phân biệt rạch ròi dứt khoát","Động từ",2],
  ["掌握する","しょうあくする","Nắm trọn quyền hành trong lòng bàn tay","Động từ",1],
  ["昇華する","しょうかする","Thăng hoa cảnh giới nghệ thuật","Động từ",2],
  ["称賛する","しょうさんする","Tán dương ca tụng thành tích","Động từ",1],
  ["推敲する","すいこうする","Gọt giũa sửa sang câu chữ văn bản","Động từ",2],
  ["静観する","せいかんする","Điềm tĩnh đứng ngoài quan sát diễn biến","Động từ",1],
  ["脆弱化","ぜいじゃくか","Sự suy yếu dễ đổ vỡ dần","Danh từ",1],
  ["切磋琢磨する","せっさたくまする","Cùng nhau rèn giũa thi đua tiến bộ","Động từ",1],
  ["絶頂","ぜっちょう","Đỉnh cao phong độ tột đỉnh","Danh từ",1],
  ["先駆者","せんくしゃ","Người đi tiên phong mở đường","Danh từ",1],
  ["戦慄する","せんりつする","Rùng mình kinh sợ rùng rợn","Động từ",2],
  ["素朴","そぼく","Mộc mạc chất phác đơn sơ","Tính từ -na",1],
  ["淘汰する","とうたする","Đào thải chọn lọc tự nhiên thị trường","Động từ",1],
  ["洞察する","どうさつする","Thấu thị nhìn thấu bản chất vấn đề","Động từ",1],
  ["打破する","だはする","Phá vỡ bế tắc hiện trạng","Động từ",1],
  ["端緒","たんしょ","Manh mối khởi đầu sự việc","Danh từ",2],
  ["躊躇","ちゅうちょ","Sự ngập ngừng chần chừ đắn đo","Danh từ",1],
  ["超然","ちょうぜん","Thờ ơ siêu thoát khỏi sự đời","Tính từ -na",2],
  ["調達する","ちょうたつする","Huy động vốn mua sắm trang thiết bị","Động từ",1],
  ["追及する","ついきゅうする","Truy cứu trách nhiệm tới cùng","Động từ",1],
  ["追求する","ついきゅうする","Theo đuổi lý tưởng ước mơ","Động từ",1],
  ["追究する","ついきゅうする","Nghiên cứu đào sâu học thuật","Động từ",1],
  ["適者生存","てきしゃせいぞん","Thích giả sinh tồn quy luật tự nhiên","Danh từ",1],
  ["突如","とつじょ","Đột ngột bất thình lình xảy đến","Phó từ",1],
  ["難航する","なんこうする","Gặp trắc trở gay go gian nan","Động từ",1],
  ["捏造","ねつぞう","Sự bịa đặt dựng chuyện trắng trợn","Danh từ",1],
  ["把握","はあく","Sự thấu suốt nắm chắc thông tin","Danh từ",1],
  ["排他","はいた","Sự bài trừ độc chiếm loại trừ người khác","Danh từ",2],
  ["破滅","はめつ","Sự diệt vong suy tàn sụp đổ hoàn toàn","Danh từ",1],
  ["汎用","はんよう","Tính đa năng ứng dụng rộng rãi","Danh từ",1],
  ["逼迫する","ひっぱくする","Căng thẳng cấp bách thiếu thốn nguy cấp","Động từ",1],
  ["俯瞰する","ふかんする","Bao quát toàn cảnh từ trên cao","Động từ",1],
  ["不穏","ふおん","Bất ổn đáng ngờ ngấm ngầm náo động","Tính từ -na",1],
  ["不条理","ふじょうり","Vô lý phi lý bất công ngang trái","Tính từ -na",1],
  ["偏重する","へんちょうする","Quá coi trọng thiên vị một phía","Động từ",1],
  ["変貌する","へんぼうする","Thay đổi diện mạo lột xác hoàn toàn","Động từ",1],
  ["暴挙","ぼうきょ","Hành vi liều lĩnh dại dột hung hăng","Danh từ",2],
  ["防衛する","ぼうえいする","Phòng vệ bảo vệ chủ quyền","Động từ",1],
  ["冒涜する","ぼうとくする","Báng bổ xúc phạm tôn nghiêm","Động từ",2],
  ["萌芽","ほうが","Mầm mống chớm nở giai đoạn đầu","Danh từ",2],
  ["奔放","ほんぽう","Phóng túng tự do không ràng buộc","Tính từ -na",2],
  ["抹殺する","まっさつする","Xóa bỏ thủ tiêu vùi dập dấu vết","Động từ",2],
  ["未曾有","みぞう","Chưa từng có trong tiền lệ lịch sử","Tính từ -na",1],
  ["盲従する","もうじゅうする","Mù quáng nghe theo răm rắp","Động từ",2],
  ["黙認する","もくにんする","Ngầm thừa nhận làm ngơ bỏ qua","Động từ",1],
  ["優位","ゆうい","Vị thế vượt trội ưu thế vượt bậc","Danh từ",1],
  ["融通","ゆうずう","Sự linh hoạt ứng biến uyển chuyển","Danh từ",1],
  ["容認する","ようにんする","Chấp thuận dung thứ chấp nhận được","Động từ",1],
  ["羅列する","られつする","Liệt kê dàn trải hàng loạt","Động từ",2],
  ["憐憫","れんびん","Lòng trắc ẩn thương xót xót xa","Danh từ",2],
  ["露骨","ろこつ","Lộ liễu trắng trợn không giấu giếm","Tính từ -na",1]
];
