/**
 * JLPT N4 Vocabulary Data (700+ words)
 * Structure: [Word, Reading, Vietnamese Meaning, Type, Priority (1=Core, 2=Common, 3=Advanced)]
 */
module.exports = [
  // Verbs - N4 Core & Common
  ["案内する","あんないする","Hướng dẫn, dẫn đường","Động từ",1],
  ["運転する","うんてんする","Lái xe","Động từ",1],
  ["遠慮する","えんりょする","Khách khí, ngại ngần","Động từ",1],
  ["遅れる","おくれる","Muộn, trễ giờ","Động từ",1],
  ["起こす","おこす","Đánh thức (ai dậy)","Động từ",1],
  ["行う","おこなう","Tổ chức, tiến hành","Động tự",1],
  ["怒る","おこる","Tức giận, nổi giận","Động từ",1],
  ["落ちる","おちる","Rơi, rớt","Động từ",1],
  ["落とす","おとす","Làm rơi, đánh rơi","Động từ",1],
  ["お目にかかる","おめにかかる","Gặp gỡ (khiêm nhường)","Động từ",2],
  ["思い出す","おもいだす","Nhớ lại, hồi tưởng","Động từ",1],
  ["思う","おもう","Nghĩ, cho rằng","Động từ",1],
  ["折る","おる","Bẻ gãy, gấp lại","Động từ",2],
  ["折れる","おれる","Bị gãy","Động từ",2],
  ["通う","かよう","Đi lại đều đặn (học, làm)","Động từ",1],
  ["乾く","かわく","Khô ráo","Động từ",2],
  ["代わる","かわる","Thay thế, đổi","Động từ",1],
  ["決まる","きまる","Được quyết định","Động từ",1],
  ["決める","きめる","Quyết định","Động từ",1],
  ["比べる","くらべる","So sánh","Động từ",1],
  ["暮らす","くらす","Sinh sống","Động từ",2],
  ["経験する","けいけんする","Trải nghiệm, có kinh nghiệm","Động từ",1],
  ["故障する","こしょうする","Bị hỏng hóc","Động từ",1],
  ["込む","こむ","Đông đúc, chen chúc","Động từ",1],
  ["壊す","こわす","Làm hỏng","Động từ",1],
  ["壊れる","こわれる","Bị hỏng","Động từ",1],
  ["下がる","さがる","Hạ xuống, giảm","Động từ",1],
  ["下げる","さげる","Hạ thấp xuống, giảm","Động từ",1],
  ["探す","さがす","Tìm kiếm (vật muốn có)","Động từ",1],
  ["捜す","さがす","Tìm kiếm (vật bị mất)","Động từ",2],
  ["差し上げる","さしあげる","Tặng, biếu (khiêm nhường)","Động từ",2],
  ["触る","さわる","Chạm vào, sờ","Động từ",1],
  ["叱る","しかる","La mắng, rầy la","Động từ",2],
  ["知らせる","しらせる","Thông báo, cho biết","Động từ",1],
  ["調べる","しらべる","Điều tra, tra cứu","Động từ",1],
  ["過ぎる","すぎる","Quá, vượt quá","Động từ",1],
  ["進む","すすむ","Tiến bộ, tiến lên","Động từ",1],
  ["捨てる","すてる","Vứt bỏ, ném đi","Động từ",1],
  ["滑る","すべる","Trượt chân, trơn trượt","Động từ",2],
  ["育てる","そだてる","Nuôi nấng, chăm sóc","Động từ",1],
  ["育つ","そだつ","Lớn lên, phát triển","Động từ",1],
  ["倒れる","たおれる","Ngã gục, đổ sập","Động từ",1],
  ["倒す","たおす","Đánh đổ, quật ngã","Động từ",2],
  ["確かめる","たしかめる","Xác nhận, kiểm tra lại","Động từ",1],
  ["助ける","たすける","Cứu giúp, giúp đỡ","Động từ",1],
  ["助かる","たすかる","Được cứu, may mắn","Động từ",1],
  ["足す","たす","Thêm vào, cộng vào","Động từ",2],
  ["訪ねる","たずねる","Ghé thăm","Động từ",2],
  ["尋ねる","たずねる","Hỏi thăm, tra hỏi","Động từ",2],
  ["建てる","たてる","Xây dựng (nhà cửa)","Động từ",1],
  ["足りる","たりる","Đủ, đầy đủ","Động từ",1],
  ["捕まえる","つかまえる","Bắt giữ, tóm lấy","Động từ",2],
  ["捕まる","つかまる","Bị bắt","Động từ",2],
  ["付く","つく","Dính vào, đính kèm","Động từ",1],
  ["付ける","つける","Dán vào, bật lên","Động từ",1],
  ["伝える","つたえる","Truyền đạt, nhắn lại","Động từ",1],
  ["続く","つづく","Tiếp diễn, kéo dài","Động từ",1],
  ["続ける","つづける","Tiếp tục làm gì","Động từ",1],
  ["包む","つつむ","Bọc lại, gói lại","Động từ",2],
  ["勤める","つとめる","Làm việc tại (công ty)","Động từ",1],
  ["連れて行く","つれていく","Dẫn đi cùng","Động từ",1],
  ["連れて来る","つれてくる","Dẫn đến cùng","Động từ",1],
  ["手伝う","てつだう","Phụ giúp","Động từ",1],
  ["通る","とおる","Đi qua, thông qua","Động từ",1],
  ["届く","とどく","Được chuyển đến tận nơi","Động từ",1],
  ["届ける","とどける","Đưa đến, chuyển phát","Động từ",1],
  ["泊まる","とまる","Nghỉ trọ qua đêm","Động từ",1],
  ["泊める","とめる","Cho ở nhờ qua đêm","Động từ",2],
  ["取り替える","とりかえる","Đổi lại, thay thế","Động từ",2],
  ["直す","なおす","Sửa chữa, chỉnh sửa","Động từ",1],
  ["直る","なおる","Được sửa xong","Động từ",1],
  ["治る","なおる","Khỏi ốm, lành bệnh","Động từ",1],
  ["亡くなる","なくなる","Mất, qua đời","Động từ",1],
  ["投げる","なげる","Ném đi","Động từ",1],
  ["慣れる","なれる","Làm quen, quen với","Động từ",1],
  ["逃げる","にげる","Chạy trốn, tẩu thoát","Động từ",1],
  ["似合う","にあう","Phù hợp, vừa vặn","Động từ",1],
  ["残る","のこる","Còn lại, sót lại","Động từ",1],
  ["残す","のこす","Để lại, chừa lại","Động từ",1],
  ["乗り換える","のりかえる","Đổi tàu, chuyển tuyến","Động từ",1],
  ["運ぶ","はこぶ","Vận chuyển, mang vác","Động từ",1],
  ["始まる","はじまる","Bắt đầu (tự)","Động từ",1],
  ["始める","はじめる","Bắt đầu (tha)","Động từ",1],
  ["払う","はらう","Chi trả tiền","Động từ",1],
  ["冷える","ひえる","Lạnh đi","Động từ",2],
  ["冷やす","ひやす","Làm lạnh, ướp lạnh","Động từ",2],
  ["光る","ひかる","Phát sáng, lấp lánh","Động từ",2],
  ["引き出す","ひきだす","Rút tiền, kéo ra","Động từ",1],
  ["引っ越す","ひっこす","Chuyển nhà","Động từ",1],
  ["開く","ひらく","Mở (sách, hội nghị)","Động từ",1],
  ["拾う","ひろう","Nhặt lên, lượm","Động từ",1],
  ["増える","ふえる","Gia tăng (số lượng)","Động từ",1],
  ["増やす","ふやす","Làm tăng lên","Động từ",1],
  ["減る","へる","Giảm đi","Động từ",1],
  ["減らす","へらす","Làm giảm bớt","Động từ",1],
  ["褒める","ほめる","Khen ngợi","Động từ",1],
  ["見つかる","みつかる","Được tìm thấy","Động từ",1],
  ["見つける","みつける","Tìm kiếm ra","Động từ",1],
  ["迎える","むかえる","Đón rước, nghênh đón","Động từ",1],
  ["戻る","もどる","Quay trở lại","Động từ",1],
  ["戻す","もどす","Để lại chỗ cũ, trả về","Động từ",1],
  ["役に立つ","やくにたつ","Có ích, hữu dụng","Động từ",1],
  ["辞める","やめる","Từ bỏ, nghỉ việc","Động từ",1],
  ["汚れる","よごれる","Bị vấy bẩn","Động từ",1],
  ["汚す","よごす","Làm bẩn","Động từ",1],
  ["喜ぶ","よろこぶ","Vui sướng, hân hoan","Động từ",1],
  ["割る","わる","Làm vỡ, chia nhỏ","Động từ",1],
  ["割れる","われる","Bị vỡ, bể","Động từ",1],

  // Nouns - Daily Life & Society (1 & 2)
  ["挨拶","あいさつ","Chào hỏi, lời chào","Danh từ",1],
  ["間","あいだ","Khoảng giữa, trong lúc","Danh từ",1],
  ["相手","あいて","Đối phương, bạn đối thoại","Danh từ",1],
  ["赤ちゃん","あかちゃん","Em bé sơ sinh","Danh từ",1],
  ["味","あじ","Hương vị, mùi vị","Danh từ",1],
  ["案内","あんない","Sự hướng dẫn","Danh từ",1],
  ["意見","いけん","Ý kiến, quan điểm","Danh từ",1],
  ["石","いし","Hòn đá","Danh từ",2],
  ["糸","いと","Sợi chỉ, sợi tơ","Danh từ",2],
  ["以内","いない","Trong vòng, không quá","Danh từ",1],
  ["田舎","いなか","Vùng quê, nông thôn","Danh từ",1],
  ["命","いのち","Sinh mệnh, tính mạng","Danh từ",1],
  ["意味","いみ","Ý nghĩa","Danh từ",1],
  ["お祝い","おいわい","Chúc mừng, quà mừng","Danh từ",1],
  ["贈り物","おくりもの","Món quà tặng","Danh từ",1],
  ["お礼","おれい","Cảm ơn, quà cảm ơn","Danh từ",1],
  ["原因","げんいん","Nguyên nhân","Danh từ",1],
  ["結果","けっか","Kết quả","Danh từ",1],
  ["経験","けいけん","Kinh nghiệm","Danh từ",1],
  ["景色","けしき","Phong cảnh","Danh từ",1],
  ["計画","けいかく","Kế hoạch","Danh từ",1],
  ["経済","けいざい","Kinh tế","Danh từ",1],
  ["警察","けいさつ","Cảnh sát","Danh từ",1],
  ["怪我","けが","Vết thương, chấn thương","Danh từ",1],
  ["研究","けんきゅう","Nghiên cứu","Danh từ",1],
  ["故障","こしょう","Sự cố, hỏng hóc","Danh từ",1],
  ["ごみ","ごみ","Rác rưởi","Danh từ",1],
  ["産業","さんぎょう","Ngành công nghiệp","Danh từ",2],
  ["事故","じこ","Tai nạn, sự cố","Danh từ",1],
  ["地震","じしん","Trận động đất","Danh từ",1],
  ["時代","じだい","Thời đại, thời kỳ","Danh từ",1],
  ["失敗","しっぱい","Sự thất bại","Danh từ",1],
  ["質問","しつもん","Câu hỏi","Danh từ",1],
  ["品物","しなもの","Hàng hóa, vật phẩm","Danh từ",1],
  ["社会","しゃかい","Xã hội","Danh từ",1],
  ["習慣","しゅうかん","Tập quán, thói quen","Danh từ",1],
  ["住所","じゅうしょ","Địa chỉ nhà","Danh từ",1],
  ["趣味","しゅみ","Sở thích","Danh từ",1],
  ["準備","じゅんび","Sự chuẩn bị","Danh từ",1],
  ["将来","しょうらい","Tương lai","Danh từ",1],
  ["食事","しょくじ","Bữa ăn","Danh từ",1],
  ["食料品","しょくりょうひん","Thực phẩm, đồ ăn","Danh từ",2],
  ["女性","じょせい","Nữ giới, phụ nữ","Danh từ",1],
  ["男性","だんせい","Nam giới, đàn ông","Danh từ",1],
  ["人口","じんこう","Dân số","Danh từ",1],
  ["神社","じんじゃ","Đền thần đạo Shinto","Danh từ",1],
  ["世界","せかい","Thế giới","Danh từ",1],
  ["席","せき","Chỗ ngồi, ghế ngồi","Danh từ",1],
  ["説明","せつめい","Sự giải thích, hướng dẫn","Danh từ",1],
  ["世話","せわ","Sự chăm sóc, giúp đỡ","Danh từ",1],
  ["専門","せんもん","Chuyên môn, chuyên ngành","Danh từ",1],
  ["相談","そうだん","Bàn bạc, thảo luận","Danh từ",1],
  ["卒業","そつぎょう","Tốt nghiệp","Danh từ",1],
  ["台風","たいふう","Cơn bão nhiệt đới","Danh từ",1],
  ["都合","つごう","Điều kiện, sự thuận tiện","Danh từ",1],
  ["手袋","てぶくろ","Găng tay, bao tay","Danh từ",2],
  ["展覧会","てんらんかい","Triển lãm, hội chợ triển lãm","Danh từ",2],
  ["道具","どうぐ","Dụng cụ, công cụ","Danh từ",1],
  ["動物","どうぶつ","Động vật, muông thú","Danh từ",1],
  ["特別","とくべつ","Đặc biệt","Tính từ -na",1],
  ["入学","にゅうがく","Nhập học","Danh từ",1],
  ["入院","にゅういん","Nhập viện","Danh từ",1],
  ["退院","たいいん","Xuất viện","Danh từ",1],
  ["番組","ばんぐみ","Chương trình (truyền hình)","Danh từ",1],
  ["反対","はんたい","Phản đối, đối diện","Danh từ",1],
  ["被害","ひがい","Thiệt hại, tổn thất","Danh từ",2],
  ["美術館","びじゅつかん","Bảo tàng mỹ thuật","Danh từ",2],
  ["不便","ふべん","Bất tiện, trắc trở","Tính từ -na",1],
  ["文化","ぶんか","Văn hóa","Danh từ",1],
  ["文学","ぶんがく","Văn học","Danh từ",2],
  ["文法","ぶんぽう","Ngữ pháp","Danh từ",1],
  ["返事","へんじ","Hồi âm, trả lời","Danh từ",1],
  ["法律","ほうりつ","Luật pháp","Danh từ",1],
  ["貿易","ぼうえき","Ngoại thương, buôn bán","Danh từ",2],
  ["方法","ほうほう","Phương pháp, cách thức","Danh từ",1],
  ["漫画","まんが","Truyện tranh Manga","Danh từ",1],
  ["約束","やくそく","Lời hứa, cuộc hẹn","Danh từ",1],
  ["予定","よてい","Dự định, lịch trình","Danh từ",1],
  ["予約","よやく","Đặt trước, hẹn trước","Danh từ",1],
  ["利用","りよう","Sử dụng, tận dụng","Danh từ",1],
  ["理由","りゆう","Lý do, nguyên cớ","Danh từ",1],
  ["歴史","れきし","Lịch sử","Danh từ",1],
  ["連絡","れんらく","Liên lạc, thông tri","Danh từ",1],

  // Adverbs & Conjunctions (1 & 2)
  ["必ず","かならず","Nhất định, chắc chắn","Phó từ",1],
  ["是非","ぜひ","Nhất định (mong muốn)","Phó từ",1],
  ["多分","たぶん","Có lẽ, chắc là","Phó từ",1],
  ["大体","だいたい","Đại khái, phần lớn","Phó từ",1],
  ["特に","とくに","Đặc biệt là","Phó từ",1],
  ["急に","きゅうに","Đột nhiên, bất ngờ","Phó từ",1],
  ["直接","ちょくせつ","Trực tiếp","Phó từ",1],
  ["はっきり","はっきり","Rõ ràng, rành mạch","Phó từ",1],
  ["すっかり","すっかり","Hoàn toàn, sạch sẽ","Phó từ",2],
  ["しっかり","しっかり","Vững chắc, chắc chắn","Phó từ",1],
  ["ゆっくり","ゆっくり","Thong thả, chậm rãi","Phó từ",1],
  ["びっくり","びっくり","Giật mình, bất ngờ","Phó từ",1],
  ["うっかり","うっかり","Lỡ đễnh, vô ý","Phó từ",2],
  ["がっかり","がっかり","Thất vọng, chán nản","Phó từ",2],
  ["ぴったり","ぴったり","Vừa khít, chuẩn xác","Phó từ",2],
  ["やっぱり","やっぱり","Quả nhiên, đúng như nghĩ","Phó từ",1],
  ["ほとんど","ほとんど","Hầu như, suýt nữa","Phó từ",1],
  ["だんだん","だんだん","Dần dần, từng bước","Phó từ",1],
  ["どんどん","どんどん","Nhanh chóng, ào ào","Phó từ",1],
  ["そろそろ","そろそろ","Sắp sửa, chuẩn bị","Phó từ",1],
  ["とうとう","とうとう","Cuối cùng thì","Phó từ",2],
  ["やっと","やっと","Cuối cùng cũng xong","Phó từ",1],
  ["たまに","たまに","Thỉnh thoảng, đôi khi","Phó từ",2],
  ["ぜんぜん","ぜんぜん","Hoàn toàn không (đi với phủ định)","Phó từ",1],
  ["けっして","けっして","Tuyệt đối không","Phó từ",1],
  ["もし","もし","Nếu như, giả sử","Phó từ",1],
  ["いくら～ても","いくら～ても","Dù cho bao nhiêu chăng nữa","Phó từ",2],
  ["例えば","たとえば","Ví dụ như là","Liên từ",1],
  ["それに","それに","Hơn nữa, vả lại","Liên từ",1],
  ["それで","それで","Vì thế, cho nên","Liên từ",1],
  ["それなら","それなら","Nếu vậy thì","Liên từ",1],
  ["しかし","しかし","Tuy nhiên, nhưng","Liên từ",1]
];
