/**
 * Additional Comprehensive JLPT Vocabulary Expansion Pack (N5-N1)
 */
module.exports = {
  N5: [
    // Additional N5 daily objects, actions, numbers, expressions
    ["一","いち","Một, số 1","Số từ",1],
    ["二","に","Hai, số 2","Số từ",1],
    ["三","さん","Ba, số 3","Số từ",1],
    ["四","よん / し","Bốn, số 4","Số từ",1],
    ["五","ご","Năm, số 5","Số từ",1],
    ["六","ろく","Sáu, số 6","Số từ",1],
    ["七","なな / しち","Bảy, số 7","Số từ",1],
    ["八","はち","Tám, số 8","Số từ",1],
    ["九","きゅう / く","Chín, số 9","Số từ",1],
    ["十","じゅう","Mười, số 10","Số từ",1],
    ["百","ひゃく","Một trăm","Số từ",1],
    ["千","せん","Một nghìn","Số từ",1],
    ["万","まん","Mười nghìn, vạn","Số từ",1],
    ["円","えん","Đồng Yên Nhật","Danh từ",1],
    ["一つ","ひとつ","1 cái (đếm đồ vật)","Số từ",1],
    ["二つ","ふたつ","2 cái","Số từ",1],
    ["三つ","みっつ","3 cái","Số từ",1],
    ["四つ","よっつ","4 cái","Số từ",1],
    ["五つ","いつつ","5 cái","Số từ",1],
    ["六つ","むっつ","6 cái","Số từ",1],
    ["七つ","ななつ","7 cái","Số từ",1],
    ["八つ","やっつ","8 cái","Số từ",1],
    ["九つ","ここのつ","9 cái","Số từ",1],
    ["十","とお","10 cái","Số từ",1],
    ["一人","ひとり","1 người","Danh từ",1],
    ["二人","ふたり","2 người","Danh từ",1],
    ["一日","ついたち","Ngày mùng một","Danh từ",1],
    ["二日","ふつか","Ngày mùng hai, 2 ngày","Danh từ",1],
    ["三日","みっか","Ngày mùng ba, 3 ngày","Danh từ",1],
    ["四日","よっか","Ngày mùng bốn, 4 ngày","Danh từ",1],
    ["五日","いつか","Ngày mùng năm, 5 ngày","Danh từ",1],
    ["六日","むいか","Ngày mùng sáu, 6 ngày","Danh từ",1],
    ["七日","なのか","Ngày mùng bảy, 7 ngày","Danh từ",1],
    ["八日","ようか","Ngày mùng tám, 8 ngày","Danh từ",1],
    ["九日","ここのか","Ngày mùng chín, 9 ngày","Danh từ",1],
    ["十日","とおか","Ngày mùng mười, 10 ngày","Danh từ",1],
    ["十四日","じゅうよっか","Ngày mười bốn, 14 ngày","Danh từ",1],
    ["二十日","はつか","Ngày hai mươi, 20 ngày","Danh từ",1],
    ["二十四日","にじゅうよっか","Ngày hai mươi tư, 24 ngày","Danh từ",1],
    ["上","うえ","Phía trên","Danh từ",1],
    ["下","した","Phía dưới","Danh từ",1],
    ["前","まえ","Phía trước","Danh từ",1],
    ["後ろ","うしろ","Phía sau","Danh từ",1],
    ["右","みぎ","Bên phải","Danh từ",1],
    ["左","ひだり","Bên trái","Danh từ",1],
    ["中","なか","Bên trong, ở giữa","Danh từ",1],
    ["外","そと","Bên ngoài","Danh từ",1],
    ["隣","となり","Bên cạnh (cùng loại)","Danh từ",1],
    ["近く","ちかく","Ở gần, lân cận","Danh từ",1],
    ["間","あいだ","Khoảng giữa","Danh từ",1],
    ["色","いろ","Màu sắc","Danh từ",1],
    ["赤 / 赤い","あか / あかい","Màu đỏ / Đỏ","Tính từ -i",1],
    ["青 / 青い","あお / あおい","Màu xanh da trời / Xanh","Tính từ -i",1],
    ["白 / 白い","しろ / しろい","Màu trắng / Trắng","Tính từ -i",1],
    ["黒 / 黒い","くろ / くろい","Màu đen / Đen","Tính từ -i",1],
    ["黄色 / 黄色い","きいろ / きいろい","Màu vàng / Vàng","Tính từ -i",1],
    ["茶色 / 茶色い","ちゃいろ / ちゃいろい","Màu nâu / Nâu","Tính từ -i",2],
    ["緑","みどり","Màu xanh lá cây","Danh từ",1],
    ["ピンク","ぴんく","Màu hồng","Danh từ",1],
    ["オレンジ","おれんじ","Màu cam","Danh từ",1],
    ["はい","はい","Vâng, dạ, đúng","Từ thán từ",1],
    ["いいえ","いいえ","Không, không phải","Từ thán từ",1],
    ["おはようございます","おはようございます","Chào buổi sáng","Chào hỏi",1],
    ["こんにちは","こんにちは","Chào buổi trưa / Xin chào","Chào hỏi",1],
    ["こんばんは","こんばんは","Chào buổi tối","Chào hỏi",1],
    ["おやすみなさい","おやすみなさい","Chúc ngủ ngon","Chào hỏi",1],
    ["さようなら","さようなら","Tạm biệt","Chào hỏi",1],
    ["ありがとうございます","ありがとうございます","Xin cảm ơn rất nhiều","Chào hỏi",1],
    ["すみません","すみません","Xin lỗi, làm phiền","Chào hỏi",1],
    ["ごめんなさい","ごめんなさい","Xin lỗi (thân mật)","Chào hỏi",1],
    ["いただきます","いただきます","Mời dùng bữa (nói trước khi ăn)","Chào hỏi",1],
    ["ごちそうさまでした","ごちそうさまでした","Cảm ơn vì bữa ăn ngon","Chào hỏi",1],
    ["いってきます","いってきます","Tôi đi đây (nói khi ra khỏi nhà)","Chào hỏi",1],
    ["いってらっしゃい","いってらっしゃい","Bạn đi nhé","Chào hỏi",1],
    ["ただいま","ただいま","Tôi đã về rồi đây","Chào hỏi",1],
    ["おかえりなさい","おかえりなさい","Bạn đã về đấy à","Chào hỏi",1],
    ["はじめまして","はじめまして","Rất hân hạnh được gặp lần đầu","Chào hỏi",1],
    ["どうぞよろしくおねがいします","どうぞよろしくおねがいします","Rất mong được giúp đỡ","Chào hỏi",1],
    ["お疲れ様でした","おつかれさまでした","Bạn đã vất vả rồi","Chào hỏi",1],
    ["失礼します","しつれいします","Xin phép thất lễ (khi vào phòng/về trước)","Chào hỏi",1]
  ],

  N4: [
    // Additional N4 Grammar words, Adverbs, Daily verbs
    ["あんなに","あんなに","Đến mức như thế kia","Phó từ",2],
    ["そんなに","そんなに","Đến mức như vậy","Phó từ",1],
    ["こんなに","こんなに","Đến mức như thế này","Phó từ",1],
    ["どんなに","どんなに","Đến mức dường nào","Phó từ",2],
    ["あんまり","あんまり","Không... lắm (đi với phủ định)","Phó từ",1],
    ["いかが","いかが","Như thế nào (kính ngữ của どう)","Phó từ",1],
    ["いつか","いつか","Một lúc nào đó, một ngày nào đó","Phó từ",1],
    ["いつでも","いつでも","Bất cứ lúc nào","Phó từ",1],
    ["どこか","どこか","Một nơi nào đó","Phó từ",1],
    ["どこでも","どこでも","Bất cứ nơi đâu","Phó từ",1],
    ["だれか","だれか","Một ai đó","Phó từ",1],
    ["だれでも","だれでも","Bất cứ ai","Phó từ",1],
    ["なにか","なにか","Một cái gì đó","Phó từ",1],
    ["なんでも","なんでも","Bất cứ thứ gì","Phó từ",1],
    ["いっぱい","いっぱい","Đầy ắp, no căng, nhiều","Phó từ",1],
    ["おっしゃる","おっしゃる","Nói (kính ngữ của 言う)","Động từ",1],
    ["なさる","なさる","Làm (kính ngữ của する)","Động từ",1],
    ["くださる","くださる","Cho tôi (kính ngữ của くれる)","Động từ",1],
    ["ご覧になる","ごらんになる","Xem, nhìn (kính ngữ của 見る)","Động từ",1],
    ["召し上がる","めしあがる","Ăn, uống (kính ngữ của 食べる/飲む)","Động từ",1],
    ["いらっしゃる","いらっしゃる","Đi, đến, ở (kính ngữ)","Động từ",1],
    ["参る","まいる","Đi, đến (khiêm nhường của 行く/来る)","Động từ",1],
    ["申す","もうす","Nói, tên là (khiêm nhường của 言う)","Động từ",1],
    ["致す","いたす","Làm (khiêm nhường của する)","Động từ",1],
    ["いただく","いただく","Ăn, uống, nhận (khiêm nhường)","Động từ",1],
    ["拝見する","はいけんする","Xem, nhìn (khiêm nhường của 見る)","Động từ",1],
    ["存じる","ぞんじる","Biết, nghĩ (khiêm nhường của 知る/思う)","Động từ",2],
    ["伺う","うかがう","Hỏi thăm, ghé thăm (khiêm nhường)","Động từ",1],
    ["カーテン","かーてん","Rèm cửa","Danh từ",1],
    ["カレンダー","かれんだー","Tờ lịch","Danh từ",1],
    ["シャワー","しゃわー","Vòi hoa sen","Danh từ",1],
    ["エアコン","えあこん","Máy điều hòa nhiệt độ","Danh từ",1],
    ["スイッチ","すいっち","Công tắc điện","Danh từ",1],
    ["リモコン","りもこん","Điều khiển từ xa","Danh từ",1],
    ["ベッド","べっど","Giường ngủ","Danh từ",1],
    ["タオル","たおる","Khăn tắm, khăn lau","Danh từ",1],
    ["せっけん","せっけん","Xà phòng bánh","Danh từ",1],
    ["シャンプー","しゃんぷー","Dầu gội đầu","Danh từ",1],
    ["歯ブラシ","はぶらし","Bàn chải đánh răng","Danh từ",1],
    ["おもちゃ","おもちゃ","Đồ chơi trẻ em","Danh từ",2],
    ["ぬいぐるみ","ぬいぐるみ","Thú nhồi bông","Danh từ",2],
    ["アクセサリー","あくせさりー","Đồ trang sức phụ kiện","Danh từ",2],
    ["スーツ","すーつ","Bộ vét, âu phục","Danh từ",1],
    ["ネクタイ","ねくたい","Cà vạt","Danh từ",1],
    ["コート","こーと","Áo khoác dạ, áo choàng","Danh từ",1],
    ["セーター","せーたー","Áo len","Danh từ",1],
    ["ポケット","ぽけっと","Túi áo, túi quần","Danh từ",1],
    ["ボタン","ぼたん","Cúc áo, nút bấm","Danh từ",1],
    ["ジッパー / チャック","じっぱー","Khóa kéo, phéc-mơ-tuya","Danh từ",2],
    ["手袋","てぶくろ","Đôi găng tay","Danh từ",1],
    ["マフラー","まふらー","Khăn quàng cổ len","Danh từ",1],
    ["指輪","ゆびわ","Chiếc nhẫn","Danh từ",2],
    ["ネックレス","ねっくれす","Dây chuyền, vòng cổ","Danh từ",2],
    ["ピアス","ぴあす","Khuyên tai","Danh từ",2]
  ],

  N3: [
    // Additional N3 Business & Daily concepts
    ["挨拶回り","あいさつまわり","Đi chào hỏi xã giao","Danh từ",2],
    ["相変わらず","あいかわらず","Như thường lệ, vẫn vậy","Phó từ",1],
    ["合図","あいず","Dấu hiệu, ám hiệu","Danh từ",1],
    ["曖昧","あいまい","Mơ hồ, mập mờ","Tính từ -na",1],
    ["遭う","あう","Gặp tai nạn, gặp sự cố","Động từ",1],
    ["扇ぐ","あおぐ","Quạt gió","Động từ",2],
    ["青白い","あおじろい","Xanh xao, tái nhợt","Tính từ -i",2],
    ["呆れる","あきれる","Kinh ngạc đến mức cạn lời","Động từ",1],
    ["握手","あくしゅ","Bắt tay giao lưu","Danh từ",1],
    ["悪魔","あくま","Ác ma, ma quỷ","Danh từ",2],
    ["明け方","あけがた","Rạng sáng, bình minh","Danh từ",2],
    ["預金","よきん","Tiền gửi tiết kiệm","Danh từ",1],
    ["汗","あせ","Mồ hôi","Danh từ",1],
    ["与える","あたえる","Ban cho, đem lại","Động từ",1],
    ["当たり前","あたりまえ","Đương nhiên, dĩ nhiên","Tính từ -na",1],
    ["あちこち","あちこち","Khắp nơi, đây đó","Đại từ",1],
    ["集まり","あつまり","Cuộc tụ họp, buổi gặp mặt","Danh từ",1],
    ["宛名","あてな","Tên người nhận (thư từ)","Danh từ",2],
    ["油断","ゆだん","Chủ quan, lơ là mất cảnh giác","Danh từ",1],
    ["暴れる","あばれる","Quậy phá náo loạn","Động từ",2],
    ["甘やかす","あまやかす","Nuông chiều","Động từ",2],
    ["編む","あむ","Đan len, đan lát","Động từ",2],
    ["編み物","あみもの","Đồ đan len","Danh từ",2],
    ["誤り","あやまり","Lỗi sai, sai sót","Danh từ",1],
    ["粗い","あらい","Thô ráp, ráp ráp","Tính từ -i",2],
    ["有難い","ありがたい","Biết ơn, may mắn thay","Tính từ -i",1],
    ["慌ただしい","あわただしい","Bận rộn túi bụi, vội vã","Tính từ -i",1],
    ["哀れ","あわれ","Đáng thương, thảm thương","Tính từ -na",2],
    ["安易","あんい","Dễ dãi, tùy tiện qua loa","Tính từ -na",2],
    ["案外","あんがい","Bất ngờ ngoài dự tính","Phó từ",1],
    ["暗記","あんき","Học thuộc lòng","Danh từ",1],
    ["安定","あんてい","Ổn định vững vàng","Danh từ",1],
    ["案内","あんない","Chỉ dẫn","Danh từ",1],
    ["胃","い","Dạ dày, bao tử","Danh từ",1],
    ["委員","いいん","Ủy viên ban chấp hành","Danh từ",2],
    ["言い訳","いいわけ","Biện bạch, lý do bao biện","Danh từ",1],
    ["家出","いえで","Bỏ nhà ra đi","Danh từ",2],
    ["生き生き","いきいき","Sống động, tràn đầy sức sống","Phó từ",1],
    ["勢い","いきおい","Sức mạnh, khí thế dâng cao","Danh từ",1],
    ["息","いき","Hơi thở","Danh từ",1],
    ["育児","いくじ","Chăm sóc nuôi dạy con nhỏ","Danh từ",1],
    ["幾分","いくぶん","Một chút, phần nào đó","Phó từ",2],
    ["医師","いし","Bác sĩ (danh xưng nghề)","Danh từ",1],
    ["意思","いし","Ý chí, chủ định","Danh từ",1],
    ["意識","いしき","Ý thức, nhận thức","Danh từ",1],
    ["意欲","いよく","Động lực, ý chí hăng hái","Danh từ",1],
    ["衣食住","いしょくじゅう","Nhu cầu ăn mặc ở","Danh từ",2],
    ["維持","いじ","Duy trì trạng thái","Danh từ",1],
    ["意地悪","いじわる","Tâm địa xấu xa, hiểm độc","Tính từ -na",1],
    ["泉","いずみ","Suối nước ngầm","Danh từ",2],
    ["偉大","いだい","Vĩ đại, to lớn","Tính từ -na",1],
    ["抱く","いだく / だく","Ôm ấp hoài bão / Ôm vào lòng","Động từ",1],
    ["悪戯","いたずら","Nghịch ngợm, trêu ghẹo","Danh từ",1],
    ["痛み","いたみ","Cơn đau nhức nhối","Danh từ",1],
    ["位置","いち","Vị trí tọa độ","Danh từ",1],
    ["市場","いちば / しじょう","Khu chợ / Thị trường","Danh từ",1],
    ["一等","いっとう","Hạng nhất, giải nhất","Danh từ",2],
    ["一時","いちじ","Tạm thời một thời gian","Danh từ",1],
    ["一段と","いちだんと","Hơn hẳn một bậc, rõ rệt","Phó từ",1],
    ["一流","いちりゅう","Đẳng cấp hàng đầu, hạng nhất","Danh từ",1],
    ["一挙に","いっきょに","Một mạch, một phát xong ngay","Phó từ",2],
    ["一致","いっち","Thống nhất, ăn khớp ý kiến","Danh từ",1],
    ["日程","にってい","Lịch trình công tác","Danh từ",1],
    ["従兄弟","いとこ","Anh em họ","Danh từ",2],
    ["稲","いね","Cây lúa nước","Danh từ",2],
    ["居眠り","いねむり","Ngủ gật ban ngày","Danh từ",1],
    ["命","いのち","Sinh mạng con người","Danh từ",1],
    ["違反","いはん","Vi phạm quy định","Danh từ",1],
    ["衣服","いふく","Y phục quần áo","Danh từ",2],
    ["居間","いま","Phòng khách gia đình","Danh từ",2],
    ["今に","いまに","Chẳng mấy chốc, sớm muộn gì","Phó từ",1],
    ["今にも","いまにも","Sắp sửa xảy ra tới nơi","Phó từ",1],
    ["以来","いらい","Kể từ đó trở đi","Danh từ",1],
    ["依頼","いらい","Yêu cầu, nhờ vả công việc","Danh từ",1],
    ["医療","いりょう","Y tế chữa trị","Danh từ",1],
    ["岩","いわ","Tảng đá lớn","Danh từ",2],
    ["祝い","いわい","Tiệc mừng, lễ mừng","Danh từ",1],
    ["印刷","いんさつ","In ấn tài liệu","Danh từ",1],
    ["引退","いんたい","Nghỉ hưu, giải nghệ","Danh từ",1],
    ["引用","いんよう","Trích dẫn văn bản","Danh từ",1],
    ["引力","いんりょく","Lực hấp dẫn, trọng lực","Danh từ",2],
    ["運","うん","Vận may, số phận","Danh từ",1],
    ["運勢","うんせい","Vận thế, số mệnh","Danh từ",2],
    ["運賃","うんちん","Cước phí vận chuyển","Danh từ",2],
    ["影響","えいきょう","Ảnh hưởng tác động","Danh từ",1],
    ["営業","えいぎょう","Kinh doanh bán hàng","Danh từ",1],
    ["衛生","えいせい","Vệ sinh môi trường phòng dịch","Danh từ",2],
    ["栄養","えいよう","Dinh dưỡng chất bổ","Danh từ",1],
    ["笑顔","えがお","Nụ cười tươi tắn","Danh từ",1],
    ["描く","えがく","Vẽ tranh, miêu tả hình dung","Động từ",1],
    ["餌","えさ","Thức ăn cho động vật/mồi câu","Danh từ",2],
    ["得","とく","Món hời, có lợi","Tính từ -na",1],
    ["損","そん","Mất mát, thua lỗ","Tính từ -na",1]
  ],

  N2: [
    // Additional N2 Economics, Society, Logic terms
    ["把握","はあく","Sự thấu suốt nắm chắc","Danh từ",1],
    ["敗北","はいぼく","Sự thất bại thua trận","Danh từ",1],
    ["配慮","はいりょ","Sự quan tâm chu đáo tế nhị","Danh từ",1],
    ["破棄","はき","Hủy bỏ hiệp định vứt rác","Danh từ",1],
    ["迫害","はくがい","Sự bức hại đàn áp tôn giáo","Danh từ",2],
    ["白熱","はくねつ","Sôi nổi nảy lửa (tranh luận/trận đấu)","Danh từ",1],
    ["発揮","はっき","Phát huy tối đa năng lực","Danh từ",1],
    ["発作","ほっさ","Cơn phát tác co giật/đau tim","Danh từ",2],
    ["発足","ほっそく","Sự thành lập đi vào hoạt động","Danh từ",1],
    ["抜擢","ばってき","Sự cất nhắc đề bạt vượt cấp","Danh từ",2],
    ["汎用性","はんようせい","Tính ứng dụng rộng rãi đa năng","Danh từ",1],
    ["悲惨","ひさん","Bi thảm thê lương","Tính từ -na",1],
    ["比率","ひりつ","Tỷ lệ phần trăm so sánh","Danh từ",1],
    ["比例","ひれい","Tỷ lệ thuận","Danh từ",1],
    ["反比例","はんぴれい","Tỷ lệ nghịch","Danh từ",2],
    ["紛失","ふんしつ","Làm thất lạc mất đồ","Danh từ",1],
    ["憤慨","ふんがい","Phẫn nộ căm phẫn uất ức","Danh từ",2],
    ["並行","へいこう","Song song đồng thời cùng lúc","Danh từ",1],
    ["平衡","へいこう","Sự thăng bằng cân bằng lực","Danh từ",2],
    ["平穏","へいおん","Bình yên êm ả không sóng gió","Tính từ -na",1],
    ["返還","へんかん","Hoàn trả lại lãnh thổ/tiền cọc","Danh từ",1],
    ["弁解","べんかい","Biện giải thanh minh lý do","Danh từ",1],
    ["変革","へんかく","Cuộc biến cách cách mạng lớn","Danh từ",1],
    ["変容","へんよう","Biến đổi dung mạo thái độ","Danh từ",2],
    ["方針","ほうしん","Phương châm chỉ đạo","Danh từ",1],
    ["崩壊","ほうかい","Sự sụp đổ tan tành","Danh từ",1],
    ["膨張","ぼうちょう","Sự giãn nở phình to lạm phát","Danh từ",1],
    ["飽和","ほうわ","Trạng thái bão hòa tối đa","Danh từ",1],
    ["没落","ぼつらく","Sự suy tàn sụp đổ dòng dõi","Danh từ",2],
    ["本格的","ほんかくてき","Mang tính bài bản đích thực","Tính từ -na",1],
    ["埋蔵","まいぞう","Chôn vùi dự trữ khoáng sản","Danh từ",2],
    ["末期","まっき","Giai đoạn cuối thời kỳ chót","Danh từ",1],
    ["摩擦","まさつ","Ma sát cọ xát xung đột","Danh từ",1],
    ["満喫","まんきつ","Tận hưởng thỏa thuê","Danh từ",1],
    ["密度","みつど","Mật độ dân số/hạt","Danh từ",1],
    ["無言","むごん","Im lặng không nói lời nào","Danh từ",1],
    ["名誉","めいよ","Danh dự uy tín thanh danh","Danh từ",1],
    ["滅亡","めつぼう","Sự diệt vong sụp đổ triều đại","Danh từ",1],
    ["面目","めんぼく","Thể diện bộ mặt danh dự","Danh từ",2],
    ["模倣","もほう","Sự bắt chước mô phỏng sao chép","Danh từ",1],
    ["黙認","もくにん","Sự ngầm thừa nhận làm ngơ","Danh từ",1],
    ["誘致","ゆうち","Thu hút mời gọi đầu tư vốn","Danh từ",1],
    ["融通","ゆうずう","Sự linh hoạt ứng biến uyển chuyển","Danh từ",1],
    ["有益","ゆうえき","Có ích lợi hữu ích thiết thực","Tính từ -na",1],
    ["有力","ゆうりょく","Có sức ảnh hưởng mạnh mẽ, có triển vọng","Tính từ -na",1],
    ["余暇","よか","Thời gian rảnh rỗi giải trí","Danh từ",1],
    ["抑制","よくせい","Sự ức chế kiềm chế kìm nén","Danh từ",1],
    ["落胆","らくたん","Sự thất vọng chán nản cùng cực","Danh từ",2],
    ["濫用","らんよう","Sự lạm dụng quyền lực/thuốc","Danh từ",1],
    ["利益","りえき","Lợi nhuận kinh doanh","Danh từ",1],
    ["連携","れんけい","Sự liên kết phối hợp hành động","Danh từ",1],
    ["論争","ろんそう","Cuộc tranh luận bút chiến nảy lửa","Danh từ",1]
  ],

  N1: [
    // Additional N1 Academic & Nuanced expressions
    ["愛着","あいちゃく","Sự quyến luyến gắn bó tha thiết","Danh từ",1],
    ["隘路","あいろ","Hẻm núi hiểm trở, nút thắt cổ chai cản trở","Danh từ",3],
    ["悪辣","あくらつ","Độc ác hiểm độc xảo quyệt tàn nhẫn","Tính từ -na",2],
    ["あからさま","あからさま","Rõ mồn một trắng trợn không che giấu","Tính từ -na",1],
    ["憧憬","しょうけい / どうけい","Sự ngưỡng mộ khao khát cháy bỏng","Danh từ",2],
    ["圧倒的","あっとうてき","Mang tính áp đảo vượt trội tuyệt đối","Tính từ -na",1],
    ["暗黙","あんもく","Ngầm hiểu không cần nói ra (ngầm định)","Danh từ",1],
    ["遺言","ゆいごん / いげん","Di chúc lời trăn trối cuối cùng","Danh từ",1],
    ["一環","いっかん","Một phần trong chuỗi kế hoạch","Danh từ",1],
    ["一存","いちぞん","Quyết định cá nhân độc đoán","Danh từ",2],
    ["一変","いっぺん","Thay đổi 180 độ hoàn toàn diện mạo","Danh từ",1],
    ["因習","いんしゅう","Hủ tục phong tục cổ hủ lạc hậu","Danh từ",2],
    ["隠蔽","いんぺい","Sự che đậy giấu giếm tang vật sự thật","Danh từ",1],
    ["婉曲","えんきょく","Nói khéo nói bóng gió tế nhị","Tính từ -na",1],
    ["横柄","おうへい","Kiêu ngạo hống hách xấc xược","Tính từ -na",2],
    ["往生","おうじょう","An nghỉ vãng sanh / Chịu thua bế tắc","Danh từ",2],
    ["概略","がいりゃく","Khái lược tóm tắt sơ lược","Danh từ",1],
    ["過密","かみつ","Quá tải đông đúc nghẹt thở (lịch trình)","Tính từ -na",1],
    ["簡素","かんそ","Đơn sơ giản dị tinh gọn","Tính từ -na",1],
    ["肝要","かんよう","Cốt lõi then chốt vô cùng quan trọng","Tính từ -na",1],
    ["詭弁","きべん","Ngụy biện xảo ngôn","Danh từ",1],
    ["機敏","きびん","Nhanh nhẹn cơ biến ứng phó lẹ làng","Tính từ -na",2],
    ["急務","きゅうむ","Nhiệm vụ cấp bách hàng đầu","Danh từ",1],
    ["強硬","きょうこう","Cứng rắn ngoan cường không lùi bước","Tính từ -na",1],
    ["郷愁","きょうしゅう","Nỗi nhớ quê hương da diết","Danh từ",2],
    ["驚異","きょうい","Kỳ diệu phi thường gây kinh ngạc","Danh từ",1],
    ["克明","こくめい","Tỉ mỉ chi tiết rành mạch từng li từng tí","Tính từ -na",2],
    ["懇願","こんがん","Khẩn cầu van xin tha thiết","Danh từ",2],
    ["惨敗","ざんぱい","Thua thảm hại thất bại nặng nề","Danh từ",1],
    ["示唆","しさ","Ám chỉ gợi ý định hướng ngầm","Danh từ",1],
    ["執念","しゅうねん","Tâm niệm bám đuổi dai dẳng khát khao","Danh từ",1],
    ["終息","しゅうそく","Chấm dứt hoàn toàn (dịch bệnh/chiến tranh)","Danh từ",1],
    ["深奥","しんおう","Thâm sâu huyền bí uyên bác","Tính từ -na",3],
    ["随時","ずいじ","Bất cứ lúc nào khi cần thiết","Phó từ",1],
    ["推移","すいい","Sự biến thiên chuyển động xu hướng","Danh từ",1],
    ["凄惨","せいさん","Kinh hoàng thảm khốc rùng rợn","Tính từ -na",2],
    ["精緻","せいち","Tinh xảo tỉ mỉ chuẩn xác tuyệt đối","Tính từ -na",2],
    ["惜敗","せきはい","Thua sít sao tiếc nuối gang tấc","Danh từ",1],
    ["切迫","せっぱく","Cấp bách khẩn trương nghẹt thở (thời gian)","Danh từ",1],
    ["拙劣","せつれつ","Vụng về dở tệ kém cỏi","Tính từ -na",2],
    ["漸減","ぜんげん","Giảm dần từ từ từng bước","Danh từ",1],
    ["漸増","ぜんぞう","Tăng dần từ từ từng bước","Danh từ",1],
    ["多角","たかく","Đa góc nhìn đa ngành nghề","Danh từ",1],
    ["多寡","たか","Nhiều hay ít, số lượng bao nhiêu","Danh từ",3],
    ["弛緩","しかん","Thư giãn thả lỏng / Rã rời lỏng lẻo","Danh từ",2],
    ["逐一","ちくいち","Từng cái một tường tận chi tiết","Phó từ",1],
    ["緻密","ちみつ","Tỉ mỉ kín kẽ cẩn trọng không kẽ hở","Tính từ -na",1],
    ["直観","ちょっかん","Trực giác trực cảm nhạy bén","Danh từ",1],
    ["痛切","つうせつ","Sâu sắc thấu tận tâm can","Tính từ -na",1],
    ["杜撰","ずさん","Cẩu thả cẩu thả qua loa tắc trách","Tính từ -na",1],
    ["恬淡","てんたん","Thản nhiên thanh thản không màng danh lợi","Tính từ -na",3],
    ["透徹","とうてつ","Sáng suốt thấu triệt nhìn thấu rõ ràng","Tính từ -na",2],
    ["唐突","とうとつ","Đột ngột bất thình lình đường đột","Tính từ -na",1],
    ["難解","なんかい","Nan giải khó hiểu hóc búa","Tính từ -na",1],
    ["捏造","ねつぞう","Bịa đặt ngụy tạo sự thật","Danh từ",1],
    ["濃密","のうみつ","Đậm đặc sâu sắc dầy dặn","Tính từ -na",1],
    ["波及","はきゅう","Lan truyền ảnh hưởng dây chuyền sang bên cạnh","Danh từ",1],
    ["跋扈","ばっこ","Hoành hành ngang ngược lộng hành","Danh từ",2],
    ["氾濫","はんらん","Tràn ngập lũ lụt / Tràn lan thông tin rác","Danh từ",1],
    ["偏狭","へんきょう","Hẹp hòi định kiến thiển cận","Tính từ -na",2],
    ["奔流","ほんりゅう","Dòng thác cuồn cuộn chảy xiết","Danh từ",3],
    ["未遂","みすい","Chưa thành bất thành (tội phạm)","Danh từ",1],
    ["密接","みっせつ","Mật thiết gắn bó chặt chẽ","Tính từ -na",1],
    ["猛威","もうい","Sức tàn phá hung tợn cuồng nộ (bão/dịch)","Danh từ",1],
    ["悠久","ゆうきゅう","Vĩnh hằng bất tận trường tồn ngàn năm","Tính từ -na",2],
    ["歪曲","わいきょく","Xuyên tạc bóp méo hình ảnh sự thật","Danh từ",1]
  ]
};
