/**
 * JLPT Vocabulary Expansion Pack 3 (500+ words across N4, N3, N2, N1)
 */
module.exports = {
  N4: [
    ["お祝い","おいわい","Lời chúc mừng, quà mừng","Danh từ",1],
    ["押し入れ","おしいれ","Tủ tường truyền thống Nhật","Danh từ",1],
    ["お嬢さん","おじょうさん","Tiểu thư, con gái của quý vị","Danh từ",2],
    ["おっしゃる","おっしゃる","Nói (kính ngữ)","Động từ",1],
    ["落とし物","おとしもの","Đồ thất lạc","Danh từ",1],
    ["おどり","おどり","Điệu nhảy múa","Danh từ",2],
    ["驚く","おどろく","Kinh ngạc, bất ngờ","Động từ",1],
    ["お祭り","おまつり","Lễ hội truyền thống","Danh từ",1],
    ["お見舞い","おみまい","Đi thăm người ốm","Danh từ",1],
    ["お土産","おみやげ","Quà đặc sản du lịch","Danh từ",1],
    ["思い出す","おもいだす","Nhớ lại dĩ vãng","Động từ",1],
    ["思う","おもう","Nghĩ rằng","Động từ",1],
    ["おもちゃ","おもちゃ","Đồ chơi","Danh từ",1],
    ["海岸","かいがん","Bờ biển","Danh từ",1],
    ["会議","かいぎ","Cuộc họp bàn bạc","Danh từ",1],
    ["会議室","かいぎしつ","Phòng họp","Danh từ",1],
    ["会場","かいじょう","Hội trường tổ chức","Danh từ",1],
    ["会話","かいわ","Hội thoại, đàm thoại","Danh từ",1],
    ["帰り","かえり","Đường về, việc trở về","Danh từ",1],
    ["変える","かえる","Thay đổi, đổi khác","Động từ",1],
    ["科学","かがく","Khoa học","Danh từ",1],
    ["鏡","かがみ","Chiếc gương soi","Danh từ",1],
    ["掛ける","かける","Đeo kính, tốn thời gian","Động từ",1],
    ["飾る","かざる","Trang hoàng, trang trí","Động từ",1],
    ["火事","かじ","Vụ hỏa hoạn, cháy nhà","Danh từ",1],
    ["ガス","がす","Khí ga","Danh từ",1],
    ["ガソリン","がそりん","Xăng dầu xe","Danh từ",1],
    ["堅い / 固い","かたい","Cứng cáp, cứng nhắc","Tính từ -i",1],
    ["形","かたち","Hình dạng, vóc dáng","Danh từ",1],
    ["片付ける","かたづける","Thu dọn ngăn nắp","Động từ",1],
    ["勝つ","かつ","Chiến thắng đối thủ","Động từ",1],
    ["格好","かっこう","Kiểu cách, vẻ ngoài","Danh từ",1],
    ["家内","かない","Vợ tôi (cách gọi khiêm tốn)","Danh từ",1],
    ["悲しい","かなしい","Đau buồn, bi ai","Tính từ -i",1],
    ["必ず","かならず","Nhất định phải làm","Phó từ",1],
    ["お金持ち","おかねもち","Người giàu có, đại gia","Danh từ",1],
    ["彼女","かのじょ","Cô ấy, bạn gái","Đại từ",1],
    ["壁","かべ","Bức tường nhà","Danh từ",1],
    ["髪","かみ","Mái tóc","Danh từ",1],
    ["噛む","かむ","Nhai, cắn","Động từ",1],
    ["通う","かよう","Đi học/đi làm đều đặn","Động từ",1],
    ["彼","かれ","Anh ấy, bạn trai","Đại từ",1],
    ["乾く","かわく","Khô ráo","Động từ",1],
    ["代わり","かわり","Thay mặt, đại diện","Danh từ",1],
    ["変わる","かわる","Thay đổi, biến đổi","Động từ",1],
    ["考える","かんがえる","Suy nghĩ, đắn đo","Động từ",1],
    ["看護師","かんごし","Điều dưỡng, y tá","Danh từ",1],
    ["簡単","かんたん","Dễ dàng, đơn giản","Tính từ -na",1],
    ["気","き","Tâm trạng, khí sắc, tinh thần","Danh từ",1],
    ["機会","きかい","Cơ hội may mắn","Danh từ",1],
    ["危険","きけん","Nguy hiểm tính mạng","Tính từ -na",1],
    ["聞こえる","きこえる","Nghe thấy (tự nhiên)","Động từ",1],
    ["汽車","きしゃ","Tàu hỏa chạy hơi nước","Danh từ",2],
    ["技術","ぎじゅつ","Kỹ thuật công nghệ","Danh từ",1],
    ["季節","きせつ","Mùa màng trong năm","Danh từ",1],
    ["規則","きそく","Quy tắc, nội quy","Danh từ",1],
    ["絹","きぬ","Lụa tơ tằm","Danh từ",2],
    ["厳しい","きびしい","Nghiêm khắc, khắc nghiệt","Tính từ -i",1],
    ["気分","きぶん","Tâm trạng, cảm giác cơ thể","Danh từ",1],
    ["決まる","きまる","Được ấn định","Động từ",1],
    ["君","きみ","Em, bạn (thân mật)","Đại từ",1],
    ["決める","きめる","Hạ quyết tâm, chọn lựa","Động từ",1],
    ["気持ち","きもち","Cảm giác, tâm tư","Danh từ",1],
    ["着物","きもの","Áo Kimono truyền thống","Danh từ",1],
    ["客","きゃく","Khách hàng, khách mời","Danh từ",1],
    ["急","きゅう","Gấp gáp, dốc đứng, đột ngột","Tính từ -na",1],
    ["急行","きゅうこう","Tàu tốc hành","Danh từ",1],
    ["教育","きょういく","Giáo dục đào tạo","Danh từ",1],
    ["教会","きょうかい","Nhà thờ giáo xứ","Danh từ",1],
    ["競争","きょうそう","Thi đấu, cạnh tranh","Danh từ",1],
    ["興味","きょうみ","Hứng thú quan tâm","Danh từ",1],
    ["近所","きんじょ","Khu vực hàng xóm láng giềng","Danh từ",1]
  ],

  N3: [
    ["管理","かんり","Quản lý trông nom","Danh từ",1],
    ["完了","かんりょう","Hoàn thành trọn vẹn","Danh từ",1],
    ["関連","かんれん","Liên quan mật thiết","Danh từ",1],
    ["議員","ぎいん","Nghị sĩ dân biểu","Danh từ",1],
    ["記憶","きおく","Ký ức, trí nhớ","Danh từ",1],
    ["気温","きおん","Nhiệt độ không khí","Danh từ",1],
    ["着替え","きがえ","Thay quần áo, đồ dự phòng","Danh từ",1],
    ["企画","きかく","Quy hoạch dự án, kế hoạch","Danh từ",1],
    ["機関","きかん","Cơ quan, tổ chức, đầu máy","Danh từ",1],
    ["期間","きかん","Khoảng thời gian, kỳ hạn","Danh từ",1],
    ["企業","きぎょう","Doanh nghiệp, công ty kinh doanh","Danh từ",1],
    ["効く","きく","Có tác dụng, hiệu nghiệm (thuốc)","Động từ",1],
    ["記事","きじ","Bài báo, phóng sự","Danh từ",1],
    ["技師","ぎし","Kỹ sư công nghệ","Danh từ",1],
    ["記者","きしゃ","Ký giả, nhà báo","Danh từ",1],
    ["傷","きず","Vết thương, vết xước đồ vật","Danh từ",1],
    ["期待","きたい","Kỳ vọng, trông đợi","Danh từ",1],
    ["気体","きたい","Thể khí, chất khí","Danh từ",2],
    ["帰宅","きたく","Việc trở về nhà sau giờ làm","Danh từ",1],
    ["貴重","きちょう","Quý giá, trân quý","Tính từ -na",1],
    ["気付く","きづく","Nhận ra phát hiện điều gì","Động từ",1],
    ["気に入る","きにいる","Vừa lòng ưng ý","Động từ",1],
    ["記入","きにゅう","Điền thông tin vào phiếu","Danh từ",1],
    ["記念","きねん","Kỷ niệm, tưởng niệm","Danh từ",1],
    ["機能","きのう","Chức năng tính năng máy móc","Danh từ",1],
    ["気の毒","きのどく","Tội nghiệp, đáng tiếc xót xa","Tính từ -na",1],
    ["基本","きほん","Cơ bản, nền tảng","Danh từ",1],
    ["寄付","きふ","Quyên góp từ thiện ủng hộ","Danh từ",1],
    ["希望","きぼう","Hy vọng mong muốn","Danh từ",1],
    ["義務","ぎむ","Nghĩa vụ trách nhiệm","Danh từ",1],
    ["疑問","ぎもん","Nghi vấn hoài nghi","Danh từ",1],
    ["客席","きゃくせき","Hàng ghế khán giả","Danh từ",1],
    ["逆","ぎゃく","Ngược lại, trái chiều","Tính từ -na",1],
    ["急激","きゅうげき","Đột biến, nhanh chóng mặt","Tính từ -na",1],
    ["吸収","きゅうしゅう","Hấp thu dinh dưỡng/tiếp thu","Danh từ",1],
    ["救助","きゅうじょ","Cứu trợ, cứu nạn khẩn cấp","Danh từ",1],
    ["急速","きゅうそく","Nhanh chóng thần tốc","Tính từ -na",1],
    ["急増","きゅうぞう","Tăng vọt đột ngột","Danh từ",1],
    ["給料","きゅうりょう","Tiền lương tháng","Danh từ",1],
    ["器用","きよう","Khéo tay tinh tế","Tính từ -na",1],
    ["教科書","きょうかしょ","Sách giáo khoa trường học","Danh từ",1],
    ["競技","きょうぎ","Cuộc thi đấu thể thao","Danh từ",1],
    ["教授","きょうじゅ","Giáo sư viện sĩ","Danh từ",1],
    ["強調","きょうちょう","Nhấn mạnh điểm cốt yếu","Danh từ",1],
    ["共通","きょうつう","Điểm chung tương đồng","Danh từ",1],
    ["共同","きょうどう","Hợp tác cộng đồng chung sức","Danh từ",1],
    ["恐怖","きょうふ","Nỗi sợ hãi khiếp đảm","Danh từ",1],
    ["協力","きょうりょく","Hợp tác tương trợ","Danh từ",1],
    ["強力","きょうりょく","Mạnh mẽ có uy lực lớn","Tính từ -na",1],
    ["許可","きょか","Sự cho phép, cấp giấy phép","Danh từ",1],
    ["巨大","きょだい","Khổng lồ to lớn phi thường","Tính từ -na",1]
  ],

  N2: [
    ["開拓","かいたく","Khai phá vùng đất mới, mở thị trường","Danh từ",1],
    ["改定","かいてい","Sửa đổi biểu phí, quy định","Danh từ",1],
    ["改訂","かいてい","Sửa chữa tái bản sách","Danh từ",1],
    ["該当","がいとう","Tương ứng phù hợp tiêu chí","Danh từ",1],
    ["概念","がいねん","Khái niệm tư tưởng","Danh từ",1],
    ["概略","がいりゃく","Khái lược tóm tắt sơ bộ","Danh từ",1],
    ["開発","かいはつ","Phát triển phần mềm/tài nguyên","Danh từ",1],
    ["介抱","かいほう","Chăm sóc bệnh nhân hồi sức","Danh từ",2],
    ["解約","かいやく","Hủy bỏ hợp đồng giao ước","Danh từ",1],
    ["外来","がいらい","Ngoại trú, nguồn gốc từ nước ngoài","Danh từ",1],
    ["概論","がいろん","Khái luận bài giảng tổng quan","Danh từ",2],
    ["省みる","かえりみる","Tự phản tỉnh soi xét lỗi sai","Động từ",1],
    ["顧みる","かえりみる","Nhìn lại quá khứ, đoái hoài","Động từ",1],
    ["掲げる","かかげる","Giương cao ngọn cờ mục tiêu","Động từ",1],
    ["踵","かかと","Gót chân","Danh từ",2],
    ["書き取る","かきとる","Nghe chính tả chép lại","Động từ",1],
    ["垣根","かきね","Hàng rào ngăn cách","Danh từ",2],
    ["限る","かぎる","Giới hạn duy nhất tốt nhất","Động từ",1],
    ["掻く","かく","Gãi ngứa, toát mồ hôi hột","Động từ",1],
    ["嗅ぐ","かぐ","Ngửi mùi hương","Động từ",1],
    ["格差","かくさ","Chênh lệch khoảng cách giàu nghèo","Danh từ",1],
    ["拡散","かくさん","Khuếch tán lan truyền tin đồn","Danh từ",1],
    ["各種","かくしゅ","Các loại đa dạng khác nhau","Danh từ",1],
    ["隔週","かくしゅう","Cách tuần một lần","Danh từ",2],
    ["確信","かくしん","Lòng tin chắc chắn không nghi ngờ","Danh từ",1],
    ["革新","かくしん","Cách tân đổi mới sáng tạo","Danh từ",1],
    ["確定","かくてい","Xác định chốt lại kết quả","Danh từ",1],
    ["獲得","かくとく","Gặt hái giành được thắng lợi","Danh từ",1],
    ["確保","かくほ","Bảo đảm giữ chắc nguồn cung","Danh từ",1],
    ["革命","かくめい","Cuộc cách mạng lịch sử","Danh từ",1],
    ["確立","かくりつ","Xác lập thiết lập vững vàng","Danh từ",1],
    ["賭ける","かける","Đánh cược mạo hiểm","Động từ",1],
    ["駆ける","かける","Chạy vụt qua, phóng nhanh","Động từ",2],
    ["嵩張る","かさばる","Cồng kềnh chiếm diện tích","Động từ",2],
    ["嵩む","かさむ","Chồng chất tăng vọt (chi phí)","Động từ",2],
    ["風上","かざかみ","Phía đầu ngọn gió","Danh từ",3],
    ["微か","かすか","Thoang thoảng mờ nhạt mong manh","Tính từ -na",1],
    ["かすむ","かすむ","Mờ mịt tầm nhìn mây mù","Động từ",2],
    ["擦る","かする","Quẹt sượt qua da","Động từ",2],
    ["火星","かせい","Sao Hỏa","Danh từ",2],
    ["化石","かせき","Hóa thạch cổ sinh vật","Danh từ",1],
    ["河川","かせん","Hệ thống sông ngòi tự nhiên","Danh từ",1],
    ["過多","かた","Quá nhiều dư thừa thái quá","Danh từ",1],
    ["課題","かだい","Đề tài bài toán cần giải quyết","Danh từ",1]
  ],

  N1: [
    ["恩赦","おんしゃ","Ân xá khoan hồng tù nhân","Danh từ",2],
    ["温情","おんじょう","Tấm lòng ấm áp nhân hậu","Danh từ",1],
    ["穏便","おんびん","Giải quyết êm thấm hòa bình","Tính từ -na",1],
    ["改悪","かいあく","Sửa đổi làm cho tệ hại hơn","Danh từ",1],
    ["改竄","かいざん","Đục khoét giả mạo số liệu tài liệu","Danh từ",1],
    ["改修","かいしゅう","Tu sửa nâng cấp cầu đường","Danh từ",1],
    ["会心","かいしん","Đắc ý tâm đắc thỏa lòng mong ước","Danh từ",1],
    ["快諾","かいだく","Vui vẻ sẵn lòng đồng ý ngay","Danh từ",1],
    ["壊滅","かいめつ","Bị hủy diệt xóa sổ sạch sành sanh","Danh từ",1],
    ["怪異","かいい","Kỳ dị quái đản ma quái","Tính từ -na",2],
    ["海峡","かいきょう","Eo biển hiểm trở","Danh từ",2],
    ["回顧","かいこ","Hồi tưởng nhớ lại chuyện xưa","Danh từ",1],
    ["介在","かいざい","Nằm ở giữa can thiệp trung gian","Danh từ",1],
    ["開拓者","かいたくしゃ","Người khai hoang mở cõi","Danh từ",1],
    ["会得","かいとく","Lĩnh hội thấu hiểu sâu sắc","Danh từ",1],
    ["皆無","かいむ","Hoàn toàn không có mảy may nào","Danh từ",1],
    ["開闢","かいびゃく","Khai thiên lập địa mở ra kỷ nguyên","Danh từ",3],
    ["概括","がいかつ","Khái quát tóm gọn luận điểm","Danh từ",1],
    ["街頭","がいとう","Đường phố nơi công cộng","Danh từ",1],
    ["該当者","がいとうしゃ","Người đúng tiêu chuẩn hợp lệ","Danh từ",1],
    ["外部","がいぶ","Bên ngoài ngoại giới","Danh từ",1],
    ["頑迷","がんめい","Ngoan cố bảo thủ u mê","Tính từ -na",2],
    ["感銘","かんめい","Cảm kích khắc cốt ghi tâm","Danh từ",1],
    ["官僚","かんりょう","Quan chức quan liêu nhà nước","Danh từ",1],
    ["気概","きがい","Khí khái ý chí kiên cường hào kiệt","Danh từ",1],
    ["企画力","きかくりょく","Năng lực lên kế hoạch sáng tạo","Danh từ",1],
    ["帰結","きけつ","Kết cục tất yếu quy về một mối","Danh từ",1],
    ["危急","ききゅう","Nguy cấp nghìn cân treo sợi tóc","Danh từ",1],
    ["寄稿","きこう","Viết bài cộng tác gửi báo","Danh từ",2],
    ["希釈","きしゃく","Pha loãng dung dịch","Danh từ",2],
    ["奇特","きとく","Hiếm có phi thường đáng khen ngợi","Tính từ -na",2],
    ["糾弾","きゅうだん","Lên án buộc tội trừng phạt công khai","Danh từ",1],
    ["急務","きゅうむ","Nhiệm vụ khẩn cấp hàng đầu","Danh từ",1],
    ["狂気","きょうき","Cơn điên loạn cuồng loạn","Danh từ",1],
    ["矜持","きょうじ / きんじ","Lòng kiêu hãnh lòng tự tôn","Danh từ",1],
    ["恐喝","きょうかつ","Tống tiền đe dọa cưỡng đoạt","Danh từ",1],
    ["虚構","きょこう","Hư cấu tưởng tượng không có thật","Danh từ",1],
    ["拒絶反応","きょぜつはんのう","Phản ứng đào thải chống đối","Danh từ",1],
    ["寄与","きよ","Sự đóng góp cống hiến lớn lao","Danh từ",1]
  ]
};
