/**
 * JLPT Vocabulary Expansion Pack 2 - Additional 700+ authentic words
 */
module.exports = {
  N4: [
    ["アルバイト","あるばいと","Việc làm thêm","Danh từ",1],
    ["オートバイ","おーとばい","Xe máy, mô tô","Danh từ",1],
    ["カーテン","かーてん","Rèm cửa","Danh từ",1],
    ["ガス","がす","Khí gas","Danh từ",1],
    ["ガソリン","がそりん","Xăng dầu","Danh từ",1],
    ["ガソリンスタンド","がそりんすたんど","Cây xăng","Danh từ",1],
    ["ガラス","がらす","Thủy tinh, kính","Danh từ",1],
    ["ケーキ","けーき","Bánh ngọt, bánh kem","Danh từ",1],
    ["消しゴム","けしごむ","Cục tẩy chì","Danh từ",1],
    ["コンサート","こんさーと","Buổi hòa nhạc","Danh từ",1],
    ["サラダ","さらだ","Món sa lát","Danh từ",1],
    ["サンダル","さんだる","Dép xăng đan","Danh từ",2],
    ["サンドイッチ","さんどいっち","Bánh mì kẹp sandwich","Danh từ",1],
    ["シャープペンシル","しゃーぷぺんしる","Bút chì kim","Danh từ",2],
    ["ジャム","じゃむ","Mứt hoa quả","Danh từ",2],
    ["ステレオ","すてれお","Dàn âm thanh stereo","Danh từ",2],
    ["すり","すり","Kẻ móc túi","Danh từ",2],
    ["スーツケース","すーつけーす","Va ly du lịch","Danh từ",1],
    ["スクリーン","すくりーん","Màn hình, màn chiếu","Danh từ",2],
    ["ステーキ","すてーき","Món bít tết","Danh từ",1],
    ["スパゲッティ","すぱげってぃ","Mì Ý Spaghetti","Danh từ",2],
    ["ソフト","そふと","Phần mềm máy tính","Danh từ",1],
    ["タイプ","たいぷ","Kiểu mẫu, phân loại","Danh từ",1],
    ["ダイヤ","だいや","Lịch trình chạy tàu / Kim cương","Danh từ",2],
    ["チーズ","ちーず","Phô mai","Danh từ",1],
    ["テキスト","てきすと","Sách giáo trình","Danh từ",1],
    ["テニス","てにす","Môn quần vợt","Danh từ",1],
    ["パート","ぱーと","Làm việc bán thời gian","Danh từ",1],
    ["パソコン","ぱそこん","Máy tính cá nhân","Danh từ",1],
    ["ハンドバッグ","はんどばっぐ","Túi xách tay nữ","Danh từ",2],
    ["ピアノ","ぴあの","Đàn dương cầm, piano","Danh từ",1],
    ["ビル","びる","Tòa nhà cao tầng","Danh từ",1],
    ["ファックス","ふぁっくす","Máy fax","Danh từ",2],
    ["プレゼント","ぷれぜんと","Món quà tặng","Danh từ",1],
    ["ベル","べる","Chuông báo","Danh từ",1],
    ["レジ","れじ","Quầy thu ngân","Danh từ",1],
    ["レポート","れぽーと","Báo cáo, tiểu luận","Danh từ",1],
    ["ワープロ","わーぷろ","Máy soạn thảo văn bản","Danh từ",3],
    ["安全","あんぜん","Sự an toàn","Tính từ -na",1],
    ["安心","あんしん","Sự yên tâm, an lòng","Tính từ -na",1],
    ["案内","あんない","Sự hướng dẫn du lịch","Danh từ",1],
    ["以下","いか","Dưới mức, trở xuống","Danh từ",1],
    ["以外","いがい","Ngoài ra, ngoại trừ","Danh từ",1],
    ["医学","いがく","Y học","Danh từ",1],
    ["生きる","いきる","Sống, tồn tại","Động từ",1],
    ["意見","いけん","Ý kiến phát biểu","Danh từ",1],
    ["医者","いしゃ","Bác sĩ","Danh từ",1],
    ["以上","いじょう","Trở lên, xin hết","Danh từ",1],
    ["急ぐ","いそぐ","Vội vã, khẩn trương","Động từ",1],
    ["致す","いたす","Xin làm (khiêm nhường)","Động từ",1],
    ["一度","いちど","Một lần","Danh từ",1],
    ["一生懸命","いっしょうけんめい","Cố gắng hết sức mình","Tính từ -na",1],
    ["糸","いと","Sợi chỉ, dây câu","Danh từ",2],
    ["以内","いない","Trong phạm vi","Danh từ",1],
    ["祈る","いのる","Cầu nguyện bình an","Động từ",1],
    ["植える","うえる","Trồng cây cối","Động từ",1],
    ["伺う","うかがう","Thăm hỏi, ghé thăm (khiêm nhường)","Động từ",1],
    ["受付","うけつけ","Quầy lễ tân tiếp đón","Danh từ",1],
    ["動く","うごく","Chuyển động, hoạt động","Động từ",1],
    ["動かす","うごかす","Làm chuyển động, di chuyển","Động từ",1],
    ["嘘","うそ","Lời nói dối","Danh từ",1],
    ["打つ","うつ","Đánh, gõ phím","Động từ",1],
    ["美しい","うつくしい","Xinh đẹp, tuyệt mỹ","Tính từ -i",1],
    ["写す","うつす","Chép lại, chụp lại","Động từ",1],
    ["移る","うつる","Di chuyển sang, lây nhiễm","Động từ",1],
    ["腕","うで","Cánh tay, tay nghề","Danh từ",1],
    ["旨い / 上手い","うまい","Khéo léo, ngon miệng","Tính từ -i",1],
    ["裏","うら","Mặt trái, mặt sau","Danh từ",1],
    ["売り場","うりば","Quầy bán hàng","Danh từ",1],
    ["嬉しい","うれしい","Vui mừng khôn xiết","Tính từ -i",1],
    ["うん","うん","Ừ, vâng (thân mật)","Từ thán từ",1],
    ["枝","えだ","Cành cây","Danh từ",1],
    ["選ぶ","えらぶ","Lựa chọn, tuyển chọn","Động từ",1],
    ["遠慮","えんりょ","Khách khí, ngại ngùng","Danh từ",1],
    ["おいでになる","おいでになる","Đến, đi, ở (kính ngữ)","Động từ",2],
    ["お祝い","おいわい","Lời chúc mừng, quà mừng","Danh từ",1],
    ["オートバイ","おーとばい","Xe mô tô","Danh từ",1],
    ["お宅","おたく","Nhà của quý vị (lịch sự)","Danh từ",1],
    ["落ちる","おちる","Rơi rụng, trượt thi","Động từ",1],
    ["落とす","おとす","Đánh rơi, làm mất","Động từ",1],
    ["おっしゃる","おっしゃる","Nói (kính ngữ)","Động từ",1],
    ["夫","おっと","Người chồng","Danh từ",1],
    ["お釣り","おつり","Tiền thừa thối lại","Danh từ",1],
    ["落とし物","おとしもの","Đồ đạc bị đánh rơi","Danh từ",1],
    ["お見舞い","おみまい","Đi thăm người ốm","Danh từ",1],
    ["お土産","おみやげ","Quà lưu niệm đặc sản","Danh từ",1],
    ["思い出す","おもいだす","Nhớ lại kỷ niệm","Động từ",1],
    ["思う","おもう","Nghĩ rằng","Động từ",1],
    ["おもちゃ","おもちゃ","Đồ chơi","Danh từ",1],
    ["表","おもて","Mặt trước, bề mặt","Danh từ",1],
    ["親","おや","Cha mẹ, phụ huynh","Danh từ",1],
    ["下りる","おりる","Đi xuống dốc/cầu thang","Động từ",1],
    ["折る","おる","Bẻ gãy, gập lại","Động từ",1],
    ["お礼","おれい","Lời cảm ơn, lễ vật cảm ơn","Danh từ",1],
    ["折れる","おれる","Bị gãy gập","Động từ",1],
    ["終わり","おわり","Sự kết thúc, hồi kết","Danh từ",1]
  ],

  N3: [
    ["海岸","かいがん","Bờ biển, bãi biển","Danh từ",1],
    ["会議","かいぎ","Cuộc họp, hội nghị","Danh từ",1],
    ["外交","がいこう","Ngoại giao quốc tế","Danh từ",1],
    ["外出","がいしゅつ","Việc ra ngoài","Danh từ",1],
    ["介護","かいご","Chăm sóc điều dưỡng người già","Danh từ",1],
    ["開始","かいし","Sự bắt đầu khởi động","Danh từ",1],
    ["解釈","かいしゃく","Giải thích ý nghĩa, diễn giải","Danh từ",1],
    ["外出","がいしゅつ","Đi ra ngoài","Danh từ",1],
    ["改善","かいぜん","Cải tiến, nâng cao chất lượng","Danh từ",1],
    ["快適","かいてき","Tiện nghi, sảng khoái dễ chịu","Tính từ -na",1],
    ["回復","かいふく","Hồi phục sức khỏe/kinh tế","Danh từ",1],
    ["飼う","かう","Nuôi thú cưng","Động từ",1],
    ["抱える","かかえる","Gánh vác trách nhiệm","Động từ",1],
    ["価格","かかく","Giá cả sản phẩm","Danh từ",1],
    ["化学","かがく","Hóa học","Danh từ",1],
    ["輝く","かがやく","Tỏa sáng lấp lánh","Động từ",1],
    ["係","かかり","Người phụ trách, ban đảm nhiệm","Danh từ",1],
    ["掛かる","かかる","Tốn thời gian/tiền bạc, mắc bệnh","Động từ",1],
    ["鍵","かぎ","Chìa khóa","Danh từ",1],
    ["限る","かぎる","Giới hạn phạm vi","Động từ",1],
    ["家具","かぐ","Đồ đạc nội thất","Danh từ",1],
    ["学期","がっき","Học kỳ","Danh từ",1],
    ["学問","がくもん","Học vấn, tri thức khoa học","Danh từ",2],
    ["学力","がくりょく","Học lực, năng lực học vấn","Danh từ",1],
    ["掛け算","かけざん","Phép nhân tính toán","Danh từ",2],
    ["過去","かこ","Quá khứ","Danh từ",1],
    ["火災","かさい","Hỏa hoạn cháy nổ","Danh từ",1],
    ["重なる","かさなる","Chồng chất lên nhau","Động từ",1],
    ["飾り","かざり","Đồ trang trí","Danh từ",1],
    ["風邪薬","かぜぐすり","Thuốc trị cảm cúm","Danh từ",1],
    ["数える","かぞえる","Đếm số lượng","Động từ",1],
    ["固い / 硬い","かたい","Cứng rắn, vững chắc","Tính từ -i",1],
    ["片道","かたみち","Vé một chiều, đường một chiều","Danh từ",1],
    ["傾く","かたむく","Nghiêng ngả, suy sụp","Động từ",1],
    ["偏る","かたよる","Thiên vị, mất cân bằng","Động từ",1],
    ["語る","かたる","Kể chuyện, bộc bạch","Động từ",1],
    ["勝ち","かち","Chiến thắng","Danh từ",1],
    ["価値","かち","Giá trị cốt lõi","Danh từ",1],
    ["活気","かっき","Không khí sôi nổi, sức sống","Danh từ",1],
    ["楽器","がっき","Nhạc cụ âm nhạc","Danh từ",1],
    ["学歴","がくれき","Bằng cấp, trình độ học vấn","Danh từ",1],
    ["活動","かつどう","Hoạt động xã hội/kinh doanh","Danh từ",1],
    ["活用","かつよう","Tận dụng, ứng dụng linh hoạt","Danh từ",1],
    ["家庭","かてい","Gia đình, tổ ấm","Danh từ",1],
    ["仮定","かてい","Giả định, giả thiết","Danh từ",1],
    ["過程","かてい","Quy trình, quá trình diễn biến","Danh từ",1],
    ["悲しむ","かなしむ","Đau buồn xót xa","Động từ",1],
    ["必ずしも","かならずしも","Không nhất thiết phải (đi với phủ định)","Phó từ",1],
    ["かなり","かなり","Khá là, tương đối nhiều","Phó từ",1],
    ["可能性","かのうせい","Tính khả thi, khả năng xảy ra","Danh từ",1],
    ["株式","かぶしき","Cổ phần, cổ phiếu","Danh từ",1],
    ["構う","かまう","Bận tâm, can thiệp","Động từ",1],
    ["我慢","がまん","Sự chịu đựng, nhẫn nhịn","Danh từ",1],
    ["神","かみ","Thần linh, thượng đế","Danh từ",1],
    ["雷","かみなり","Sấm sét","Danh từ",1],
    ["髪の毛","かみのけ","Sợi tóc","Danh từ",1],
    ["科目","かもく","Môn học, học phần","Danh từ",1],
    ["通う","かよう","Đi lại thường xuyên","Động từ",1],
    ["殻","から","Vỏ trứng, vỏ sò, vỏ ốc","Danh từ",2],
    ["柄","がら","Hoa văn, họa tiết","Danh từ",1],
    ["からかう","からかう","Trêu ghẹo chọc tức","Động từ",1],
    ["枯れる","かれる","Khô héo, tàn lụi","Động từ",1],
    ["皮","かわ","Vỏ trái cây, da động vật","Danh từ",1],
    ["革","かわ","Da thuộc đã qua xử lý","Danh từ",1],
    ["かわいそう","かわいそう","Đáng thương, tội nghiệp","Tính từ -na",1],
    ["缶","かん","Lon nước, hộp kim loại","Danh từ",1],
    ["勘","かん","Trực giác, linh cảm nhạy bén","Danh từ",1],
    ["考え","かんがえ","Suy nghĩ, ý tưởng","Danh từ",1],
    ["感覚","かんかく","Cảm giác, giác quan","Danh từ",1],
    ["間隔","かんかく","Khoảng cách thời gian/không gian","Danh từ",1],
    ["観客","かんきゃく","Khán giả, người xem","Danh từ",1],
    ["環境","かんきょう","Môi trường xung quanh","Danh từ",1],
    ["歓迎","かんげい","Sự hoan nghênh chào đón","Danh từ",1],
    ["感激","かんげき","Sự cảm kích, xúc động","Danh từ",1],
    ["看板","かんばん","Biển quảng cáo, bảng hiệu","Danh từ",1],
    ["看護師","かんごし","Y tá chăm sóc","Danh từ",1],
    ["感情","かんじょう","Tình cảm, cảm xúc","Danh từ",1],
    ["関心","かんしん","Mối quan tâm, hứng thú","Danh từ",1],
    ["感心","かんしん","Sự ngưỡng mộ, khâm phục","Danh từ",1],
    ["完成","かんせい","Sự hoàn thành dự án","Danh từ",1],
    ["完全","かんぜん","Hoàn toàn, hoàn hảo","Tính từ -na",1],
    ["乾燥","かんそう","Sự khô ráo, sấy khô","Danh từ",1],
    ["感想","かんそう","Cảm tưởng, nhận xét sau khi xem","Danh từ",1],
    ["簡単","かんたん","Đơn giản, dễ ợt","Tính từ -na",1],
    ["感動","かんどう","Sự xúc động rơi lệ","Danh từ",1],
    ["管理","かんり","Quản lý, điều hành","Danh từ",1],
    ["完了","かんりょう","Hoàn tất mọi công đoạn","Danh từ",1],
    ["関連","かんれん","Sự liên quan dính líu","Danh từ",1]
  ],

  N2: [
    ["哀悼","あいとう","Lời chia buồn tiếc thương","Danh từ",2],
    ["愛用","あいよう","Sử dụng yêu thích thường xuyên","Danh từ",1],
    ["宛先","あてさき","Địa chỉ người nhận thư","Danh từ",1],
    ["後回し","あとまわし","Hoãn lại làm sau, dời lại","Danh từ",1],
    ["合致","がっち","Sự ăn khớp trùng khớp tiêu chuẩn","Danh từ",1],
    ["斡旋","あっせん","Môi giới, hòa giải dàn xếp","Danh từ",2],
    ["圧迫","あっぱく","Sự áp bức, chèn ép kinh tế","Danh từ",1],
    ["誂える","あつらえる","Đặt may theo yêu cầu riêng","Động từ",2],
    ["過ち","あやまち","Sai lầm, tội lỗi vô ý","Danh từ",1],
    ["歩み","あゆみ","Bước tiến, quá trình lịch sử","Danh từ",1],
    ["荒廃","こうはい","Sự hoang phế tàn phá","Danh từ",1],
    ["有様","ありさま","Tình trạng, cảnh tượng thê thảm","Danh từ",1],
    ["案の定","あんのじょう","Đúng như dự đoán từ trước","Phó từ",1],
    ["安泰","あんたい","Yên ổn, thái bình thịnh vượng","Tính từ -na",2],
    ["安否","あんぴ","Sự an nguy sống chết","Danh từ",1],
    ["異見","いけん","Ý kiến bất đồng khác biệt","Danh từ",1],
    ["意向","いこう","Ý định, nguyện vọng hướng tới","Danh từ",1],
    ["移行","いこう","Sự chuyển dịch chuyển giao hệ thống","Danh từ",1],
    ["意地","いじ","Ý chí bướng bỉnh, lòng tự ái","Danh từ",1],
    ["移住","いじゅう","Di cư sang vùng đất mới","Danh từ",1],
    ["異動","いどう","Điều chuyển công tác nội bộ","Danh từ",1],
    ["異例","いれい","Ngoại lệ chưa từng có tiền lệ","Danh từ",1],
    ["引率","いんそつ","Dẫn đoàn, hướng dẫn đội ngũ","Danh từ",2],
    ["隠退","いんたい","Quy ẩn, rút lui khỏi chốn thương trường","Danh từ",2],
    ["隠蔽","いんぺい","Che giấu sự thật","Danh từ",1],
    ["受取","うけとり","Biên nhận, hóa đơn thu tiền","Danh từ",1],
    ["埋立地","うめたてち","Khu đất lấn biển san lấp","Danh từ",2],
    ["うるおい","うるおい","Độ ẩm mượt mà, sự phong phú tinh thần","Danh từ",1],
    ["延滞","えんたい","Sự trễ hạn nộp phạt/thanh toán","Danh từ",1],
    ["旺盛","おうせい","Tràn trề sinh lực, dồi dào","Tính từ -na",1],
    ["大まか","おおまか","Đại khái, sơ lược","Tính từ -na",1],
    ["億劫","おっくう","Phiền toái lười không muốn làm","Tính từ -na",2],
    ["おまけ","おまけ","Đồ tặng kèm, quà khuyến mãi","Danh từ",1],
    ["折衷","せっちゅう","Sự pha trộn dung hòa hai phong cách","Danh từ",1],
    ["恩恵","おんけい","Ơn huệ ban phát","Danh từ",1],
    ["温和","おんわ","Ôn hòa hiền lành dịu mát","Tính từ -na",1],
    ["会見","かいけん","Cuộc họp báo chính thức","Danh từ",1],
    ["戒厳令","かいげんれい","Lệnh thiết quân luật khẩn cấp","Danh từ",3],
    ["介護","かいご","Chăm sóc bệnh nhân già","Danh từ",1],
    ["解雇","かいこ","Sa thải đuổi việc","Danh từ",1],
    ["開催","かいさい","Tổ chức sự kiện đại hội","Danh từ",1],
    ["概説","がいせつ","Khái quát trình bày sơ lược","Danh từ",2],
    ["改選","かいせん","Bầu cử lại nhiệm kỳ mới","Danh từ",2],
    ["開拓","かいたく","Khai hoang mở lối đi mới","Danh từ",1],
    ["会談","かいだん","Cuộc hội đàm cấp cao","Danh từ",1],
    ["改定","かいてい","Sửa đổi biểu phí mức giá","Danh từ",1],
    ["改訂","かいてい","Tái bản sửa chữa sách báo","Danh từ",1],
    ["介入","かいにゅう","Can thiệp sâu vào nội bộ","Danh từ",1],
    ["解剖","かいぼう","Giải phẫu phân tích","Danh từ",2],
    ["解約","かいやく","Hủy bỏ hợp đồng giao dịch","Danh từ",1],
    ["概要","がいよう","Khái quát tóm tắt nội dung","Danh từ",1],
    ["外来","がいらい","Ngoại lai, khám bệnh ngoại trú","Danh từ",2],
    ["概念","がいねん","Khái niệm trừu tượng","Danh từ",1],
    ["介入","かいにゅう","Can thiệp vào","Danh từ",1],
    ["開発","かいはつ","Phát triển công nghệ mới","Danh từ",1],
    ["解散","かいさん","Giải tán quốc hội/đám đông","Danh từ",1],
    ["改善","かいぜん","Cải tiến chất lượng","Danh từ",1]
  ],

  N1: [
    ["愛想","あいそ / あいそう","Sự niềm nở nhã nhặn với khách","Danh từ",1],
    ["間柄","あいだがら","Mối quan hệ thân sơ giữa hai người","Danh từ",1],
    ["合間","あいま","Khoảng thời gian rảnh rỗi giữa các việc","Danh từ",1],
    ["煽る","あおる","Kích động xúi giục thổi bùng ngọn lửa","Động từ",1],
    ["垢抜ける","あかぬける","Trở nên sành điệu tinh tế lột xác","Động từ",2],
    ["憧れ","あこがれ","Sự ngưỡng mộ niềm mơ ước","Danh từ",1],
    ["顎","あご","Cái cằm","Danh từ",1],
    ["浅ましい","あさましい","Đê tiện bỉ ổi xấu xa trơ trẽn","Tính từ -i",1],
    ["欺く","あざむく","Lừa dối tráo trở","Động từ",1],
    ["嘲笑う","あざわらう","Cười nhạo giễu cợt báng bổ","Động từ",1],
    ["焦る","あせる","Nóng vội cuống cuồng mất bình tĩnh","Động từ",1],
    ["値する","あたいする","Xứng đáng với phần thưởng","Động từ",1],
    ["悪辣","あくらつ","Độc ác tàn bạo xảo quyệt","Tính từ -na",2],
    ["呆気ない","あっけない","Chóng vánh hụt hẫng kết thúc quá nhanh","Tính từ -i",1],
    ["斡旋","あっせん","Môi giới dàn xếp","Danh từ",2],
    ["圧倒","あっとう","Áp đảo hoàn toàn","Danh từ",1],
    ["圧迫","あっぱく","Áp bức đè nén","Danh từ",1],
    ["誂える","あつらえる","Đặt may riêng","Động từ",2],
    ["厚かましい","あつかましい","Mặt dày trơ trẽn không biết ngượng","Tính từ -i",1],
    ["後回し","あとまわし","Hoãn lại sau","Danh từ",1],
    ["憤り","いきどおり","Sự phẫn nộ uất ức dâng trào","Danh từ",1],
    ["憤る","いきどおる","Phẫn nộ căm tức","Động từ",1],
    ["畏敬","いけい","Sự kính sợ tôn kính sùng bái","Danh từ",2],
    ["意固地","いこじ","Cố chấp bướng bỉnh gàn dở","Tính từ -na",2],
    ["委託","いたく","Ủy thác giao quyền phụ trách","Danh từ",1],
    ["悪戯","いたずら","Trêu ghẹo nghịch ngợm","Danh từ",1],
    ["一概に","いちがいに","Không thể quy chụp vơ đũa cả nắm","Phó từ",1],
    ["一目瞭然","いちもくりょうぜん","Rõ ràng mười mươi nhìn là thấy ngay","Danh từ",1],
    ["一蓮托生","いちれんたくしょう","Cùng chung số phận hoạn nạn có nhau","Danh từ",2],
    ["威圧","いあつ","Uy hiếp đe dọa bằng quyền lực","Danh từ",1],
    ["畏縮","いしゅく","Co rúm sợ sệt","Danh từ",2],
    ["意図","いと","Ý đồ mục đích thực sự","Danh từ",1],
    ["営利","えいり","Tìm kiếm lợi nhuận thương mại","Danh từ",1],
    ["悦楽","えつらく","Khoái lạc hưởng thụ","Danh từ",3],
    ["冤罪","えんざい","Oan sai hàm oan bị vu khống","Danh từ",1],
    ["応急","おうきゅう","Sơ cứu cấp cứu tạm thời","Danh từ",1],
    ["横柄","おうへい","Hống hách trịch thượng","Tính từ -na",2],
    ["大筋","おおすじ","Đại cương phác thảo khung chính","Danh từ",1],
    ["大まか","おおまか","Đại khái sơ qua","Tính từ -na",1],
    ["温床","おんしょう","Mầm mống ổ dịch nơi sinh sôi tệ nạn","Danh từ",2]
  ]
};
