module.exports = [
  { kanji: '安', level: 'N4', meanings: ['An', 'An toàn', 'Rẻ'], onyomi: ['アン'], kunyomi: ['やす・い'] },
  { kanji: '高', level: 'N4', meanings: ['Cao', 'Đắt', 'Cao lớn'], onyomi: ['コウ'], kunyomi: ['たか・い'] },
  { kanji: '新', level: 'N4', meanings: ['Tân', 'Mới'], onyomi: ['シン'], kunyomi: ['あたら・しい', 'あら・た'] },
  { kanji: '古', level: 'N4', meanings: ['Cổ', 'Cũ'], onyomi: ['コ'], kunyomi: ['ふる・い'] },
  { kanji: '長', level: 'N4', meanings: ['Trường', 'Dài', 'Trưởng'], onyomi: ['チョウ'], kunyomi: ['なが・い'] },
  { kanji: '多', level: 'N4', meanings: ['Đa', 'Nhiều'], onyomi: ['タ'], kunyomi: ['おお・い'] },
  { kanji: '少', level: 'N4', meanings: ['Thiểu', 'Ít', 'Một chút'], onyomi: ['ショウ'], kunyomi: ['すく・ない', 'すこ・し'] },
  { kanji: '重', level: 'N4', meanings: ['Trọng', 'Nặng', 'Quan trọng'], onyomi: ['ジュウ', 'チョウ'], kunyomi: ['おも・い', 'かさ・ねる'] },
  { kanji: '軽', level: 'N4', meanings: ['Khinh', 'Nhẹ'], onyomi: ['ケイ'], kunyomi: ['かる・い'] },
  { kanji: '広', level: 'N4', meanings: ['Quảng', 'Rộng'], onyomi: ['コウ'], kunyomi: ['ひろ・い'] },
  { kanji: '近', level: 'N4', meanings: ['Cận', 'Gần'], onyomi: ['キン'], kunyomi: ['ちか・い'] },
  { kanji: '遠', level: 'N4', meanings: ['Viễn', 'Xa'], onyomi: ['エン', 'オン'], kunyomi: ['とお・い'] },
  { kanji: '悪', level: 'N4', meanings: ['Ác', 'Xấu', 'Tồi tệ'], onyomi: ['アク', 'オ'], kunyomi: ['わる・い'] },
  { kanji: '正', level: 'N4', meanings: ['Chính', 'Đúng', 'Chính xác'], onyomi: ['セイ', 'ショウ'], kunyomi: ['ただ・しい', 'まさ'] },
  { kanji: '同', level: 'N4', meanings: ['Đồng', 'Giống nhau'], onyomi: ['ドウ'], kunyomi: ['おな・じ'] },
  { kanji: '立', level: 'N4', meanings: ['Lập', 'Đứng'], onyomi: ['リツ', 'リュウ'], kunyomi: ['た・つ', 'た・てる'] },
  { kanji: '座', level: 'N4', meanings: ['Tọa', 'Ngồi', 'Chỗ ngồi'], onyomi: ['ザ'], kunyomi: ['すわ・る'] },
  { kanji: '歩', level: 'N4', meanings: ['Bộ', 'Đi bộ'], onyomi: ['ホ', 'ブ'], kunyomi: ['ある・く', 'あゆ・む'] },
  { kanji: '走', level: 'N4', meanings: ['Tẩu', 'Chạy'], onyomi: ['ソウ'], kunyomi: ['はし・る'] },
  { kanji: '起', level: 'N4', meanings: ['Khởi', 'Thức dậy', 'Xảy ra'], onyomi: ['キ'], kunyomi: ['お・きる', 'お・こす'] },
  { kanji: '寝', level: 'N4', meanings: ['Tẩm', 'Ngủ'], onyomi: ['シン'], kunyomi: ['ね・る', 'ね・かす'] },
  { kanji: '始', level: 'N4', meanings: ['Thủy', 'Bắt đầu'], onyomi: ['シ'], kunyomi: ['はじ・まる', 'はじ・める'] },
  { kanji: '終', level: 'N4', meanings: ['Chung', 'Kết thúc'], onyomi: ['シュウ'], kunyomi: ['お・わる', 'お・える'] },
  { kanji: '開', level: 'N4', meanings: ['Khai', 'Mở'], onyomi: ['カイ'], kunyomi: ['ひら・く', 'あ・く', 'あ・ける'] },
  { kanji: '閉', level: 'N4', meanings: ['Bế', 'Đóng'], onyomi: ['ヘイ'], kunyomi: ['と・じる', 'し・まる', 'し・める'] },
  { kanji: '待', level: 'N4', meanings: ['Đãi', 'Chờ đợi'], onyomi: ['タイ'], kunyomi: ['ま・つ'] },
  { kanji: '止', level: 'N4', meanings: ['Chỉ', 'Dừng lại'], onyomi: ['シ'], kunyomi: ['と・まる', 'と・める'] },
  { kanji: '入', level: 'N4', meanings: ['Nhập', 'Vào', 'Cho vào'], onyomi: ['ニュウ'], kunyomi: ['はい・る', 'い・れる'] },
  { kanji: '出', level: 'N4', meanings: ['Xuất', 'Ra', 'Lấy ra'], onyomi: ['シュツ', 'スイ'], kunyomi: ['で・る', 'だ・す'] },
  { kanji: '思', level: 'N4', meanings: ['Tư', 'Nghĩ', 'Suy nghĩ'], onyomi: ['シ'], kunyomi: ['おも・う'] },
  { kanji: '考', level: 'N4', meanings: ['Khảo', 'Suy nghĩ', 'Xem xét'], onyomi: ['コウ'], kunyomi: ['かんが・える'] },
  { kanji: '知', level: 'N4', meanings: ['Tri', 'Biết', 'Hiểu biết'], onyomi: ['チ'], kunyomi: ['し・る'] },
  { kanji: '答', level: 'N4', meanings: ['Đáp', 'Trả lời', 'Câu trả lời'], onyomi: ['トウ'], kunyomi: ['こた・える', 'こた・え'] },
  { kanji: '問', level: 'N4', meanings: ['Vấn', 'Hỏi', 'Vấn đề'], onyomi: ['モン'], kunyomi: ['と・う', 'と・い'] },
  { kanji: '題', level: 'N4', meanings: ['Đề', 'Chủ đề', 'Đề tài'], onyomi: ['ダイ'], kunyomi: [] },
  { kanji: '住', level: 'N4', meanings: ['Trú', 'Sống', 'Ở'], onyomi: ['ジュウ'], kunyomi: ['す・む', 'す・まう'] },
  { kanji: '所', level: 'N4', meanings: ['Sở', 'Nơi chốn', 'Địa điểm'], onyomi: ['ショ'], kunyomi: ['ところ'] },
  { kanji: '屋', level: 'N4', meanings: ['Ốc', 'Nhà', 'Cửa hàng'], onyomi: ['オク'], kunyomi: ['や'] },
  { kanji: '室', level: 'N4', meanings: ['Thất', 'Phòng'], onyomi: ['シツ'], kunyomi: ['むろ'] },
  { kanji: '堂', level: 'N4', meanings: ['Đường', 'Hội trường', 'Chính đường'], onyomi: ['ドウ'], kunyomi: [] },
  { kanji: '館', level: 'N4', meanings: ['Quán', 'Tòa nhà', 'Bảo tàng'], onyomi: ['カン'], kunyomi: ['やかた'] },
  { kanji: '院', level: 'N4', meanings: ['Viện', 'Bệnh viện', 'Học viện'], onyomi: ['イン'], kunyomi: [] },
  { kanji: '病', level: 'N4', meanings: ['Bệnh', 'Bệnh tật', 'Ốm'], onyomi: ['ビョウ', 'ヘイ'], kunyomi: ['や・む', 'やまい'] },
  { kanji: '医', level: 'N4', meanings: ['Y', 'Y học', 'Bác sĩ'], onyomi: ['イ'], kunyomi: [] },
  { kanji: '者', level: 'N4', meanings: ['Giả', 'Người'], onyomi: ['シャ'], kunyomi: ['もの'] },
  { kanji: '薬', level: 'N4', meanings: ['Dược', 'Thuốc'], onyomi: ['ヤク'], kunyomi: ['くすり'] },
  { kanji: '死', level: 'N4', meanings: ['Tử', 'Chết'], onyomi: ['シ'], kunyomi: ['し・ぬ'] },
  { kanji: '心', level: 'N4', meanings: ['Tâm', 'Trái tim', 'Tấm lòng'], onyomi: ['シン'], kunyomi: ['こころ'] },
  { kanji: '体', level: 'N4', meanings: ['Thể', 'Cơ thể', 'Thân thể'], onyomi: ['タイ', 'テイ'], kunyomi: ['からだ'] },
  { kanji: '頭', level: 'N4', meanings: ['Đầu', 'Cái đầu'], onyomi: ['トウ', 'ズ'], kunyomi: ['あたま', 'かしら'] },
  { kanji: '顔', level: 'N4', meanings: ['Nhan', 'Khuôn mặt'], onyomi: ['ガン'], kunyomi: ['かお'] },
  { kanji: '首', level: 'N4', meanings: ['Thủ', 'Cổ', 'Đứng đầu'], onyomi: ['シュ'], kunyomi: ['くび'] },
  { kanji: '声', level: 'N4', meanings: ['Thanh', 'Tiếng', 'Giọng nói'], onyomi: ['セイ', 'ショウ'], kunyomi: ['こえ', 'こわ'] },
  { kanji: '音', level: 'N4', meanings: ['Âm', 'Âm thanh'], onyomi: ['オン', 'イン'], kunyomi: ['おと', 'ね'] },
  { kanji: '楽', level: 'N4', meanings: ['Lạc', 'Vui vẻ', 'Âm nhạc'], onyomi: ['ラク', 'ガク'], kunyomi: ['たの・しい', 'たの・しむ'] },
  { kanji: '歌', level: 'N4', meanings: ['Ca', 'Hát', 'Bài hát'], onyomi: ['カ'], kunyomi: ['うた', 'うた・う'] },
  { kanji: '写', level: 'N4', meanings: ['Tả', 'Chụp', 'Sao chép'], onyomi: ['シャ'], kunyomi: ['うつ・す', 'うつ・る'] },
  { kanji: '真', level: 'N4', meanings: ['Chân', 'Thật', 'Chân thực'], onyomi: ['シン'], kunyomi: ['ま', 'まこと'] },
  { kanji: '旅', level: 'N4', meanings: ['Lữ', 'Du lịch', 'Chuyến đi'], onyomi: ['リョ'], kunyomi: ['たび'] },
  { kanji: '世', level: 'N4', meanings: ['Thế', 'Thế giới', 'Đời'], onyomi: ['セイ', 'セ'], kunyomi: ['よ'] },
  { kanji: '界', level: 'N4', meanings: ['Giới', 'Thế giới', 'Ranh giới'], onyomi: ['カイ'], kunyomi: [] },
  { kanji: '度', level: 'N4', meanings: ['Độ', 'Lần', 'Mức độ'], onyomi: ['ド', 'ト'], kunyomi: ['たび'] },
  { kanji: '回', level: 'N4', meanings: ['Hồi', 'Quay lại', 'Lần'], onyomi: ['カイ', 'エ'], kunyomi: ['まわ・る', 'まわ・す'] },
  { kanji: '用', level: 'N4', meanings: ['Dụng', 'Dùng', 'Sử dụng', 'Việc bận'], onyomi: ['ヨウ'], kunyomi: ['もち・いる'] },
  { kanji: '事', level: 'N4', meanings: ['Sự', 'Việc', 'Sự việc'], onyomi: ['ジ', 'ズ'], kunyomi: ['こと'] },
  { kanji: '仕', level: 'N4', meanings: ['Sĩ', 'Phục vụ', 'Làm việc'], onyomi: ['シ', 'ジ'], kunyomi: ['つか・える'] },
  { kanji: '使', level: 'N4', meanings: ['Sử', 'Dùng', 'Sử dụng'], onyomi: ['シ'], kunyomi: ['つか・う'] },
  { kanji: '作', level: 'N4', meanings: ['Tác', 'Làm', 'Chế tạo'], onyomi: ['サク', 'サ'], kunyomi: ['つく・る'] },
  { kanji: '品', level: 'N4', meanings: ['Phẩm', 'Hàng hóa', 'Vật phẩm'], onyomi: ['ヒン'], kunyomi: ['しな'] },
  { kanji: '物', level: 'N4', meanings: ['Vật', 'Đồ vật'], onyomi: ['ブツ', 'モツ'], kunyomi: ['もの'] },
  { kanji: '料', level: 'N4', meanings: ['Liệu', 'Nguyên liệu', 'Phí'], onyomi: ['リョウ'], kunyomi: [] },
  { kanji: '理', level: 'N4', meanings: ['Lý', 'Lý do', 'Chữa trị', 'Xử lý'], onyomi: ['リ'], kunyomi: ['ことわり'] },
  { kanji: '飯', level: 'N4', meanings: ['Phạn', 'Cơm', 'Bữa ăn'], onyomi: ['ハン'], kunyomi: ['めし'] },
  { kanji: '牛', level: 'N4', meanings: ['Ngưu', 'Bò'], onyomi: ['ギュウ'], kunyomi: ['うし'] },
  { kanji: '鳥', level: 'N4', meanings: ['Điểu', 'Chim'], onyomi: ['チョウ'], kunyomi: ['とり'] },
  { kanji: '親', level: 'N4', meanings: ['Thân', 'Bố mẹ', 'Thân thiết'], onyomi: ['シン'], kunyomi: ['おや', 'した・しい'] },
  { kanji: '兄', level: 'N4', meanings: ['Huynh', 'Anh trai'], onyomi: ['ケイ', 'キョウ'], kunyomi: ['あに'] },
  { kanji: '弟', level: 'N4', meanings: ['Đệ', 'Em trai'], onyomi: ['テイ', 'ダイ'], kunyomi: ['おとうと'] },
  { kanji: '姉', level: 'N4', meanings: ['Tỷ', 'Chị gái'], onyomi: ['シ'], kunyomi: ['あね'] },
  { kanji: '妹', level: 'N4', meanings: ['Muội', 'Em gái'], onyomi: ['マイ'], kunyomi: ['いもうと'] },
  { kanji: '家', level: 'N4', meanings: ['Gia', 'Nhà', 'Gia đình'], onyomi: ['カ', 'ケ'], kunyomi: ['いえ', 'や'] },
  { kanji: '族', level: 'N4', meanings: ['Tộc', 'Gia tộc', 'Bộ tộc'], onyomi: ['ゾク'], kunyomi: [] },
  { kanji: '自', level: 'N4', meanings: ['Tự', 'Bản thân', 'Tự mình'], onyomi: ['ジ', 'シ'], kunyomi: ['みずか・ら'] },
  { kanji: '動', level: 'N4', meanings: ['Động', 'Chuyển động', 'Cử động'], onyomi: ['ドウ'], kunyomi: ['うご・く', 'うご・かす'] },
  { kanji: '運', level: 'N4', meanings: ['Vận', 'Vận chuyển', 'May mắn'], onyomi: ['ウン'], kunyomi: ['はこ・ぶ'] },
  { kanji: '転', level: 'N4', meanings: ['Chuyển', 'Lăn', 'Ngã', 'Chuyển biến'], onyomi: ['テン'], kunyomi: ['ころ・がる', 'ころ・ぶ'] },
  { kanji: '送', level: 'N4', meanings: ['Tống', 'Gửi', 'Tiễn'], onyomi: ['ソウ'], kunyomi: ['おく・る'] },
  { kanji: '借', level: 'N4', meanings: ['Tá', 'Mượn', 'Vay'], onyomi: ['シャク'], kunyomi: ['か・りる'] },
  { kanji: '貸', level: 'N4', meanings: ['Thải', 'Cho vay', 'Cho mượn'], onyomi: ['タイ'], kunyomi: ['か・す'] },
  { kanji: '返', level: 'N4', meanings: ['Phản', 'Trả lại'], onyomi: ['ヘン'], kunyomi: ['かえ・す', 'かえ・る'] },
  { kanji: '洗', level: 'N4', meanings: ['Tẩy', 'Rửa', 'Giặt'], onyomi: ['セン'], kunyomi: ['あら・う'] },
  { kanji: '急', level: 'N4', meanings: ['Cấp', 'Gấp', 'Vội vã'], onyomi: ['キュウ'], kunyomi: ['いそ・ぐ'] },
  { kanji: '通', level: 'N4', meanings: ['Thông', 'Đi qua', 'Thông qua'], onyomi: ['ツウ'], kunyomi: ['とお・る', 'かよ・う'] },
  { kanji: '降', level: 'N4', meanings: ['Giáng', 'Xuống xe', 'Rơi (mưa/tuyết)'], onyomi: ['コウ'], kunyomi: ['お・りる', 'ふ・る'] },
  { kanji: '着', level: 'N4', meanings: ['Trước', 'Mặc', 'Đến nơi'], onyomi: ['チャク', 'ジャク'], kunyomi: ['き・る', 'つ・く'] },
  { kanji: '海', level: 'N4', meanings: ['Hải', 'Biển'], onyomi: ['カイ'], kunyomi: ['うみ'] },
  { kanji: '池', level: 'N4', meanings: ['Trì', 'Ao hồ'], onyomi: ['チ'], kunyomi: ['いけ'] },
  { kanji: '町', level: 'N4', meanings: ['Đinh', 'Thị trấn', 'Khu phố'], onyomi: ['チョウ'], kunyomi: ['まち'] },
  { kanji: '市', level: 'N4', meanings: ['Thị', 'Thành phố', 'Chợ'], onyomi: ['シ'], kunyomi: ['いち'] },
  { kanji: '村', level: 'N4', meanings: ['Thôn', 'Làng'], onyomi: ['ソン'], kunyomi: ['むら'] },
  { kanji: '県', level: 'N4', meanings: ['Huyện', 'Tỉnh (Nhật Bản)'], onyomi: ['ケン'], kunyomi: [] },
  { kanji: '春', level: 'N4', meanings: ['Xuân', 'Mùa xuân'], onyomi: ['シュン'], kunyomi: ['はる'] },
  { kanji: '夏', level: 'N4', meanings: ['Hạ', 'Mùa hè'], onyomi: ['カ', 'ゲ'], kunyomi: ['なつ'] },
  { kanji: '秋', level: 'N4', meanings: ['Thu', 'Mùa thu'], onyomi: ['シュウ'], kunyomi: ['あき'] },
  { kanji: '冬', level: 'N4', meanings: ['Đông', 'Mùa đông'], onyomi: ['トウ'], kunyomi: ['ふゆ'] },
  { kanji: '暑', level: 'N4', meanings: ['Thử', 'Nóng (thời tiết)'], onyomi: ['ショ'], kunyomi: ['あつ・い'] },
  { kanji: '寒', level: 'N4', meanings: ['Hàn', 'Lạnh (thời tiết)'], onyomi: ['カン'], kunyomi: ['さむ・い'] },
  { kanji: '暖', level: 'N4', meanings: ['Noãn', 'Ấm áp'], onyomi: ['ダン'], kunyomi: ['あたた・かい'] },
  { kanji: '涼', level: 'N4', meanings: ['Lương', 'Mát mẻ'], onyomi: ['リョウ'], kunyomi: ['すず・しい'] },
  { kanji: '強', level: 'N4', meanings: ['Cường', 'Mạnh mẽ'], onyomi: ['キョウ', 'ゴウ'], kunyomi: ['つよ・い'] },
  { kanji: '弱', level: 'N4', meanings: ['Nhược', 'Yếu ớt'], onyomi: ['ジャク'], kunyomi: ['よわ・い'] },
  { kanji: '明', level: 'N4', meanings: ['Minh', 'Sáng', 'Rõ ràng'], onyomi: ['メイ', 'ミョウ'], kunyomi: ['あか・るい', 'あ・ける'] },
  { kanji: '暗', level: 'N4', meanings: ['Ám', 'Tối tăm'], onyomi: ['アン'], kunyomi: ['くら・い'] },
  { kanji: '有', level: 'N4', meanings: ['Hữu', 'Có', 'Tồn tại'], onyomi: ['ユウ', 'ウ'], kunyomi: ['あ・る'] },
  { kanji: '無', level: 'N4', meanings: ['Vô', 'Không có'], onyomi: ['ム', 'ブ'], kunyomi: ['な・い'] },
  { kanji: '切', level: 'N4', meanings: ['Thiết', 'Cắt', 'Hết'], onyomi: ['セツ', 'サイ'], kunyomi: ['き・る', 'き・れる'] },
  { kanji: '教', level: 'N4', meanings: ['Giáo', 'Dạy', 'Chỉ bảo'], onyomi: ['キョウ'], kunyomi: ['おし・える', 'おそ・わる'] },
  { kanji: '習', level: 'N4', meanings: ['Tập', 'Học tập', 'Luyện tập'], onyomi: ['シュウ'], kunyomi: ['なら・う'] },
  { kanji: '研', level: 'N4', meanings: ['Nghiên', 'Mài giũa', 'Nghiên cứu'], onyomi: ['ケン'], kunyomi: ['と・ぐ'] },
  { kanji: '究', level: 'N4', meanings: ['Cứu', 'Nghiên cứu sâu'], onyomi: ['キュウ'], kunyomi: ['きわ・める'] },
  { kanji: '試', level: 'N4', meanings: ['Thí', 'Thử', 'Thi cử'], onyomi: ['シ'], kunyomi: ['こころ・みる', 'ため・す'] },
  { kanji: '験', level: 'N4', meanings: ['Nghiệm', 'Kinh nghiệm', 'Thí nghiệm'], onyomi: ['ケン', 'ゲン'], kunyomi: [] },
  { kanji: '貸', level: 'N4', meanings: ['Thải', 'Cho mượn'], onyomi: ['タイ'], kunyomi: ['か・す'] },
  { kanji: '銀', level: 'N4', meanings: ['Ngân', 'Bạc', 'Ngân hàng'], onyomi: ['ギン'], kunyomi: ['しろがね'] },
  { kanji: '紙', level: 'N4', meanings: ['Chỉ', 'Giấy'], onyomi: ['シ'], kunyomi: ['かみ'] },
  { kanji: '手', level: 'N4', meanings: ['Thủ', 'Tay'], onyomi: ['シュ'], kunyomi: ['て'] },
  { kanji: '足', level: 'N4', meanings: ['Túc', 'Chân'], onyomi: ['ソク'], kunyomi: ['あし'] },
  { kanji: '員', level: 'N4', meanings: ['Viên', 'Thành viên', 'Nhân viên'], onyomi: ['イン'], kunyomi: [] },
  { kanji: '色', level: 'N4', meanings: ['Sắc', 'Màu sắc'], onyomi: ['ショク', 'シキ'], kunyomi: ['いろ'] },
  { kanji: '味', level: 'N4', meanings: ['Vị', 'Hương vị', 'Mùi vị'], onyomi: ['ミ'], kunyomi: ['あじ', 'あじ・わう'] },
  { kanji: '油', level: 'N4', meanings: ['Du', 'Dầu'], onyomi: ['ユ'], kunyomi: ['あぶら'] },
  { kanji: '洋', level: 'N4', meanings: ['Dương', 'Đại dương', 'Phương Tây'], onyomi: ['ヨウ'], kunyomi: [] },
  { kanji: '服', level: 'N4', meanings: ['Phục', 'Quần áo', 'Phục tùng'], onyomi: ['フク'], kunyomi: [] }
];
