// 214 Bộ thủ Khang Hy (Kangxi Radicals) đầy đủ từ 1 nét đến 17 nét
module.exports = [
  // 1 nét (1-6)
  { kanji: '一', level: 'Bộ Thủ', meanings: ['Bộ Nhất', 'Số một', 'Toàn bộ'], onyomi: ['イチ', 'イツ'], kunyomi: ['ひと・つ', 'ひと'] },
  { kanji: '丨', level: 'Bộ Thủ', meanings: ['Bộ Cổn', 'Nét sổ dọc', 'Đâm xuyên'], onyomi: ['コン'], kunyomi: ['ぼう'] },
  { kanji: '丶', level: 'Bộ Thủ', meanings: ['Bộ Chủ', 'Dấu chấm', 'Điểm sáng'], onyomi: ['チュ'], kunyomi: ['てん'] },
  { kanji: '丿', level: 'Bộ Thủ', meanings: ['Bộ Phiệt', 'Nét phẩy', 'Nét xiên qua trái'], onyomi: ['ヘツ'], kunyomi: ['の'] },
  { kanji: '乙', level: 'Bộ Thủ', meanings: ['Bộ Ất', 'Can chi thứ 2', 'Uốn khúc'], onyomi: ['オツ', 'イツ'], kunyomi: ['おと'] },
  { kanji: '亅', level: 'Bộ Thủ', meanings: ['Bộ Quyết', 'Nét móc lên'], onyomi: ['ケツ'], kunyomi: ['はねぼう'] },
  
  // 2 nét (7-29)
  { kanji: '二', level: 'Bộ Thủ', meanings: ['Bộ Nhị', 'Số hai'], onyomi: ['ニ'], kunyomi: ['ふた・つ'] },
  { kanji: '亠', level: 'Bộ Thủ', meanings: ['Bộ Đầu', 'Cái nắp', 'Ở trên cùng'], onyomi: ['トウ'], kunyomi: ['なべぶた'] },
  { kanji: '人', level: 'Bộ Thủ', meanings: ['Bộ Nhân', 'Con người'], onyomi: ['ジン', 'ニン'], kunyomi: ['ひと'] },
  { kanji: '亻', level: 'Bộ Thủ', meanings: ['Bộ Nhân đứng', 'Con người (biến thể đứng)'], onyomi: ['ジン'], kunyomi: ['にんべん'] },
  { kanji: '儿', level: 'Bộ Thủ', meanings: ['Bộ Nhi', 'Trẻ con', 'Người đi'], onyomi: ['ジ', 'ニ'], kunyomi: ['ひとあし'] },
  { kanji: '入', level: 'Bộ Thủ', meanings: ['Bộ Nhập', 'Đi vào', 'Thu vào'], onyomi: ['ニュウ'], kunyomi: ['はい・る', 'い・る'] },
  { kanji: '八', level: 'Bộ Thủ', meanings: ['Bộ Bát', 'Số tám', 'Tẽ ra hai bên'], onyomi: ['ハチ'], kunyomi: ['や・っつ'] },
  { kanji: '冂', level: 'Bộ Thủ', meanings: ['Bộ Quynh', 'Vùng biên cương', 'Khung bao ngoài'], onyomi: ['ケイ'], kunyomi: ['まきがまえ'] },
  { kanji: '冖', level: 'Bộ Thủ', meanings: ['Bộ Mịch', 'Khăn trùm', 'Bao phủ'], onyomi: ['ベキ'], kunyomi: ['わかんむり'] },
  { kanji: '冫', level: 'Bộ Thủ', meanings: ['Bộ Băng', 'Băng tuyết', 'Lạnh giá'], onyomi: ['ヒョウ'], kunyomi: ['にすい'] },
  { kanji: '几', level: 'Bộ Thủ', meanings: ['Bộ Kỷ', 'Cái ghế dựa', 'Cái bàn nhỏ'], onyomi: ['キ'], kunyomi: ['つくえ'] },
  { kanji: '凵', level: 'Bộ Thủ', meanings: ['Bộ Khảm', 'Hố sâu', 'Há miệng'], onyomi: ['カン'], kunyomi: ['うけばこ'] },
  { kanji: '刀', level: 'Bộ Thủ', meanings: ['Bộ Đao', 'Con dao', 'Cây kiếm'], onyomi: ['トウ'], kunyomi: ['かたな'] },
  { kanji: '刂', level: 'Bộ Thủ', meanings: ['Bộ Đao đứng', 'Con dao (biến thể đứng)'], onyomi: ['トウ'], kunyomi: ['りっとう'] },
  { kanji: '力', level: 'Bộ Thủ', meanings: ['Bộ Lực', 'Sức mạnh', 'Nỗ lực'], onyomi: ['リョク', 'リキ'], kunyomi: ['ちから'] },
  { kanji: '勹', level: 'Bộ Thủ', meanings: ['Bộ Bao', 'Bao bọc', 'Ôm lấy'], onyomi: ['ホウ'], kunyomi: ['つつみがまえ'] },
  { kanji: '匕', level: 'Bộ Thủ', meanings: ['Bộ Chủy', 'Cái thìa', 'Cái muỗng'], onyomi: ['ヒ'], kunyomi: ['さじ'] },
  { kanji: '匚', level: 'Bộ Thủ', meanings: ['Bộ Phương', 'Cái hộp đựng đồ'], onyomi: ['ホウ'], kunyomi: ['はこがまえ'] },
  { kanji: '匸', level: 'Bộ Thủ', meanings: ['Bộ Hệ', 'Che đậy', 'Cất giấu'], onyomi: ['ケイ'], kunyomi: ['かくしがまえ'] },
  { kanji: '十', level: 'Bộ Thủ', meanings: ['Bộ Thập', 'Số mười', 'Hoàn thiện'], onyomi: ['ジュウ'], kunyomi: ['とお'] },
  { kanji: '卜', level: 'Bộ Thủ', meanings: ['Bộ Bặc', 'Bói toán', 'Xem bói'], onyomi: ['ボク'], kunyomi: ['うらな・う'] },
  { kanji: '卩', level: 'Bộ Thủ', meanings: ['Bộ Tiết', 'Khớp xương', 'Con dấu'], onyomi: ['セツ'], kunyomi: ['ふしづくり'] },
  { kanji: '厂', level: 'Bộ Thủ', meanings: ['Bộ Hán', 'Vách núi dốc'], onyomi: ['カン'], kunyomi: ['がんだれ'] },
  { kanji: '厶', level: 'Bộ Thủ', meanings: ['Bộ Tư', 'Riêng tư', 'Cá nhân'], onyomi: ['シ'], kunyomi: ['む'] },
  { kanji: '又', level: 'Bộ Thủ', meanings: ['Bộ Hựu', 'Lại nữa', 'Cánh tay phải'], onyomi: ['ユウ'], kunyomi: ['また'] },

  // 3 nét (30-60)
  { kanji: '口', level: 'Bộ Thủ', meanings: ['Bộ Khẩu', 'Cái miệng', 'Cửa ngõ'], onyomi: ['コウ', 'ク'], kunyomi: ['くち'] },
  { kanji: '囗', level: 'Bộ Thủ', meanings: ['Bộ Vi', 'Vây quanh', 'Bao bọc tứ phía'], onyomi: ['イ'], kunyomi: ['くにがまえ'] },
  { kanji: '土', level: 'Bộ Thủ', meanings: ['Bộ Thổ', 'Đất đai', 'Thổ nhưỡng'], onyomi: ['ド', 'ト'], kunyomi: ['つち'] },
  { kanji: '士', level: 'Bộ Thủ', meanings: ['Bộ Sĩ', 'Kẻ sĩ', 'Quan lại', 'Người có học'], onyomi: ['シ'], kunyomi: ['さむらい'] },
  { kanji: '夂', level: 'Bộ Thủ', meanings: ['Bộ Trĩ', 'Đi chậm chạp ở phía sau'], onyomi: ['チ'], kunyomi: ['ふゆがしら'] },
  { kanji: '夊', level: 'Bộ Thủ', meanings: ['Bộ Tuy', 'Đi chậm rãi'], onyomi: ['スイ'], kunyomi: ['すいにょう'] },
  { kanji: '夕', level: 'Bộ Thủ', meanings: ['Bộ Tịch', 'Buổi chiều tối', 'Đêm tối'], onyomi: ['セキ'], kunyomi: ['ゆう'] },
  { kanji: '大', level: 'Bộ Thủ', meanings: ['Bộ Đại', 'To lớn', 'Vĩ đại'], onyomi: ['ダイ', 'タイ'], kunyomi: ['おお・きい'] },
  { kanji: '女', level: 'Bộ Thủ', meanings: ['Bộ Nữ', 'Phụ nữ', 'Con gái'], onyomi: ['ジョ', 'ニョ'], kunyomi: ['おんな'] },
  { kanji: '子', level: 'Bộ Thủ', meanings: ['Bộ Tử', 'Con cái', 'Trẻ nhỏ'], onyomi: ['シ', 'ス'], kunyomi: ['こ'] },
  { kanji: '宀', level: 'Bộ Thủ', meanings: ['Bộ Miên', 'Mái nhà', 'Nơi trú ẩn'], onyomi: ['ベン'], kunyomi: ['うかんむり'] },
  { kanji: '寸', level: 'Bộ Thủ', meanings: ['Bộ Thốn', 'Tấc (đơn vị đo)', 'Ngắn nhỏ'], onyomi: ['スン'], kunyomi: [] },
  { kanji: '小', level: 'Bộ Thủ', meanings: ['Bộ Tiểu', 'Nhỏ bé', 'Ít ỏi'], onyomi: ['ショウ'], kunyomi: ['ちい・さい', 'こ'] },
  { kanji: '⺌', level: 'Bộ Thủ', meanings: ['Bộ Tiểu (biến thể)', 'Nhỏ bé'], onyomi: ['ショウ'], kunyomi: ['しょうかんむり'] },
  { kanji: '尢', level: 'Bộ Thủ', meanings: ['Bộ Uông', 'Chân bị què', 'Tật nguyền'], onyomi: ['オウ'], kunyomi: ['だいのまげあし'] },
  { kanji: '尸', level: 'Bộ Thủ', meanings: ['Bộ Thi', 'Xác chết', 'Thân xác'], onyomi: ['シ'], kunyomi: ['しかばね'] },
  { kanji: '屮', level: 'Bộ Thủ', meanings: ['Bộ Triệt', 'Mầm non mới mọc'], onyomi: ['テツ'], kunyomi: ['てつ'] },
  { kanji: '山', level: 'Bộ Thủ', meanings: ['Bộ Sơn', 'Núi non', 'Ngọn núi'], onyomi: ['サン'], kunyomi: ['やま'] },
  { kanji: '巛', level: 'Bộ Thủ', meanings: ['Bộ Xuyên', 'Dòng sông', 'Dòng chảy'], onyomi: ['セン'], kunyomi: ['かわ'] },
  { kanji: '工', level: 'Bộ Thủ', meanings: ['Bộ Công', 'Công nhân', 'Thợ thủ công'], onyomi: ['コウ', 'ク'], kunyomi: [] },
  { kanji: '己', level: 'Bộ Thủ', meanings: ['Bộ Kỷ', 'Bản thân mình', 'Can chi'], onyomi: ['コ', 'キ'], kunyomi: ['おのれ'] },
  { kanji: '巾', level: 'Bộ Thủ', meanings: ['Bộ Cân', 'Cái khăn', 'Vải vóc'], onyomi: ['キン'], kunyomi: ['はば'] },
  { kanji: '干', level: 'Bộ Thủ', meanings: ['Bộ Can', 'Cái khiên che chắn', 'Khô ráo'], onyomi: ['カン'], kunyomi: ['ほ・す'] },
  { kanji: '幺', level: 'Bộ Thủ', meanings: ['Bộ Yêu', 'Nhỏ nhoi', 'Sợi tơ nhỏ'], onyomi: ['ヨウ'], kunyomi: ['いとがしら'] },
  { kanji: '广', level: 'Bộ Thủ', meanings: ['Bộ Quảng', 'Mái nhà rộng', 'Mái che'], onyomi: ['ゲン'], kunyomi: ['まだれ'] },
  { kanji: '廴', level: 'Bộ Thủ', meanings: ['Bộ Dẫn', 'Bước dài', 'Kéo dài'], onyomi: ['イン'], kunyomi: ['えんにょう'] },
  { kanji: '廾', level: 'Bộ Thủ', meanings: ['Bộ Củng', 'Hai tay chắp lại', 'Nâng đỡ'], onyomi: ['キョウ'], kunyomi: ['こまぬ・く'] },
  { kanji: '弋', level: 'Bộ Thủ', meanings: ['Bộ Dặc', 'Mũi tên có dây buộc', 'Bắn'], onyomi: ['ヨク'], kunyomi: ['しきがまえ'] },
  { kanji: '弓', level: 'Bộ Thủ', meanings: ['Bộ Cung', 'Cây cung bắn tên'], onyomi: ['キュウ'], kunyomi: ['ゆみ'] },
  { kanji: '彐', level: 'Bộ Thủ', meanings: ['Bộ Kế', 'Đầu con nhím', 'Bàn chân thú'], onyomi: ['ケイ'], kunyomi: ['けいがしら'] },
  { kanji: '彡', level: 'Bộ Thủ', meanings: ['Bộ Sam', 'Lông dài', 'Nét trang trí'], onyomi: ['サン'], kunyomi: ['さんづくり'] },
  { kanji: '彳', level: 'Bộ Thủ', meanings: ['Bộ Xích', 'Bước chân trái', 'Đi lại'], onyomi: ['テキ'], kunyomi: ['ぎょうにんべん'] },

  // 4 nét (61-94)
  { kanji: '心', level: 'Bộ Thủ', meanings: ['Bộ Tâm', 'Trái tim', 'Tấm lòng'], onyomi: ['シン'], kunyomi: ['こころ'] },
  { kanji: '忄', level: 'Bộ Thủ', meanings: ['Bộ Tâm đứng', 'Tâm trạng (biến thể đứng)'], onyomi: ['シン'], kunyomi: ['りっしんべん'] },
  { kanji: '戈', level: 'Bộ Thủ', meanings: ['Bộ Qua', 'Cây giáo', 'Binh khí'], onyomi: ['カ'], kunyomi: ['ほこ'] },
  { kanji: '戶', level: 'Bộ Thủ', meanings: ['Bộ Hộ', 'Cửa một cánh', 'Hộ gia đình'], onyomi: ['コ'], kunyomi: ['と'] },
  { kanji: '手', level: 'Bộ Thủ', meanings: ['Bộ Thủ', 'Bàn tay'], onyomi: ['シュ'], kunyomi: ['て'] },
  { kanji: '扌', level: 'Bộ Thủ', meanings: ['Bộ Đề', 'Bàn tay (biến thể đứng)'], onyomi: ['シュ'], kunyomi: ['てへん'] },
  { kanji: '支', level: 'Bộ Thủ', meanings: ['Bộ Chi', 'Cành cây', 'Nâng đỡ'], onyomi: ['シ'], kunyomi: ['ささ・える'] },
  { kanji: '攴', level: 'Bộ Thủ', meanings: ['Bộ Phác', 'Đánh khẽ', 'Gõ nhẹ'], onyomi: ['ホク'], kunyomi: ['ぼくづくり'] },
  { kanji: '攵', level: 'Bộ Thủ', meanings: ['Bộ Phác (biến thể)', 'Đánh khẽ'], onyomi: ['ホク'], kunyomi: ['のぶん'] },
  { kanji: '文', level: 'Bộ Thủ', meanings: ['Bộ Văn', 'Văn tự', 'Chữ nghĩa'], onyomi: ['ブン', 'モン'], kunyomi: ['ふみ'] },
  { kanji: '斗', level: 'Bộ Thủ', meanings: ['Bộ Đẩu', 'Cái đấu đong gạo'], onyomi: ['ト'], kunyomi: ['ます'] },
  { kanji: '斤', level: 'Bộ Thủ', meanings: ['Bộ Cân', 'Cái rìu', 'Cân nặng'], onyomi: ['キン'], kunyomi: ['おの'] },
  { kanji: '方', level: 'Bộ Thủ', meanings: ['Bộ Phương', 'Hình vuông', 'Phương hướng'], onyomi: ['ホウ'], kunyomi: ['かた'] },
  { kanji: '无', level: 'Bộ Thủ', meanings: ['Bộ Vô', 'Không có'], onyomi: ['ム', 'ブ'], kunyomi: ['な・い'] },
  { kanji: '日', level: 'Bộ Thủ', meanings: ['Bộ Nhật', 'Mặt trời', 'Ngày'], onyomi: ['ニチ', 'ジツ'], kunyomi: ['ひ'] },
  { kanji: '曰', level: 'Bộ Thủ', meanings: ['Bộ Viết', 'Nói rằng', 'Rằng'], onyomi: ['エツ'], kunyomi: ['いわ・く'] },
  { kanji: '月', level: 'Bộ Thủ', meanings: ['Bộ Nguyệt', 'Mặt trăng', 'Tháng'], onyomi: ['ゲツ', 'ガツ'], kunyomi: ['つき'] },
  { kanji: '木', level: 'Bộ Thủ', meanings: ['Bộ Mộc', 'Cây cối', 'Gỗ'], onyomi: ['モク', 'ボク'], kunyomi: ['き'] },
  { kanji: '欠', level: 'Bộ Thủ', meanings: ['Bộ Khiếm', 'Ngáp', 'Thiếu thốn'], onyomi: ['ケツ'], kunyomi: ['か・ける'] },
  { kanji: '止', level: 'Bộ Thủ', meanings: ['Bộ Chỉ', 'Dừng lại', 'Đứng yên'], onyomi: ['シ'], kunyomi: ['と・まる'] },
  { kanji: '歹', level: 'Bộ Thủ', meanings: ['Bộ Đãi', 'Xương tàn', 'Chết chóc'], onyomi: ['タイ'], kunyomi: ['かばねへん'] },
  { kanji: '殳', level: 'Bộ Thủ', meanings: ['Bộ Thù', 'Binh khí bằng tre'], onyomi: ['シュ'], kunyomi: ['ほこづくり'] },
  { kanji: '毋', level: 'Bộ Thủ', meanings: ['Bộ Vô', 'Đừng', 'Chớ', 'Mẹ'], onyomi: ['ブ', 'ム'], kunyomi: ['なか・れ'] },
  { kanji: '比', level: 'Bộ Thủ', meanings: ['Bộ Tỷ', 'So sánh', 'Xếp cạnh nhau'], onyomi: ['ヒ'], kunyomi: ['くら・べる'] },
  { kanji: '毛', level: 'Bộ Thủ', meanings: ['Bộ Mao', 'Lông', 'Tóc'], onyomi: ['モウ'], kunyomi: ['け'] },
  { kanji: '氏', level: 'Bộ Thủ', meanings: ['Bộ Thị', 'Họ tộc', 'Dòng họ'], onyomi: ['シ'], kunyomi: ['うじ'] },
  { kanji: '气', level: 'Bộ Thủ', meanings: ['Bộ Khí', 'Không khí', 'Mây hơi'], onyomi: ['キ'], kunyomi: ['きがまえ'] },
  { kanji: '水', level: 'Bộ Thủ', meanings: ['Bộ Thủy', 'Nước'], onyomi: ['スイ'], kunyomi: ['みず'] },
  { kanji: '氵', level: 'Bộ Thủ', meanings: ['Bộ Ba chấm thủy', 'Nước (biến thể)'], onyomi: ['スイ'], kunyomi: ['さんずい'] },
  { kanji: '火', level: 'Bộ Thủ', meanings: ['Bộ Hỏa', 'Lửa'], onyomi: ['カ'], kunyomi: ['ひ'] },
  { kanji: '灬', level: 'Bộ Thủ', meanings: ['Bộ Hỏa dưới', 'Bốn chấm hỏa'], onyomi: ['カ'], kunyomi: ['れっか'] },
  { kanji: '爪', level: 'Bộ Thủ', meanings: ['Bộ Trảo', 'Móng vuốt'], onyomi: ['ソウ'], kunyomi: ['つめ'] },
  { kanji: '父', level: 'Bộ Thủ', meanings: ['Bộ Phụ', 'Người cha', 'Người bố'], onyomi: ['フ'], kunyomi: ['ちち'] },
  { kanji: '爻', level: 'Bộ Thủ', meanings: ['Bộ Hào', 'Quẻ bói', 'Giao nhau'], onyomi: ['コウ'], kunyomi: [] },
  { kanji: '爿', level: 'Bộ Thủ', meanings: ['Bộ Tường', 'Mảnh gỗ', 'Giường'], onyomi: ['ショウ'], kunyomi: ['しょうへん'] },
  { kanji: '片', level: 'Bộ Thủ', meanings: ['Bộ Phiến', 'Mảnh vỡ', 'Một phía'], onyomi: ['ヘン'], kunyomi: ['かた'] },
  { kanji: '牙', level: 'Bộ Thủ', meanings: ['Bộ Nha', 'Răng nanh'], onyomi: ['ガ', 'ゲ'], kunyomi: ['きば'] },
  { kanji: '牛', level: 'Bộ Thủ', meanings: ['Bộ Ngưu', 'Con bò'], onyomi: ['ギュウ'], kunyomi: ['うし'] },
  { kanji: '犬', level: 'Bộ Thủ', meanings: ['Bộ Khuyển', 'Con chó'], onyomi: ['ケン'], kunyomi: ['いぬ'] },
  { kanji: '犭', level: 'Bộ Thủ', meanings: ['Bộ Khuyển đứng', 'Thú hoang (biến thể)'], onyomi: ['ケン'], kunyomi: ['けものへん'] },

  // 5 nét (95-117)
  { kanji: '玄', level: 'Bộ Thủ', meanings: ['Bộ Huyền', 'Màu đen huyền bí', 'Sâu kín'], onyomi: ['ゲン'], kunyomi: [] },
  { kanji: '玉', level: 'Bộ Thủ', meanings: ['Bộ Ngọc', 'Viên ngọc quý'], onyomi: ['ギョク'], kunyomi: ['たま'] },
  { kanji: '瓜', level: 'Bộ Thủ', meanings: ['Bộ Qua', 'Quả dưa'], onyomi: ['カ'], kunyomi: ['うり'] },
  { kanji: '瓦', level: 'Bộ Thủ', meanings: ['Bộ Ngõa', 'Ngói lợp nhà'], onyomi: ['ガ'], kunyomi: ['かわら'] },
  { kanji: '甘', level: 'Bộ Thủ', meanings: ['Bộ Cam', 'Ngọt ngào'], onyomi: ['カン'], kunyomi: ['あま・い'] },
  { kanji: '生', level: 'Bộ Thủ', meanings: ['Bộ Sinh', 'Sinh sôi', 'Sống'], onyomi: ['セイ', 'ショウ'], kunyomi: ['い・きる', 'う・まれる'] },
  { kanji: '用', level: 'Bộ Thủ', meanings: ['Bộ Dụng', 'Dùng', 'Sử dụng'], onyomi: ['ヨウ'], kunyomi: ['もち・いる'] },
  { kanji: '田', level: 'Bộ Thủ', meanings: ['Bộ Điền', 'Ruộng đồng'], onyomi: ['デン'], kunyomi: ['た'] },
  { kanji: '疋', level: 'Bộ Thủ', meanings: ['Bộ Thất', 'Đoạn vải', 'Con thú'], onyomi: ['ヒキ', 'ショショ'], kunyomi: ['ひき'] },
  { kanji: '疒', level: 'Bộ Thủ', meanings: ['Bộ Nạch', 'Bệnh tật', 'Ốm đau'], onyomi: ['ダク'], kunyomi: ['やまいだれ'] },
  { kanji: '癶', level: 'Bộ Thủ', meanings: ['Bộ Bát', 'Hai chân dang ra'], onyomi: ['ハツ'], kunyomi: ['はつがしら'] },
  { kanji: '白', level: 'Bộ Thủ', meanings: ['Bộ Bạch', 'Màu trắng'], onyomi: ['ハク', 'ビャク'], kunyomi: ['しろ・い'] },
  { kanji: '皮', level: 'Bộ Thủ', meanings: ['Bộ Bì', 'Da', 'Vỏ'], onyomi: ['ヒ'], kunyomi: ['かわ'] },
  { kanji: '皿', level: 'Bộ Thủ', meanings: ['Bộ Mãnh', 'Cái đĩa', 'Bát đĩa'], onyomi: ['ベイ'], kunyomi: ['さら'] },
  { kanji: '目', level: 'Bộ Thủ', meanings: ['Bộ Mục', 'Con mắt'], onyomi: ['モク'], kunyomi: ['め'] },
  { kanji: '矛', level: 'Bộ Thủ', meanings: ['Bộ Mâu', 'Cây mâu', 'Mâu thuẫn'], onyomi: ['ム', 'ボウ'], kunyomi: ['ほこ'] },
  { kanji: '矢', level: 'Bộ Thủ', meanings: ['Bộ Thỉ', 'Mũi tên'], onyomi: ['シ'], kunyomi: ['や'] },
  { kanji: '石', level: 'Bộ Thủ', meanings: ['Bộ Thạch', 'Hòn đá'], onyomi: ['セキ', 'シャク'], kunyomi: ['いし'] },
  { kanji: '示', level: 'Bộ Thủ', meanings: ['Bộ Kỳ / Thị', 'Bày tỏ', 'Thần linh'], onyomi: ['ジ', 'シ'], kunyomi: ['しめ・す'] },
  { kanji: '礻', level: 'Bộ Thủ', meanings: ['Bộ Thị (biến thể)', 'Tâm linh', 'Thần thánh'], onyomi: ['シ'], kunyomi: ['しめすへん'] },
  { kanji: '禸', level: 'Bộ Thủ', meanings: ['Bộ Nhựu', 'Vết chân thú'], onyomi: ['ジュウ'], kunyomi: ['ぐうのあし'] },
  { kanji: '禾', level: 'Bộ Thủ', meanings: ['Bộ Hòa', 'Cây lúa'], onyomi: ['カ'], kunyomi: ['のぎへん'] },
  { kanji: '穴', level: 'Bộ Thủ', meanings: ['Bộ Huyệt', 'Cái hang', 'Lỗ hổng'], onyomi: ['ケツ'], kunyomi: ['あな'] },
  { kanji: '立', level: 'Bộ Thủ', meanings: ['Bộ Lập', 'Đứng thẳng'], onyomi: ['リツ'], kunyomi: ['た・つ'] },

  // 6 nét (118-146)
  { kanji: '竹', level: 'Bộ Thủ', meanings: ['Bộ Trúc', 'Cây tre', 'Cây trúc'], onyomi: ['チク'], kunyomi: ['たけ'] },
  { kanji: '米', level: 'Bộ Thủ', meanings: ['Bộ Mễ', 'Hạt gạo'], onyomi: ['ベイ', 'マイ'], kunyomi: ['こめ'] },
  { kanji: '糸', level: 'Bộ Thủ', meanings: ['Bộ Mịch', 'Sợi tơ', 'Sợi chỉ'], onyomi: ['シ'], kunyomi: ['いと'] },
  { kanji: '缶', level: 'Bộ Thủ', meanings: ['Bộ Phẫu', 'Đồ sành sứ', 'Cái vò'], onyomi: ['フ'], kunyomi: ['ほとぎ'] },
  { kanji: '网', level: 'Bộ Thủ', meanings: ['Bộ Võng', 'Lưới bắt cá'], onyomi: ['モウ'], kunyomi: ['あみ'] },
  { kanji: '羊', level: 'Bộ Thủ', meanings: ['Bộ Dương', 'Con cừu', 'Con dê'], onyomi: ['ヨウ'], kunyomi: ['ひつじ'] },
  { kanji: '羽', level: 'Bộ Thủ', meanings: ['Bộ Vũ', 'Lông vũ', 'Cánh chim'], onyomi: ['ウ'], kunyomi: ['はね', 'は'] },
  { kanji: '老', level: 'Bộ Thủ', meanings: ['Bộ Lão', 'Người già', 'Lão hóa'], onyomi: ['ロウ'], kunyomi: ['お・いる', 'ふ・ける'] },
  { kanji: '而', level: 'Bộ Thủ', meanings: ['Bộ Nhi', 'Râu ria', 'Mà'], onyomi: ['ジ', 'ニ'], kunyomi: ['しこう・して'] },
  { kanji: '耒', level: 'Bộ Thủ', meanings: ['Bộ Lỗi', 'Cái cày ruộng'], onyomi: ['ライ'], kunyomi: ['すき'] },
  { kanji: '耳', level: 'Bộ Thủ', meanings: ['Bộ Nhĩ', 'Cái tai'], onyomi: ['ジ'], kunyomi: ['みみ'] },
  { kanji: '聿', level: 'Bộ Thủ', meanings: ['Bộ Duật', 'Cây bút viết'], onyomi: ['イツ'], kunyomi: ['ふで'] },
  { kanji: '肉', level: 'Bộ Thủ', meanings: ['Bộ Nhục', 'Thịt', 'Cơ bắp'], onyomi: ['ニク'], kunyomi: [] },
  { kanji: '臣', level: 'Bộ Thủ', meanings: ['Bộ Thần', 'Bầy tôi', 'Quan đại thần'], onyomi: ['シン', 'ジン'], kunyomi: [] },
  { kanji: '自', level: 'Bộ Thủ', meanings: ['Bộ Tự', 'Bản thân', 'Tự mình'], onyomi: ['ジ', 'シ'], kunyomi: ['みずか・ら'] },
  { kanji: '至', level: 'Bộ Thủ', meanings: ['Bộ Chí', 'Đến nơi', 'Tột cùng'], onyomi: ['シ'], kunyomi: ['いた・る'] },
  { kanji: '臼', level: 'Bộ Thủ', meanings: ['Bộ Cữu', 'Cái cối giã'], onyomi: ['キュウ'], kunyomi: ['うす'] },
  { kanji: '舌', level: 'Bộ Thủ', meanings: ['Bộ Thiệt', 'Cái lưỡi'], onyomi: ['ゼツ'], kunyomi: ['した'] },
  { kanji: '舛', level: 'Bộ Thủ', meanings: ['Bộ Suyễn', 'Sai lệch', 'Trái ngược'], onyomi: ['セン'], kunyomi: ['ます'] },
  { kanji: '舟', level: 'Bộ Thủ', meanings: ['Bộ Chu', 'Con thuyền', 'Chiếc thuyền'], onyomi: ['シュウ'], kunyomi: ['ふね'] },
  { kanji: '艮', level: 'Bộ Thủ', meanings: ['Bộ Cấn', 'Quẻ cấn', 'Bướng bỉnh'], onyomi: ['コン', 'ゴン'], kunyomi: ['うしとら'] },
  { kanji: '色', level: 'Bộ Thủ', meanings: ['Bộ Sắc', 'Màu sắc', 'Nhan sắc'], onyomi: ['ショク', 'シキ'], kunyomi: ['いろ'] },
  { kanji: '艸', level: 'Bộ Thủ', meanings: ['Bộ Thảo', 'Cỏ cây'], onyomi: ['ソウ'], kunyomi: ['くさ'] },
  { kanji: '艹', level: 'Bộ Thủ', meanings: ['Bộ Cỏ', 'Thảo đầu (biến thể)'], onyomi: ['ソウ'], kunyomi: ['くさかんむり'] },
  { kanji: '虍', level: 'Bộ Thủ', meanings: ['Bộ Hô', 'Vằn con hổ'], onyomi: ['コ'], kunyomi: ['とらがしら'] },
  { kanji: '虫', level: 'Bộ Thủ', meanings: ['Bộ Trùng', 'Côn trùng', 'Sâu bọ'], onyomi: ['チュウ'], kunyomi: ['むし'] },
  { kanji: '血', level: 'Bộ Thủ', meanings: ['Bộ Huyết', 'Máu'], onyomi: ['ケツ'], kunyomi: ['ち'] },
  { kanji: '行', level: 'Bộ Thủ', meanings: ['Bộ Hành', 'Đi lại', 'Hành động'], onyomi: ['コウ', 'ギョウ'], kunyomi: ['い・く', 'おこな・う'] },
  { kanji: '衣', level: 'Bộ Thủ', meanings: ['Bộ Y', 'Áo quần', 'Trang phục'], onyomi: ['イ'], kunyomi: ['ころも'] },
  { kanji: '衤', level: 'Bộ Thủ', meanings: ['Bộ Y (biến thể đứng)', 'Áo quần'], onyomi: ['イ'], kunyomi: ['ころもへん'] },
  { kanji: '襾', level: 'Bộ Thủ', meanings: ['Bộ Á', 'Che đậy', 'Bao trùm'], onyomi: ['ア'], kunyomi: ['おおい'] },

  // 7 nét (147-166)
  { kanji: '見', level: 'Bộ Thủ', meanings: ['Bộ Kiến', 'Nhìn thấy', 'Ý kiến'], onyomi: ['ケン'], kunyomi: ['み・る'] },
  { kanji: '角', level: 'Bộ Thủ', meanings: ['Bộ Giác', 'Góc cạnh', 'Cái sừng'], onyomi: ['カク'], kunyomi: ['かど', 'つの'] },
  { kanji: '言', level: 'Bộ Thủ', meanings: ['Bộ Ngôn', 'Lời nói', 'Ngôn ngữ'], onyomi: ['ゲン', 'ゴン'], kunyomi: ['い・う', 'こと'] },
  { kanji: '谷', level: 'Bộ Thủ', meanings: ['Bộ Cốc', 'Thung lũng'], onyomi: ['コク'], kunyomi: ['たに'] },
  { kanji: '豆', level: 'Bộ Thủ', meanings: ['Bộ Đậu', 'Hạt đậu'], onyomi: ['トウ', 'ズ'], kunyomi: ['まめ'] },
  { kanji: '豕', level: 'Bộ Thủ', meanings: ['Bộ Thỉ', 'Con lợn', 'Con heo'], onyomi: ['シ'], kunyomi: ['いのこ'] },
  { kanji: '豸', level: 'Bộ Thủ', meanings: ['Bộ Trĩ', 'Thú không sừng'], onyomi: ['チ'], kunyomi: ['むじな'] },
  { kanji: '貝', level: 'Bộ Thủ', meanings: ['Bộ Bối', 'Vỏ sò', 'Tiền của'], onyomi: ['バイ'], kunyomi: ['かい'] },
  { kanji: '赤', level: 'Bộ Thủ', meanings: ['Bộ Xích', 'Màu đỏ'], onyomi: ['セキ'], kunyomi: ['あか・い'] },
  { kanji: '走', level: 'Bộ Thủ', meanings: ['Bộ Tẩu', 'Chạy'], onyomi: ['ソウ'], kunyomi: ['はし・る'] },
  { kanji: '足', level: 'Bộ Thủ', meanings: ['Bộ Túc', 'Chân', 'Đầy đủ'], onyomi: ['ソク'], kunyomi: ['あし', 'た・りる'] },
  { kanji: '身', level: 'Bộ Thủ', meanings: ['Bộ Thân', 'Thân thể', 'Bản thân'], onyomi: ['シン'], kunyomi: ['み'] },
  { kanji: '車', level: 'Bộ Thủ', meanings: ['Bộ Xa', 'Chiếc xe'], onyomi: ['シャ'], kunyomi: ['くるま'] },
  { kanji: '辛', level: 'Bộ Thủ', meanings: ['Bộ Tân', 'Cay đắng', 'Vất vả'], onyomi: ['シン'], kunyomi: ['から・い'] },
  { kanji: '辰', level: 'Bộ Thủ', meanings: ['Bộ Thần', 'Can chi (Thìn)', 'Thời gian'], onyomi: ['シン'], kunyomi: ['たつ'] },
  { kanji: '辵', level: 'Bộ Thủ', meanings: ['Bộ Sước', 'Bước đi rồi dừng lại'], onyomi: ['チャク'], kunyomi: ['しんにょう'] },
  { kanji: '辶', level: 'Bộ Thủ', meanings: ['Bộ Quai xước (biến thể)', 'Đường đi'], onyomi: ['チャク'], kunyomi: ['しんにょう'] },
  { kanji: '邑', level: 'Bộ Thủ', meanings: ['Bộ Ấp', 'Làng xóm', 'Thành ấp'], onyomi: ['ユウ'], kunyomi: ['むら'] },
  { kanji: '阝', level: 'Bộ Thủ', meanings: ['Bộ Phụ / Ấp', 'Gò đất / Thành quách'], onyomi: ['フ', 'ユウ'], kunyomi: ['こざとへん', 'おおざと'] },
  { kanji: '酉', level: 'Bộ Thủ', meanings: ['Bộ Dậu', 'Bình rượu', 'Can chi (Dậu)'], onyomi: ['ユウ'], kunyomi: ['とり'] },
  { kanji: '釆', level: 'Bộ Thủ', meanings: ['Bộ Biện', 'Phân biệt', 'Gặt hái'], onyomi: ['ハン', 'ベン'], kunyomi: ['うね'] },
  { kanji: '里', level: 'Bộ Thủ', meanings: ['Bộ Lý', 'Làng mạc', 'Dặm đường'], onyomi: ['リ'], kunyomi: ['さと'] },

  // 8 nét (167-175)
  { kanji: '金', level: 'Bộ Thủ', meanings: ['Bộ Kim', 'Kim loại', 'Vàng', 'Tiền'], onyomi: ['キン', 'コン'], kunyomi: ['かね'] },
  { kanji: '長', level: 'Bộ Thủ', meanings: ['Bộ Trường', 'Dài', 'Trưởng lão'], onyomi: ['チョウ'], kunyomi: ['なが・い'] },
  { kanji: '門', level: 'Bộ Thủ', meanings: ['Bộ Môn', 'Cánh cổng', 'Cửa lớn'], onyomi: ['モン'], kunyomi: ['かど'] },
  { kanji: '阜', level: 'Bộ Thủ', meanings: ['Bộ Phụ', 'Gò đất cao', 'Đồi'], onyomi: ['フ'], kunyomi: ['おか'] },
  { kanji: '隶', level: 'Bộ Thủ', meanings: ['Bộ Đãi', 'Nô lệ', 'Theo hầu'], onyomi: ['レイ'], kunyomi: ['つきしたが・う'] },
  { kanji: '隹', level: 'Bộ Thủ', meanings: ['Bộ Chuy', 'Chim đuôi ngắn'], onyomi: ['スイ'], kunyomi: ['ふるとり'] },
  { kanji: '雨', level: 'Bộ Thủ', meanings: ['Bộ Vũ', 'Mưa'], onyomi: ['ウ'], kunyomi: ['あめ'] },
  { kanji: '靑', level: 'Bộ Thủ', meanings: ['Bộ Thanh', 'Màu xanh'], onyomi: ['セイ'], kunyomi: ['あお・い'] },
  { kanji: '非', level: 'Bộ Thủ', meanings: ['Bộ Phi', 'Sai trái', 'Không phải'], onyomi: ['ヒ'], kunyomi: ['あら・ず'] },

  // 9 nét (176-186)
  { kanji: '面', level: 'Bộ Thủ', meanings: ['Bộ Diện', 'Mặt', 'Bề mặt'], onyomi: ['メン'], kunyomi: ['おも', 'つら'] },
  { kanji: '革', level: 'Bộ Thủ', meanings: ['Bộ Cách', 'Da thuộc', 'Cải cách'], onyomi: ['カク'], kunyomi: ['かわ'] },
  { kanji: '韋', level: 'Bộ Thủ', meanings: ['Bộ Vi', 'Da thuộc mềm'], onyomi: ['イ'], kunyomi: ['なめしがわ'] },
  { kanji: '韭', level: 'Bộ Thủ', meanings: ['Bộ Cửu', 'Cây hẹ'], onyomi: ['キュウ'], kunyomi: ['にら'] },
  { kanji: '音', level: 'Bộ Thủ', meanings: ['Bộ Âm', 'Âm thanh'], onyomi: ['オン'], kunyomi: ['おと', 'ね'] },
  { kanji: '頁', level: 'Bộ Thủ', meanings: ['Bộ Hiệt', 'Trang giấy', 'Cái đầu'], onyomi: ['ケツ'], kunyomi: ['ページ'] },
  { kanji: '風', level: 'Bộ Thủ', meanings: ['Bộ Phong', 'Gió', 'Phong thái'], onyomi: ['フウ'], kunyomi: ['かぜ'] },
  { kanji: '飛', level: 'Bộ Thủ', meanings: ['Bộ Phi', 'Bay lượn'], onyomi: ['ヒ'], kunyomi: ['と・ぶ'] },
  { kanji: '食', level: 'Bộ Thủ', meanings: ['Bộ Thực', 'Ăn uống', 'Món ăn'], onyomi: ['ショク'], kunyomi: ['た・べる'] },
  { kanji: '首', level: 'Bộ Thủ', meanings: ['Bộ Thủ', 'Đầu', 'Cổ'], onyomi: ['シュ'], kunyomi: ['くび'] },
  { kanji: '香', level: 'Bộ Thủ', meanings: ['Bộ Hương', 'Mùi thơm'], onyomi: ['コウ'], kunyomi: ['かお・り'] },

  // 10-17 nét (187-214)
  { kanji: '馬', level: 'Bộ Thủ', meanings: ['Bộ Mã', 'Con ngựa'], onyomi: ['バ'], kunyomi: ['うま'] },
  { kanji: '骨', level: 'Bộ Thủ', meanings: ['Bộ Cốt', 'Xương cốt'], onyomi: ['コツ'], kunyomi: ['ほね'] },
  { kanji: '高', level: 'Bộ Thủ', meanings: ['Bộ Cao', 'Cao ráo', 'Đắt'], onyomi: ['コウ'], kunyomi: ['たか・い'] },
  { kanji: '髟', level: 'Bộ Thủ', meanings: ['Bộ Bưu', 'Tóc dài'], onyomi: ['ヒョウ'], kunyomi: ['かみがしら'] },
  { kanji: '鬥', level: 'Bộ Thủ', meanings: ['Bộ Đấu', 'Chiến đấu', 'Đánh nhau'], onyomi: ['トウ'], kunyomi: ['たたか・う'] },
  { kanji: '鬯', level: 'Bộ Thủ', meanings: ['Bộ Sưởng', 'Rượu cúng tế'], onyomi: ['チョウ'], kunyomi: ['ちょう'] },
  { kanji: '鬲', level: 'Bộ Thủ', meanings: ['Bộ Cách', 'Cái nồi ba chân'], onyomi: ['レキ', 'カク'], kunyomi: ['かなえ'] },
  { kanji: '鬼', level: 'Bộ Thủ', meanings: ['Bộ Quỷ', 'Ma quỷ'], onyomi: ['キ'], kunyomi: ['おに'] },
  { kanji: '魚', level: 'Bộ Thủ', meanings: ['Bộ Ngư', 'Con cá'], onyomi: ['ギョ'], kunyomi: ['さかな'] },
  { kanji: '鳥', level: 'Bộ Thủ', meanings: ['Bộ Điểu', 'Con chim'], onyomi: ['チョウ'], kunyomi: ['とり'] },
  { kanji: '鹵', level: 'Bộ Thủ', meanings: ['Bộ Lỗ', 'Đất mặn', 'Muối mỏ'], onyomi: ['ロ'], kunyomi: ['しおち'] },
  { kanji: '鹿', level: 'Bộ Thủ', meanings: ['Bộ Lộc', 'Con hươu', 'Con nai'], onyomi: ['ロク'], kunyomi: ['しか'] },
  { kanji: '麥', level: 'Bộ Thủ', meanings: ['Bộ Mạch', 'Lúa mạch'], onyomi: ['バク'], kunyomi: ['むぎ'] },
  { kanji: '麻', level: 'Bộ Thủ', meanings: ['Bộ Ma', 'Cây gai', 'Vải gai'], onyomi: ['マ'], kunyomi: ['あさ'] },
  { kanji: '黃', level: 'Bộ Thủ', meanings: ['Bộ Hoàng', 'Màu vàng'], onyomi: ['コウ'], kunyomi: ['き'] },
  { kanji: '黍', level: 'Bộ Thủ', meanings: ['Bộ Thử', 'Cây kê'], onyomi: ['ショ'], kunyomi: ['きび'] },
  { kanji: '黑', level: 'Bộ Thủ', meanings: ['Bộ Hắc', 'Màu đen'], onyomi: ['コク'], kunyomi: ['くろ'] },
  { kanji: '黹', level: 'Bộ Thủ', meanings: ['Bộ Chỉ', 'May vá', 'Thêu thùa'], onyomi: ['チ'], kunyomi: ['ぬいとり'] },
  { kanji: '黽', level: 'Bộ Thủ', meanings: ['Bộ Mẫn', 'Con ếch', 'Con nhái'], onyomi: ['ビン', 'ミン'], kunyomi: ['あおがえる'] },
  { kanji: '鼎', level: 'Bộ Thủ', meanings: ['Bộ Đỉnh', 'Cái đỉnh đồng ba chân'], onyomi: ['テイ'], kunyomi: ['かなえ'] },
  { kanji: '鼓', level: 'Bộ Thủ', meanings: ['Bộ Cổ', 'Cái trống'], onyomi: ['コ'], kunyomi: ['つづみ'] },
  { kanji: '鼠', level: 'Bộ Thủ', meanings: ['Bộ Thử', 'Con chuột'], onyomi: ['ソ'], kunyomi: ['ねずみ'] },
  { kanji: '鼻', level: 'Bộ Thủ', meanings: ['Bộ Tỵ', 'Cái mũi'], onyomi: ['ビ'], kunyomi: ['はな'] },
  { kanji: '齊', level: 'Bộ Thủ', meanings: ['Bộ Tề', 'Đều đặn', 'Tề chỉnh'], onyomi: ['セイ'], kunyomi: ['そろ・う'] },
  { kanji: '齒', level: 'Bộ Thủ', meanings: ['Bộ Xỉ', 'Cái răng'], onyomi: ['シ'], kunyomi: ['は'] },
  { kanji: '龍', level: 'Bộ Thủ', meanings: ['Bộ Long', 'Con rồng'], onyomi: ['リュウ'], kunyomi: ['たつ'] },
  { kanji: '龜', level: 'Bộ Thủ', meanings: ['Bộ Quy', 'Con rùa'], onyomi: ['キ'], kunyomi: ['かめ'] },
  { kanji: '龠', level: 'Bộ Thủ', meanings: ['Bộ Dược', 'Cây sáo ba lỗ', 'Ống tiêu'], onyomi: ['ヤク'], kunyomi: ['ふえ'] }
];
