module.exports = [
  { kanji: '愛', level: 'N3', meanings: ['Ái', 'Yêu thương', 'Tình yêu'], onyomi: ['アイ'], kunyomi: ['い・しい', 'め・でる'] },
  { kanji: '感', level: 'N3', meanings: ['Cảm', 'Cảm giác', 'Cảm nhận'], onyomi: ['カン'], kunyomi: [] },
  { kanji: '情', level: 'N3', meanings: ['Tình', 'Tình cảm', 'Thông tin'], onyomi: ['ジョウ', 'セイ'], kunyomi: ['なさ・け'] },
  { kanji: '想', level: 'N3', meanings: ['Tưởng', 'Suy nghĩ', 'Tưởng tượng'], onyomi: ['ソウ', 'ソ'], kunyomi: ['おも・う'] },
  { kanji: '願', level: 'N3', meanings: ['Nguyện', 'Cầu nguyện', 'Mong muốn'], onyomi: ['ガン'], kunyomi: ['ねが・う'] },
  { kanji: '望', level: 'N3', meanings: ['Vọng', 'Hy vọng', 'Nguyện vọng'], onyomi: ['ボウ', 'モウ'], kunyomi: ['のぞ・む'] },
  { kanji: '信', level: 'N3', meanings: ['Tín', 'Tin tưởng', 'Tín nhiệm'], onyomi: ['シン'], kunyomi: [] },
  { kanji: '疑', level: 'N3', meanings: ['Nghi', 'Nghi ngờ'], onyomi: ['ギ'], kunyomi: ['うたが・う'] },
  { kanji: '変', level: 'N3', meanings: ['Biến', 'Thay đổi', 'Kỳ lạ'], onyomi: ['ヘン'], kunyomi: ['か・わる', 'か・える'] },
  { kanji: '化', level: 'N3', meanings: ['Hóa', 'Biến hóa', 'Hóa học'], onyomi: ['カ', 'ケ'], kunyomi: ['ば・ける', 'ば・かす'] },
  { kanji: '関', level: 'N3', meanings: ['Quan', 'Liên quan', 'Quan hệ'], onyomi: ['カン'], kunyomi: ['せき', 'かか・わる'] },
  { kanji: '係', level: 'N3', meanings: ['Hệ', 'Người phụ trách', 'Liên can'], onyomi: ['ケイ'], kunyomi: ['かか・る', 'かかり'] },
  { kanji: '連', level: 'N3', meanings: ['Liên', 'Liên lạc', 'Dẫn theo'], onyomi: ['レン'], kunyomi: ['つら・なる', 'つ・れる'] },
  { kanji: '絡', level: 'N3', meanings: ['Lạc', 'Vướng mắc', 'Liên lạc'], onyomi: ['ラク'], kunyomi: ['から・む'] },
  { kanji: '約', level: 'N3', meanings: ['Ước', 'Ước lượng', 'Hẹn ước'], onyomi: ['ヤク'], kunyomi: [] },
  { kanji: '束', level: 'N3', meanings: ['Thúc', 'Bó', 'Ràng buộc'], onyomi: ['ソク'], kunyomi: ['たば'] },
  { kanji: '必', level: 'N3', meanings: ['Tất', 'Tất yếu', 'Chắc chắn'], onyomi: ['ヒツ'], kunyomi: ['かなら・ず'] },
  { kanji: '要', level: 'N3', meanings: ['Yếu', 'Cần thiết', 'Quan trọng'], onyomi: ['ヨウ'], kunyomi: ['い・る', 'かなめ'] },
  { kanji: '相', level: 'N3', meanings: ['Tương', 'Tương hỗ', 'Cùng nhau'], onyomi: ['ソウ', 'ショウ'], kunyomi: ['あい'] },
  { kanji: '談', level: 'N3', meanings: ['Đàm', 'Bàn luận', 'Nói chuyện'], onyomi: ['ダン'], kunyomi: [] },
  { kanji: '案', level: 'N3', meanings: ['Án', 'Phương án', 'Đề án'], onyomi: ['アン'], kunyomi: [] },
  { kanji: '内', level: 'N3', meanings: ['Nội', 'Bên trong'], onyomi: ['ナイ', 'ダイ'], kunyomi: ['うち'] },
  { kanji: '準', level: 'N3', meanings: ['Chuẩn', 'Tiêu chuẩn', 'Chuẩn bị'], onyomi: ['ジュン'], kunyomi: [] },
  { kanji: '備', level: 'N3', meanings: ['Bị', 'Trang bị', 'Chuẩn bị'], onyomi: ['ビ'], kunyomi: ['そな・える', 'そな・わる'] },
  { kanji: '面', level: 'N3', meanings: ['Diện', 'Mặt', 'Bề mặt'], onyomi: ['メン'], kunyomi: ['おも', 'つら'] },
  { kanji: '接', level: 'N3', meanings: ['Tiếp', 'Tiếp xúc', 'Gặp mặt'], onyomi: ['セツ'], kunyomi: ['つ・ぐ'] },
  { kanji: '受', level: 'N3', meanings: ['Thụ', 'Nhận', 'Tiếp nhận'], onyomi: ['ジュ'], kunyomi: ['う・ける', 'う・かる'] },
  { kanji: '付', level: 'N3', meanings: ['Phó', 'Gắn vào', 'Kèm theo'], onyomi: ['フ'], kunyomi: ['つ・く', 'つ・ける'] },
  { kanji: '加', level: 'N3', meanings: ['Gia', 'Thêm vào', 'Gia tăng'], onyomi: ['カ'], kunyomi: ['くわ・える', 'くわ・わる'] },
  { kanji: '減', level: 'N3', meanings: ['Giảm', 'Giảm bớt', 'Suy giảm'], onyomi: ['ゲン'], kunyomi: ['へ・る', 'へ・らす'] },
  { kanji: '増', level: 'N3', meanings: ['Tăng', 'Tăng lên', 'Gia tăng'], onyomi: ['ゾウ'], kunyomi: ['ふ・える', 'ふ・やす', 'ま・す'] },
  { kanji: '常', level: 'N3', meanings: ['Thường', 'Bình thường', 'Thường ngày'], onyomi: ['ジョウ'], kunyomi: ['つね', 'とこ'] },
  { kanji: '非', level: 'N3', meanings: ['Phi', 'Phi thường', 'Không phải'], onyomi: ['ヒ'], kunyomi: [] },
  { kanji: '活', level: 'N3', meanings: ['Hoạt', 'Hoạt động', 'Sống động'], onyomi: ['カツ'], kunyomi: ['い・きる'] },
  { kanji: '性', level: 'N3', meanings: ['Tính', 'Tính cách', 'Giới tính'], onyomi: ['セイ', 'ショウ'], kunyomi: ['さが'] },
  { kanji: '格', level: 'N3', meanings: ['Cách', 'Tư cách', 'Quy cách'], onyomi: ['カク', 'コウ'], kunyomi: [] },
  { kanji: '的', level: 'N3', meanings: ['Đích', 'Mục đích', 'Mang tính'], onyomi: ['テキ'], kunyomi: ['まと'] },
  { kanji: '解', level: 'N3', meanings: ['Giải', 'Giải thích', 'Hiểu'], onyomi: ['カイ', 'ゲ'], kunyomi: ['と・く', 'と・ける'] },
  { kanji: '決', level: 'N3', meanings: ['Quyết', 'Quyết định', 'Quyết tâm'], onyomi: ['ケツ'], kunyomi: ['き・める', 'き・まる'] },
  { kanji: '定', level: 'N3', meanings: ['Định', 'Cố định', 'Xác định'], onyomi: ['テイ', 'ジョウ'], kunyomi: ['さだ・める', 'さだ・まる'] },
  { kanji: '選', level: 'N3', meanings: ['Tuyển', 'Lựa chọn', 'Tuyển chọn'], onyomi: ['セン'], kunyomi: ['えら・ぶ'] },
  { kanji: '残', level: 'N3', meanings: ['Tàn', 'Còn lại', 'Tàn tích'], onyomi: ['ザン'], kunyomi: ['のこ・る', 'のこ・す'] },
  { kanji: '念', level: 'N3', meanings: ['Niệm', 'Ý niệm', 'Tưởng nhớ'], onyomi: ['ネン'], kunyomi: [] },
  { kanji: '求', level: 'N3', meanings: ['Cầu', 'Tìm kiếm', 'Yêu cầu'], onyomi: ['キュウ'], kunyomi: ['もと・める'] },
  { kanji: '職', level: 'N3', meanings: ['Chức', 'Nghề nghiệp', 'Chức vụ'], onyomi: ['ショク'], kunyomi: [] },
  { kanji: '給', level: 'N3', meanings: ['Cấp', 'Cung cấp', 'Tiền lương'], onyomi: ['キュウ'], kunyomi: ['たま・う'] },
  { kanji: '資', level: 'N3', meanings: ['Tư', 'Tư cách', 'Tài sản'], onyomi: ['シ'], kunyomi: [] },
  { kanji: '料', level: 'N3', meanings: ['Liệu', 'Nguyên liệu', 'Tiền phí'], onyomi: ['リョウ'], kunyomi: [] },
  { kanji: '税', level: 'N3', meanings: ['Thuế', 'Tiền thuế'], onyomi: ['ゼイ'], kunyomi: [] },
  { kanji: '金', level: 'N3', meanings: ['Kim', 'Tiền', 'Vàng'], onyomi: ['キン', 'コン'], kunyomi: ['かね'] }
];
