module.exports = [
  { kanji: '日', level: 'N5', meanings: ['Nhật', 'Ngày', 'Mặt trời'], onyomi: ['ニチ', 'ジツ'], kunyomi: ['ひ', 'か'] },
  { kanji: '月', level: 'N5', meanings: ['Nguyệt', 'Tháng', 'Mặt trăng'], onyomi: ['ゲツ', 'ガツ'], kunyomi: ['つき'] },
  { kanji: '火', level: 'N5', meanings: ['Hỏa', 'Lửa'], onyomi: ['カ'], kunyomi: ['ひ'] },
  { kanji: '水', level: 'N5', meanings: ['Thủy', 'Nước'], onyomi: ['スイ'], kunyomi: ['みず'] },
  { kanji: '木', level: 'N5', meanings: ['Mộc', 'Cây', 'Gỗ'], onyomi: ['モク', 'ボク'], kunyomi: ['き'] },
  { kanji: '金', level: 'N5', meanings: ['Kim', 'Vàng', 'Tiền'], onyomi: ['キン', 'コン'], kunyomi: ['かね'] },
  { kanji: '土', level: 'N5', meanings: ['Thổ', 'Đất'], onyomi: ['ド', 'ト'], kunyomi: ['つち'] },
  { kanji: '山', level: 'N5', meanings: ['Sơn', 'Núi'], onyomi: ['サン'], kunyomi: ['やま'] },
  { kanji: '川', level: 'N5', meanings: ['Xuyên', 'Sông'], onyomi: ['セン'], kunyomi: ['かわ'] },
  { kanji: '田', level: 'N5', meanings: ['Điền', 'Ruộng'], onyomi: ['デン'], kunyomi: ['た'] },
  { kanji: '一', level: 'N5', meanings: ['Nhất', 'Một'], onyomi: ['イチ', 'イツ'], kunyomi: ['ひと・つ'] },
  { kanji: '二', level: 'N5', meanings: ['Nhị', 'Hai'], onyomi: ['ニ'], kunyomi: ['ふた・つ'] },
  { kanji: '三', level: 'N5', meanings: ['Tam', 'Ba'], onyomi: ['サン'], kunyomi: ['み・っつ'] },
  { kanji: '四', level: 'N5', meanings: ['Tứ', 'Bốn'], onyomi: ['シ'], kunyomi: ['よ・っつ', 'よん'] },
  { kanji: '五', level: 'N5', meanings: ['Ngũ', 'Năm'], onyomi: ['ゴ'], kunyomi: ['いつ・つ'] },
  { kanji: '六', level: 'N5', meanings: ['Lục', 'Sáu'], onyomi: ['ロク'], kunyomi: ['む・っつ'] },
  { kanji: '七', level: 'N5', meanings: ['Thất', 'Bảy'], onyomi: ['シチ'], kunyomi: ['なな・つ'] },
  { kanji: '八', level: 'N5', meanings: ['Bát', 'Tám'], onyomi: ['ハチ'], kunyomi: ['や・っつ'] },
  { kanji: '九', level: 'N5', meanings: ['Cửu', 'Chín'], onyomi: ['キュウ', 'ク'], kunyomi: ['ここの・つ'] },
  { kanji: '十', level: 'N5', meanings: ['Thập', 'Mười'], onyomi: ['ジュウ', 'ジッ'], kunyomi: ['とお'] },
  { kanji: '百', level: 'N5', meanings: ['Bách', 'Trăm'], onyomi: ['ヒャク'], kunyomi: ['もも'] },
  { kanji: '千', level: 'N5', meanings: ['Thiên', 'Nghìn'], onyomi: ['セン'], kunyomi: ['ち'] },
  { kanji: '万', level: 'N5', meanings: ['Vạn', 'Mười nghìn'], onyomi: ['マン', 'バン'], kunyomi: [] },
  { kanji: '円', level: 'N5', meanings: ['Yên', 'Tròn', 'Đồng Yên'], onyomi: ['エン'], kunyomi: ['まる・い'] },
  { kanji: '年', level: 'N5', meanings: ['Niên', 'Năm', 'Tuổi'], onyomi: ['ネン'], kunyomi: ['とし'] },
  { kanji: '上', level: 'N5', meanings: ['Thượng', 'Trên', 'Lên'], onyomi: ['ジョウ'], kunyomi: ['うえ', 'あ・がる'] },
  { kanji: '下', level: 'N5', meanings: ['Hạ', 'Dưới', 'Xuống'], onyomi: ['カ', 'ゲ'], kunyomi: ['した', 'さ・がる'] },
  { kanji: '中', level: 'N5', meanings: ['Trung', 'Trong', 'Giữa'], onyomi: ['チュウ'], kunyomi: ['なか'] },
  { kanji: '大', level: 'N5', meanings: ['Đại', 'Lớn', 'To'], onyomi: ['ダイ', 'タイ'], kunyomi: ['おお・きい'] },
  { kanji: '小', level: 'N5', meanings: ['Tiểu', 'Nhỏ', 'Bé'], onyomi: ['ショウ'], kunyomi: ['ちい・さい', 'こ'] },
  { kanji: '本', level: 'N5', meanings: ['Bản', 'Sách', 'Gốc', 'Thật'], onyomi: ['ホン'], kunyomi: ['もと'] },
  { kanji: '人', level: 'N5', meanings: ['Nhân', 'Người'], onyomi: ['ジン', 'ニン'], kunyomi: ['ひと'] },
  { kanji: '今', level: 'N5', meanings: ['Kim', 'Bây giờ', 'Nay'], onyomi: ['コン', 'キン'], kunyomi: ['いま'] },
  { kanji: '寺', level: 'N5', meanings: ['Tự', 'Chùa'], onyomi: ['ジ'], kunyomi: ['てら'] },
  { kanji: '時', level: 'N5', meanings: ['Thời', 'Giờ', 'Thời gian'], onyomi: ['ジ'], kunyomi: ['とき'] },
  { kanji: '半', level: 'N5', meanings: ['Bán', 'Nửa', 'Rưỡi'], onyomi: ['ハン'], kunyomi: ['なか・ば'] },
  { kanji: '刀', level: 'N5', meanings: ['Đao', 'Kiếm', 'Dao'], onyomi: ['トウ'], kunyomi: ['かたな'] },
  { kanji: '分', level: 'N5', meanings: ['Phân', 'Phút', 'Hiểu', 'Phần'], onyomi: ['ブン', 'フン', 'ブ'], kunyomi: ['わ・かる', 'わ・ける'] },
  { kanji: '何', level: 'N5', meanings: ['Hà', 'Cái gì'], onyomi: ['カ'], kunyomi: ['なに', 'なん'] },
  { kanji: '前', level: 'N5', meanings: ['Tiền', 'Trước'], onyomi: ['ゼン'], kunyomi: ['まえ'] },
  { kanji: '後', level: 'N5', meanings: ['Hậu', 'Sau'], onyomi: ['ゴ', 'コウ'], kunyomi: ['うし・ろ', 'あと', 'おく・れる'] },
  { kanji: '午', level: 'N5', meanings: ['Ngọ', 'Buổi trưa'], onyomi: ['ゴ'], kunyomi: [] },
  { kanji: '早', level: 'N5', meanings: ['Tảo', 'Sớm'], onyomi: ['ソウ', 'サッ'], kunyomi: ['はや・い'] },
  { kanji: '間', level: 'N5', meanings: ['Gian', 'Khoảng giữa', 'Khoảng thời gian'], onyomi: ['カン', 'ケン'], kunyomi: ['あいだ', 'ま'] },
  { kanji: '週', level: 'N5', meanings: ['Chu', 'Tuần'], onyomi: ['シュウ'], kunyomi: [] },
  { kanji: '東', level: 'N5', meanings: ['Đông', 'Phía Đông'], onyomi: ['トウ'], kunyomi: ['ひがし'] },
  { kanji: '西', level: 'N5', meanings: ['Tây', 'Phía Tây'], onyomi: ['セイ', 'サイ'], kunyomi: ['にし'] },
  { kanji: '南', level: 'N5', meanings: ['Nam', 'Phía Nam'], onyomi: ['ナン'], kunyomi: ['みなみ'] },
  { kanji: '北', level: 'N5', meanings: ['Bắc', 'Phía Bắc'], onyomi: ['ホク'], kunyomi: ['きた'] },
  { kanji: '口', level: 'N5', meanings: ['Khẩu', 'Miệng', 'Cửa'], onyomi: ['コウ', 'ク'], kunyomi: ['くち'] },
  { kanji: '目', level: 'N5', meanings: ['Mục', 'Mắt'], onyomi: ['モク', 'ボク'], kunyomi: ['め'] },
  { kanji: '耳', level: 'N5', meanings: ['Nhĩ', 'Tai'], onyomi: ['ジ'], kunyomi: ['みみ'] },
  { kanji: '手', level: 'N5', meanings: ['Thủ', 'Tay'], onyomi: ['シュ'], kunyomi: ['て'] },
  { kanji: '足', level: 'N5', meanings: ['Túc', 'Chân', 'Đầy đủ'], onyomi: ['ソク'], kunyomi: ['あし', 'た・りる'] },
  { kanji: '力', level: 'N5', meanings: ['Lực', 'Sức mạnh'], onyomi: ['リョク', 'リキ'], kunyomi: ['ちから'] },
  { kanji: '父', level: 'N5', meanings: ['Phụ', 'Bố', 'Cha'], onyomi: ['フ'], kunyomi: ['ちち'] },
  { kanji: '母', level: 'N5', meanings: ['Mẫu', 'Mẹ'], onyomi: ['ボ'], kunyomi: ['はは'] },
  { kanji: '先', level: 'N5', meanings: ['Tiên', 'Trước'], onyomi: ['セン'], kunyomi: ['さき'] },
  { kanji: '生', level: 'N5', meanings: ['Sinh', 'Sống', 'Sinh ra', 'Học sinh'], onyomi: ['セイ', 'ショウ'], kunyomi: ['い・きる', 'う・まれる', 'なま'] },
  { kanji: '学', level: 'N5', meanings: ['Học', 'Học tập'], onyomi: ['ガク'], kunyomi: ['まな・ぶ'] },
  { kanji: '校', level: 'N5', meanings: ['Hiệu', 'Trường học'], onyomi: ['コウ'], kunyomi: [] },
  { kanji: '友', level: 'N5', meanings: ['Hữu', 'Bạn bè'], onyomi: ['ユウ'], kunyomi: ['とも'] },
  { kanji: '女', level: 'N5', meanings: ['Nữ', 'Phụ nữ'], onyomi: ['ジョ', 'ニョ'], kunyomi: ['おんな', 'め'] },
  { kanji: '男', level: 'N5', meanings: ['Nam', 'Đàn ông'], onyomi: ['ダン', 'ナン'], kunyomi: ['おとこ'] },
  { kanji: '子', level: 'N5', meanings: ['Tử', 'Con cái'], onyomi: ['シ', 'ス'], kunyomi: ['こ'] },
  { kanji: '私', level: 'N5', meanings: ['Tư', 'Tôi', 'Cá nhân'], onyomi: ['シ'], kunyomi: ['わたし', 'わたくし'] },
  { kanji: '文', level: 'N5', meanings: ['Văn', 'Câu', 'Văn tự'], onyomi: ['ブン', 'モン'], kunyomi: ['ふみ'] },
  { kanji: '字', level: 'N5', meanings: ['Tự', 'Chữ', 'Ký tự'], onyomi: ['ジ'], kunyomi: ['あざ'] },
  { kanji: '名', level: 'N5', meanings: ['Danh', 'Tên', 'Nổi tiếng'], onyomi: ['メイ', 'ミョウ'], kunyomi: ['な'] },
  { kanji: '白', level: 'N5', meanings: ['Bạch', 'Trắng'], onyomi: ['ハク', 'ビャク'], kunyomi: ['しろ・い'] },
  { kanji: '黒', level: 'N5', meanings: ['Hắc', 'Đen'], onyomi: ['コク'], kunyomi: ['くろ・い'] },
  { kanji: '赤', level: 'N5', meanings: ['Xích', 'Đỏ'], onyomi: ['セキ', 'シャク'], kunyomi: ['あか・い'] },
  { kanji: '青', level: 'N5', meanings: ['Thanh', 'Xanh'], onyomi: ['セイ', 'ショウ'], kunyomi: ['あお・い'] },
  { kanji: '天', level: 'N5', meanings: ['Thiên', 'Trời'], onyomi: ['テン'], kunyomi: ['あめ', 'あま'] },
  { kanji: '気', level: 'N5', meanings: ['Khí', 'Khí sắc', 'Tinh thần', 'Khí trời'], onyomi: ['キ', 'ケ'], kunyomi: [] },
  { kanji: '雨', level: 'N5', meanings: ['Vũ', 'Mưa'], onyomi: ['ウ'], kunyomi: ['あめ', 'あま'] },
  { kanji: '雪', level: 'N5', meanings: ['Tuyết', 'Tuyết rơi'], onyomi: ['セツ'], kunyomi: ['ゆき'] },
  { kanji: '空', level: 'N5', meanings: ['Không', 'Bầu trời', 'Trống rỗng'], onyomi: ['クウ'], kunyomi: ['そら', 'あ・く', 'から'] },
  { kanji: '風', level: 'N5', meanings: ['Phong', 'Gió', 'Phong cách'], onyomi: ['フウ', 'フ'], kunyomi: ['かぜ'] },
  { kanji: '魚', level: 'N5', meanings: ['Ngư', 'Cá'], onyomi: ['ギョ'], kunyomi: ['さかな', 'うお'] },
  { kanji: '肉', level: 'N5', meanings: ['Nhục', 'Thịt'], onyomi: ['ニク'], kunyomi: [] },
  { kanji: '犬', level: 'N5', meanings: ['Khuyển', 'Chó'], onyomi: ['ケン'], kunyomi: ['いぬ'] },
  { kanji: '花', level: 'N5', meanings: ['Hoa', 'Bông hoa'], onyomi: ['カ'], kunyomi: ['はな'] },
  { kanji: '車', level: 'N5', meanings: ['Xa', 'Xe'], onyomi: ['シャ'], kunyomi: ['くるま'] },
  { kanji: '門', level: 'N5', meanings: ['Môn', 'Cổng'], onyomi: ['モン'], kunyomi: ['かど'] },
  { kanji: '店', level: 'N5', meanings: ['Điếm', 'Cửa hàng', 'Tiệm'], onyomi: ['テン'], kunyomi: ['みせ'] },
  { kanji: '駅', level: 'N5', meanings: ['Dịch', 'Nhà ga'], onyomi: ['エキ'], kunyomi: [] },
  { kanji: '道', level: 'N5', meanings: ['Đạo', 'Đường', 'Đạo lộ'], onyomi: ['ドウ', 'トウ'], kunyomi: ['みち'] },
  { kanji: '社', level: 'N5', meanings: ['Xã', 'Công ty', 'Đền thờ'], onyomi: ['シャ'], kunyomi: ['やしろ'] },
  { kanji: '国', level: 'N5', meanings: ['Quốc', 'Đất nước', 'Quốc gia'], onyomi: ['コク'], kunyomi: ['くに'] },
  { kanji: '外', level: 'N5', meanings: ['Ngoại', 'Bên ngoài'], onyomi: ['ガイ', 'ゲ'], kunyomi: ['そと', 'ほか', 'はず・す'] },
  { kanji: '見', level: 'N5', meanings: ['Kiến', 'Nhìn', 'Xem'], onyomi: ['ケン'], kunyomi: ['み・る', 'み・える'] },
  { kanji: '聞', level: 'N5', meanings: ['Văn', 'Nghe', 'Hỏi'], onyomi: ['ブン', 'モン'], kunyomi: ['き・く', 'き・こえる'] },
  { kanji: '読', level: 'N5', meanings: ['Độc', 'Đọc'], onyomi: ['ドク', 'トク'], kunyomi: ['よ・む'] },
  { kanji: '書', level: 'N5', meanings: ['Thư', 'Viết', 'Sách'], onyomi: ['ショ'], kunyomi: ['か・く'] },
  { kanji: '話', level: 'N5', meanings: ['Thoại', 'Nói chuyện', 'Câu chuyện'], onyomi: ['ワ'], kunyomi: ['はな・す', 'はなし'] },
  { kanji: '買', level: 'N5', meanings: ['Mãi', 'Mua'], onyomi: ['バイ'], kunyomi: ['か・う'] },
  { kanji: '食', level: 'N5', meanings: ['Thực', 'Ăn', 'Món ăn'], onyomi: ['ショク', 'ジキ'], kunyomi: ['た・べる', 'く・う'] },
  { kanji: '飲', level: 'N5', meanings: ['Ẩm', 'Uống'], onyomi: ['イン'], kunyomi: ['の・む'] },
  { kanji: '行', level: 'N5', meanings: ['Hành', 'Đi', 'Tổ chức'], onyomi: ['コウ', 'ギョウ'], kunyomi: ['い・く', 'おこな・う'] },
  { kanji: '来', level: 'N5', meanings: ['Lai', 'Đến'], onyomi: ['ライ'], kunyomi: ['く・る', 'き・たる'] },
  { kanji: '休', level: 'N5', meanings: ['Hưu', 'Nghỉ ngơi'], onyomi: ['キュウ'], kunyomi: ['やす・む'] },
  { kanji: '会', level: 'N5', meanings: ['Hội', 'Gặp gỡ', 'Hội họp'], onyomi: ['カイ', 'エ'], kunyomi: ['あ・う'] }
];
