module.exports = [
  { kanji: '議', level: 'N2', meanings: ['Nghị', 'Hội nghị', 'Nghị luận'], onyomi: ['ギ'], kunyomi: [] },
  { kanji: '論', level: 'N2', meanings: ['Luận', 'Thảo luận', 'Lý luận'], onyomi: ['ロン'], kunyomi: [] },
  { kanji: '挙', level: 'N2', meanings: ['Cử', 'Tuyển cử', 'Nâng lên'], onyomi: ['キョ'], kunyomi: ['あ・げる', 'あ・がる'] },
  { kanji: '策', level: 'N2', meanings: ['Sách', 'Chính sách', 'Kế sách'], onyomi: ['サク'], kunyomi: [] },
  { kanji: '政', level: 'N2', meanings: ['Chính', 'Chính trị', 'Chính phủ'], onyomi: ['セイ', 'ショウ'], kunyomi: ['まつりごと'] },
  { kanji: '治', level: 'N2', meanings: ['Trị', 'Chữa trị', 'Thống trị'], onyomi: ['ジ', 'チ'], kunyomi: ['おさ・める', 'なお・る'] },
  { kanji: '経', level: 'N2', meanings: ['Kinh', 'Kinh tế', 'Trải qua'], onyomi: ['ケイ', 'キョウ'], kunyomi: ['へ・る'] },
  { kanji: '済', level: 'N2', meanings: ['Tế', 'Kinh tế', 'Hoàn tất'], onyomi: ['サイ', 'セイ'], kunyomi: ['す・む', 'す・ます'] },
  { kanji: '財', level: 'N2', meanings: ['Tài', 'Tài sản', 'Tài chính'], onyomi: ['ザイ', 'サイ'], kunyomi: [] },
  { kanji: '価', level: 'N2', meanings: ['Giá', 'Giá trị', 'Giá cả'], onyomi: ['カ'], kunyomi: ['あたい'] },
  { kanji: '格', level: 'N2', meanings: ['Cách', 'Tư cách', 'Giá cả'], onyomi: ['カク', 'コウ'], kunyomi: [] },
  { kanji: '営', level: 'N2', meanings: ['Doanh', 'Kinh doanh', 'Quản lý'], onyomi: ['エイ'], kunyomi: ['いとな・む'] },
  { kanji: '業', level: 'N2', meanings: ['Nghiệp', 'Công việc', 'Nghề nghiệp'], onyomi: ['ギョウ', 'ゴウ'], kunyomi: ['わざ'] },
  { kanji: '務', level: 'N2', meanings: ['Vụ', 'Nhiệm vụ', 'Công vụ'], onyomi: ['ム'], kunyomi: ['つと・める'] },
  { kanji: '確', level: 'N2', meanings: ['Xác', 'Chính xác', 'Xác nhận'], onyomi: ['カク'], kunyomi: ['たし・か', 'たし・かめる'] },
  { kanji: '認', level: 'N2', meanings: ['Nhận', 'Xác nhận', 'Thừa nhận'], onyomi: ['ニン'], kunyomi: ['みと・める'] },
  { kanji: '証', level: 'N2', meanings: ['Chứng', 'Bằng chứng', 'Chứng minh'], onyomi: ['ショウ'], kunyomi: ['あかし'] },
  { kanji: '明', level: 'N2', meanings: ['Minh', 'Chứng minh', 'Sáng sủa'], onyomi: ['メイ', 'ミョウ'], kunyomi: ['あか・るい'] },
  { kanji: '規', level: 'N2', meanings: ['Quy', 'Quy định', 'Quy tắc'], onyomi: ['キ'], kunyomi: [] },
  { kanji: '則', level: 'N2', meanings: ['Tắc', 'Quy tắc', 'Nguyên tắc'], onyomi: ['ソク'], kunyomi: ['のっと・る'] },
  { kanji: '制', level: 'N2', meanings: ['Chế', 'Quy chế', 'Chế độ'], onyomi: ['セイ'], kunyomi: [] },
  { kanji: '度', level: 'N2', meanings: ['Độ', 'Chế độ', 'Mức độ'], onyomi: ['ド', 'ト'], kunyomi: ['たび'] },
  { kanji: '限', level: 'N2', meanings: ['Hạn', 'Giới hạn', 'Kỳ hạn'], onyomi: ['ゲン'], kunyomi: ['かぎ・る'] },
  { kanji: '権', level: 'N2', meanings: ['Quyền', 'Quyền hạn', 'Quyền lợi'], onyomi: ['ケン', 'ゴン'], kunyomi: [] },
  { kanji: '利', level: 'N2', meanings: ['Lợi', 'Lợi ích', 'Tiện lợi'], onyomi: ['リ'], kunyomi: ['き・く'] },
  { kanji: '益', level: 'N2', meanings: ['Ích', 'Lợi ích', 'Hữu ích'], onyomi: ['エキ', 'ヤク'], kunyomi: ['ま・す'] },
  { kanji: '損', level: 'N2', meanings: ['Tổn', 'Tổn thất', 'Thiệt hại'], onyomi: ['ソン'], kunyomi: ['そこ・なう'] },
  { kanji: '害', level: 'N2', meanings: ['Hại', 'Tác hại', 'Thiệt hại'], onyomi: ['ガイ'], kunyomi: [] },
  { kanji: '保', level: 'N2', meanings: ['Bảo', 'Bảo hiểm', 'Bảo đảm'], onyomi: ['ホ', 'ホウ'], kunyomi: ['たも・つ'] },
  { kanji: '障', level: 'N2', meanings: ['Chướng', 'Bảo đảm', 'Trở ngại'], onyomi: ['ショウ'], kunyomi: ['さわ・る'] }
];
