module.exports = [
  { kanji: '覇', level: 'N1', meanings: ['Bá', 'Bá quyền', 'Tranh bá'], onyomi: ['ハ'], kunyomi: [] },
  { kanji: '抑', level: 'N1', meanings: ['Ức', 'Đàn áp', 'Ức chế'], onyomi: ['ヨク'], kunyomi: ['おさ・える'] },
  { kanji: '揚', level: 'N1', meanings: ['Dương', 'Tuyên dương', 'Bay lên'], onyomi: ['ヨウ'], kunyomi: ['あ・げる', 'あ・がる'] },
  { kanji: '暫', level: 'N1', meanings: ['Tạm', 'Tạm thời', 'Chốc lát'], onyomi: ['ザン'], kunyomi: ['しばら・く'] },
  { kanji: '漸', level: 'N1', meanings: ['Tiệm', 'Tiệm tiến', 'Dần dần'], onyomi: ['ゼン'], kunyomi: ['ようや・く'] },
  { kanji: '諮', level: 'N1', meanings: ['Ti', 'Tham vấn', 'Hỏi ý kiến'], onyomi: ['シ'], kunyomi: ['はか・る'] },
  { kanji: '賠', level: 'N1', meanings: ['Bồi', 'Bồi thường'], onyomi: ['バイ'], kunyomi: [] },
  { kanji: '償', level: 'N1', meanings: ['Thường', 'Bồi thường', 'Đền bù'], onyomi: ['ショウ'], kunyomi: ['つぐな・う'] },
  { kanji: '騰', level: 'N1', meanings: ['Đằng', 'Tăng vọt', 'Tăng giá'], onyomi: ['トウ'], kunyomi: [] },
  { kanji: '唆', level: 'N1', meanings: ['Toa', 'Xúi giục', 'Ám chỉ'], onyomi: ['サ'], kunyomi: ['そそのか・す'] },
  { kanji: '妥', level: 'N1', meanings: ['Thỏa', 'Thỏa hiệp', 'Thỏa đáng'], onyomi: ['ダ'], kunyomi: [] },
  { kanji: '轄', level: 'N1', meanings: ['Hạt', 'Quản hạt', 'Cai quản'], onyomi: ['カツ'], kunyomi: ['くさび'] },
  { kanji: '頻', level: 'N1', meanings: ['Tần', 'Tần suất', 'Thường xuyên'], onyomi: ['ヒン'], kunyomi: ['しき・りに'] },
  { kanji: '顕', level: 'N1', meanings: ['Hiển', 'Hiển nhiên', 'Rõ ràng'], onyomi: ['ケン'], kunyomi: ['あきらか', 'あらわ・れる'] },
  { kanji: '躍', level: 'N1', meanings: ['Dược', 'Nhảy vọt', 'Hoạt dược'], onyomi: ['ヤク'], kunyomi: ['おど・る'] },
  { kanji: '覆', level: 'N1', meanings: ['Phúc', 'Lật đổ', 'Bao phủ'], onyomi: ['フク'], kunyomi: ['おお・う', 'くつがえ・す'] },
  { kanji: '促', level: 'N1', meanings: ['Xúc', 'Thúc đẩy', 'Xúc tiến'], onyomi: ['ソク'], kunyomi: ['うなが・す'] },
  { kanji: '慮', level: 'N1', meanings: ['Lự', 'Suy nghĩ sâu xa', 'Lưỡng lự'], onyomi: ['リョ'], kunyomi: ['おもんぱか・る'] },
  { kanji: '陥', level: 'N1', meanings: ['Hãm', 'Rơi vào', 'Hãm hại'], onyomi: ['カン'], kunyomi: ['おちい・る', 'おとしい・れる'] },
  { kanji: '拠', level: 'N1', meanings: ['Cứ', 'Căn cứ', 'Bằng chứng'], onyomi: ['キョ', 'コ'], kunyomi: ['よ・る'] },
  { kanji: '匿', level: 'N1', meanings: ['Nặc', 'Ẩn danh', 'Nặc danh'], onyomi: ['トク'], kunyomi: ['かく・す'] },
  { kanji: '濫', level: 'N1', meanings: ['Lạm', 'Lạm dụng', 'Tràn lan'], onyomi: ['ラン'], kunyomi: ['みだ・りに'] },
  { kanji: '蔑', level: 'N1', meanings: ['Miệt', 'Khinh miệt', 'Xem thường'], onyomi: ['ベツ'], kunyomi: ['さげす・む'] },
  { kanji: '弊', level: 'N1', meanings: ['Tệ', 'Tệ hại', 'Khuyết điểm'], onyomi: ['ヘイ'], kunyomi: [] },
  { kanji: '阻', level: 'N1', meanings: ['Trở', 'Ngăn cản', 'Trở ngại'], onyomi: ['ソ'], kunyomi: ['はば・む'] },
  { kanji: '怠', level: 'N1', meanings: ['Đãi', 'Lười biếng', 'Chểnh mảng'], onyomi: ['タイ'], kunyomi: ['おこた・る', 'なま・ける'] },
  { kanji: '侮', level: 'N1', meanings: ['Vũ', 'Khinh bỉ', 'Coi thường'], onyomi: ['ブ'], kunyomi: ['あなど・る'] },
  { kanji: '偏', level: 'N1', meanings: ['Thiên', 'Lệch lạc', 'Thiên vị'], onyomi: ['ヘン'], kunyomi: ['かたよ・る'] },
  { kanji: '誇', level: 'N1', meanings: ['Khoa', 'Tự hào', 'Khoe khoang'], onyomi: ['コ'], kunyomi: ['ほこ・る'] },
  { kanji: '醸', level: 'N1', meanings: ['Nhưỡng', 'Ủ rượu', 'Tạo ra không khí'], onyomi: ['ジョウ'], kunyomi: ['かも・す'] }
];
